<a href="https://colab.research.google.com/github/bogdanparvu18/msc-graduate-project/blob/main/notebooks/phase2/phase2_07_image_quality_control.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Phase 2 — Sector 7: Image Quality Control with Deferred Splits

This standalone Colab notebook consumes the current **published GitHub main S1–S6 chain**, pinned once per input load. It accepts S6's `temporal_context_split_policy="deferred"`, preserves every annotation and in-bounds temporal reference, and computes technical image metrics independently of final train/validation/test assignment.

All official images are checked against S5's inherited source SHA-256 values. Temporal images are also checked against S6's audit and extraction records, and extracted-image sidecars must agree with the published source-video and decoder provenance. Images are staged to `/content/mmvqa_sector7`; QC reads SSD copies. Existing valid copies and verified metric batches can be reused after interruption.

**`final_split` remains null, `split_assignment_status="pending"`, and `training_ready=false`.** Old splits are provenance only. Statistical quantile thresholds and their outlier decisions remain uncalibrated until final splits are independently established and validated.

## 1. Dependencies and centralized imports

NumPy/OpenCV provide the CPU path. Optional CuPy and NVIDIA nvImageCodec enable GPU-first decoding and metric computation; unsupported formats or unavailable CUDA use the recorded CPU fallback. Video decoding and image extraction remain S6 responsibilities.

The GPU install log is `/tmp/sector7_gpu_install.log`. A successful CPU run verifies the data workflow but does not validate GPU performance.

In [1]:
%pip install -q "numpy>=1.26,<3" "pandas>=2.2,<3" "pyarrow>=16" tqdm "opencv-python-headless>=4.10,<6"
# Optional GPU libraries; inspect this log if GPU decoding is unavailable.
!python -m pip install -q cupy-cuda12x "nvidia-nvimgcodec-cu12[nvjpeg]" > /tmp/sector7_gpu_install.log 2>&1 || true

In [2]:
from pathlib import Path, PurePosixPath
from datetime import datetime, timezone
from types import CodeType, FunctionType
from concurrent.futures import ThreadPoolExecutor, as_completed, wait, FIRST_COMPLETED
from contextlib import contextmanager
from urllib.parse import unquote, urlsplit
import base64
import copy
import hashlib
import gzip
import importlib.metadata
import json
import math
import os
import platform
import re
import shutil
import stat
import subprocess
import tempfile
import time
import warnings

import cv2
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from IPython.display import display

# Optional GPU SDK imports never abort a CPU-capable execution.
S7_GPU_IMPORT_ERRORS = {}
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    try:
        import cupy as cp
    except Exception as error:
        cp = None
        S7_GPU_IMPORT_ERRORS['cupy'] = type(error).__name__
    try:
        # Suppress repetitive SDK warning logs; pipeline fallback warns once.
        os.environ['PYNVIMGCODEC_VERBOSITY'] = '1'
        from nvidia import nvimgcodec
    except Exception as error:
        nvimgcodec = None
        S7_GPU_IMPORT_ERRORS['nvimagecodec'] = type(error).__name__

try:
    from google.colab import drive, userdata
except ImportError:
    drive, userdata = None, None

## 2. Declarative configuration

`BOOTSTRAP.storage_root` identifies the mounted persistent data root. `local_workspace_root` identifies a separate SSD workspace for pinned metadata, staged images and resumable QC batches. Do not place it below the Drive mount.

The reader pins `main` once and follows catalog-declared metadata. Drive supplies image bytes, not authoritative manifests. A changed upstream producer requires a compatible newly published S6 bundle.

`qc_decode_batch_size=64` bounds each decoder call; `qc_checkpoint_batch_size=1000` defines one reusable metric checkpoint. `qc_workers=16` bounds concurrent file operations. Quantile settings are retained for a future explicit calibration stage; `qc_threshold_fit_split="deferred"` forbids fitting on the historical S4 split. Publication is disabled with `push=False`.

In [17]:
BOOTSTRAP = {
    "repo_url": "https://github.com/bogdanparvu18/msc-graduate-project.git",
    "branch": "main",
    "storage_root": "/content/drive/MyDrive/MMVQA_Clinical",
    "local_workspace_root": "/content/mmvqa_sector7",
    "mount_google_drive": True,
    "sector3_dir": None,
    "sector4_dir": None,
    "sector5_dir": None,
    "sector6_dir": None,
    "sector2_results_dir": None,
    "sector2_manifests_dir": None,
    "sector2_configs_dir": None,
}

S7_DEFAULTS = {
    "qc_enabled": True,
    "qc_fov_radius_fraction": 0.95,
    "qc_underexposed_pixel_threshold": 20,
    "qc_overexposed_pixel_threshold": 240,
    "qc_specular_value_threshold": 240,
    "qc_specular_saturation_threshold": 30,
    "qc_blur_quantile": 0.01,
    "qc_contrast_quantile": 0.01,
    "qc_brightness_low_quantile": 0.01,
    "qc_brightness_high_quantile": 0.99,
    "qc_threshold_fit_split": "deferred",
    "qc_workers": 16,  # Local compressed-file reads during QC.
    "qc_staging_workers": 32,  # Independent Drive-to-SSD transfer concurrency.
    "qc_checkpoint_batch_size": 1000,
    "qc_staging_reserve_bytes": 2 * 1024**3,
    "qc_max_image_bytes": 64 * 1024**2,
    "qc_decoder": "nvimagecodec",
    "qc_gpu_backend_policy": "gpu_preferred",
    "qc_gpu_id": 0,
    "qc_decode_batch_size": 64,
}

# None inherits the saved effective S6 setting, then uses S7_DEFAULTS if absent.
# Quantile fitting awaits validated final splits. GPU decoding has CPU fallback.
# Review copy: publication is disabled; no notebook upload is performed.
SECTOR7_SETTINGS = {
    **{key: None for key in S7_DEFAULTS},
    "qc_enabled": True,
    "qc_threshold_fit_split": "deferred",
    "qc_workers": 16,
    "qc_staging_workers": 32,
    "qc_decoder": "nvimagecodec",
    "qc_gpu_backend_policy": "gpu_preferred",
    "qc_gpu_id": 0,
    "qc_decode_batch_size": 64,
    "local_output_dir": "outputs/phase2/sector7",
    "export_dir": "outputs/phase2/sector7",
    "push": True,
    "dry_run": False,
    "github_overrides": {"token_secret_name": "GITHUB_TOKEN"},
}

## 3. Pinned published input contracts

Read and validate the current S1–S6 catalog chain, configuration, schemas, content hashes and annotation/frame identities from one GitHub commit. Follow active catalog entries rather than timestamp filename guesses. Rebase media access paths from portable references onto the selected persistent root.

S6's `upstream_split`, `context_frame_upstream_split` and conflict diagnostics are checked provenance. Shared context across those assignments is valid. Legacy split-exclusion bundles are rejected with a rerun/migration error. Nothing in this section extracts videos or assigns final splits.

In [4]:
# ------------------------------------------------------------------------------
# Read-only published-main contracts. Metadata authority is one pinned Git
# snapshot; Google Drive supplies image bytes only in the explicit QC I/O stage.
# Current producer validation helpers are embedded, never downloaded/executed.
# ------------------------------------------------------------------------------

SECTOR5_DEFAULTS = {"segment_max_gap_frames": 1, "minimum_verified_segment_frames": 2}

P3_NULL = "\\N"


S3_EXECUTION_METADATA_KEYS = frozenset({
    "run_id", "run_context", "run_datetime", "run_timestamp", "run_date", "run_time",
    "timestamp", "date", "time", "execution_date", "execution_time",
    "created_at", "created_at_utc", "created_utc", "saved_at", "saved_at_utc", "saved_utc",
    "started_at", "started_at_utc", "started_utc", "finished_at", "finished_at_utc", "finished_utc",
    "generated_at", "generated_at_utc", "generated_utc", "updated_at", "updated_at_utc", "updated_utc",
    "modified_at", "modified_at_utc", "modified_utc",
    "source_commit", "source_commit_sha", "source_commit_hash", "source_revision", "config_source_commit",
    "commit", "commit_sha", "head_commit", "current_commit", "repository_commit",
    "publication_receipt", "receipt", "last_publication",
    "source_configs", "config_provenance", "config_conflict_report", "lineage",
    "source_notebooks", "source_config_provenance", "config_sources", "literal_notebooks", "literal_configs",
    "input_sha256", "state_sha256", "upstream_states", "upstream_alignment_run_id",
    "notebook_path", "notebook_sha256", "source_notebook_path", "source_notebook_sha256",
    "source_config_path", "source_config_sha256", "source_snapshot_path", "source_snapshot_sha256",
    "config_snapshot_path", "config_snapshot_sha256", "snapshot_path", "snapshot_sha256",
    "source_config_file", "source_config_hash", "source_snapshot_file", "source_snapshot_hash",
    "config_snapshot_file", "config_snapshot_hash", "snapshot_file", "snapshot_hash",
    "config_inheritance_policy", "taxonomy_validation_policy",
})


def _s3_semantic_json_value(value):
    """Pure conversion to canonical JSON-compatible values; no I/O or clock access."""
    if value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, dict):
        return {str(key): _s3_semantic_json_value(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_s3_semantic_json_value(item) for item in value]
    if isinstance(value, (set, frozenset)):
        values = [_s3_semantic_json_value(item) for item in value]
        return sorted(values, key=lambda item: json.dumps(item, sort_keys=True))
    if isinstance(value, (Path, PurePosixPath)):
        return str(value)
    if isinstance(value, np.generic):
        return _s3_semantic_json_value(value.item())
    if isinstance(value, float) and not np.isfinite(value):
        raise ValueError("Semantic configuration must not contain NaN or infinite values.")
    if value is None or isinstance(value, (str, bool, int, float)):
        return value
    raise TypeError(f"Unsupported semantic configuration value: {type(value).__name__}")


def _s3_semantic_json(value):
    return json.dumps(_s3_semantic_json_value(value), ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"), allow_nan=False)


def _s3_semantic_digest(value):
    return hashlib.sha256(_s3_semantic_json(value).encode("utf-8")).hexdigest()


def sector3_semantic_config(config):
    """Project authored effective values, excluding execution/source bookkeeping only.

    Full source snapshots and current execution metadata remain available in the
    saved envelope. Authored paths, thresholds, publication settings (including
    push/dry_run), and unknown substantive config keys retain their meaning.
    """
    if not isinstance(config, dict):
        raise TypeError("Sector 3 semantic configuration requires a dictionary.")
    def project(value):
        if isinstance(value, dict):
            return {str(key): project(item) for key, item in value.items()
                    if str(key).lower() not in S3_EXECUTION_METADATA_KEYS}
        if isinstance(value, (list, tuple)):
            return [project(item) for item in value]
        return _s3_semantic_json_value(value)
    return project(config)


def sector3_semantic_config_fingerprint(config):
    """Stable identity of authored configuration, independent of execution time."""
    return _s3_semantic_digest(sector3_semantic_config(config))


def _p3_json_default(value):
    if value is pd.NA or value is pd.NaT:
        return None
    if isinstance(value, pd.DataFrame):
        return {"type": "dataframe", "columns": list(value.columns),
                "dtypes": {str(column): str(dtype) for column, dtype in value.dtypes.items()},
                "records": value.astype(object).where(value.notna(), None).to_dict("records")}
    if isinstance(value, (Path, PurePosixPath, datetime, pd.Timestamp)):
        return str(value)
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, (set, tuple)):
        return sorted(value) if isinstance(value, set) else list(value)
    raise TypeError(f"Unsupported Sector 3 JSON value: {type(value).__name__}")


def _p3_json_text(value):
    return json.dumps(value, sort_keys=True, indent=2, ensure_ascii=False,
                      allow_nan=False, default=_p3_json_default) + "\n"


def _p3_json_hash(value):
    return hashlib.sha256(_p3_json_text(value).encode("utf-8")).hexdigest()


def _p3_file_hash(path):
    with Path(path).open("rb") as source:
        return hashlib.file_digest(source, "sha256").hexdigest()


def _p3_relative(value):
    path = PurePosixPath(str(value))
    if path.is_absolute() or ".." in path.parts or len(path.parts) != 2:
        raise ValueError(f"Sector 3 artifacts must be flat relative paths: {value!r}")
    if path.parts[0] not in {"configs", "results", "reports"}:
        raise ValueError(f"Unexpected Sector 3 artifact group: {value!r}")
    return path.as_posix()


def _p3_safe_path(root, relative):
    path = root / _p3_relative(relative)
    if path.is_symlink() or root not in path.resolve().parents or path.parent.is_symlink():
        raise RuntimeError(f"Unsafe Sector 3 artifact path: {relative}")
    return path


def _p3_schema(frame):
    columns = []
    for column, dtype in frame.dtypes.items():
        descriptor = {"name": column, "dtype": str(dtype)}
        if isinstance(dtype, pd.StringDtype):
            descriptor["string_storage"] = dtype.storage
        if str(dtype) == "object":
            descriptor["object_kind"] = pd.api.types.infer_dtype(frame[column], skipna=True)
        if isinstance(dtype, pd.CategoricalDtype):
            descriptor.update({"categories": list(dtype.categories), "ordered": dtype.ordered})
        columns.append(descriptor)
    return {"rows": len(frame), "columns": columns, "column_axis_name": frame.columns.name,
            "csv_null_marker": P3_NULL, "schema_version": 1}


def sector3_table_fingerprint(frame):
    """Hash every value and its dtype schema; no clock or execution metadata is added."""
    if frame.columns.duplicated().any() or not all(isinstance(column, str) for column in frame.columns):
        raise ValueError("Sector 3 tables require unique string column names.")
    normalized = frame.reset_index(drop=True)
    digest = hashlib.sha256(_p3_json_text(_p3_schema(normalized)).encode("utf-8"))
    try:
        # Missing values have one semantic identity, including None/NaN/pd.NA in object columns.
        hash_values = normalized.astype(object).where(normalized.notna(), None)
        values = pd.util.hash_pandas_object(hash_values, index=False, categorize=False)
    except TypeError as error:
        raise TypeError("Sector 3 tables must contain scalar values; canonicalize nested conflict values first.") from error
    digest.update(values.to_numpy(dtype="uint64").astype("<u8", copy=False).tobytes())
    return digest.hexdigest()


def _p3_restore_csv(path, schema):
    frame = pd.read_csv(path, dtype="string", keep_default_na=False)
    expected = [descriptor["name"] for descriptor in schema["columns"]]
    if list(frame.columns) != expected or len(frame) != schema["rows"]:
        raise RuntimeError(f"CSV dimensions differ from saved schema: {path.name}")
    for descriptor in schema["columns"]:
        name, dtype = descriptor["name"], descriptor["dtype"]
        values = frame[name]
        nulls = values.eq(P3_NULL)
        values = values.mask(nulls, pd.NA)
        if dtype == "object":
            kind = descriptor.get("object_kind", "string")
            if kind in {"integer", "floating", "mixed-integer-float", "decimal"}:
                values = pd.to_numeric(values, errors="raise").astype(object)
            elif kind == "boolean":
                values = values.map({"True": True, "False": False}).astype(object)
            elif kind not in {"string", "unicode", "bytes", "empty"}:
                raise RuntimeError(f"Unsupported object CSV dtype {kind!r}: canonicalize this table before saving.")
            else:
                values = values.astype(object)
            frame[name] = values.mask(nulls, None)
        elif dtype in {"bool", "boolean"}:
            if (~nulls & ~values.isin(["True", "False"])).any():
                raise RuntimeError(f"Invalid saved boolean values: {path.name}/{name}")
            frame[name] = values.map({"True": True, "False": False}).astype(dtype)
        elif dtype == "string":
            frame[name] = values.astype(pd.StringDtype(storage=descriptor.get("string_storage", "python")))
        elif dtype == "category":
            category = pd.CategoricalDtype(descriptor["categories"], ordered=descriptor["ordered"])
            if pd.api.types.infer_dtype(descriptor["categories"], skipna=True) in {"integer", "floating", "mixed-integer-float"}:
                values = pd.to_numeric(values, errors="raise")
            frame[name] = values.astype(category)
        elif dtype.startswith("timedelta64"):
            frame[name] = pd.to_timedelta(values).astype(dtype)
        else:
            frame[name] = values.astype(dtype)
    frame.columns.name = schema.get("column_axis_name")
    return frame


def _p3_read_table(root, descriptor):
    path = _p3_safe_path(root, descriptor["relative_path"])
    schema_path = _p3_safe_path(root, descriptor["schema_path"])
    schema = json.loads(schema_path.read_text(encoding="utf-8"))
    if schema.get("fingerprint") != descriptor["fingerprint"] or schema.get("artifact") != descriptor["relative_path"]:
        raise RuntimeError("Table schema disagrees with the committed catalog.")
    frame = pd.read_parquet(path) if path.suffix == ".parquet" else _p3_restore_csv(path, schema)
    if sector3_table_fingerprint(frame) != descriptor["fingerprint"]:
        raise RuntimeError(f"Typed table readback fingerprint failed: {path.name}")
    return frame


def _p3_catalog_meaning(state):
    return {key: state[key] for key in (
        "schema_version", "complete", "processing_signature", "semantic_config_fingerprint",
        "input_sha256", "core_source_sha256", "config_snapshot", "tables", "summary", "artifacts", "obsolete_paths")}


S4_EXECUTION_METADATA_KEYS = frozenset({
    'run_id', 'run_context', 'run_datetime', 'run_timestamp', 'run_date', 'run_time',
    'timestamp', 'date', 'time', 'execution_date', 'execution_time',
    'created_at', 'created_at_utc', 'created_utc', 'saved_at', 'saved_at_utc', 'saved_utc',
    'started_at', 'started_at_utc', 'started_utc', 'finished_at', 'finished_at_utc', 'finished_utc',
    'generated_at', 'generated_at_utc', 'generated_utc', 'updated_at', 'updated_at_utc', 'updated_utc',
    'modified_at', 'modified_at_utc', 'modified_utc',
})


def sector4_semantic_config(config):
    """Exclude clock bookkeeping only from the effective authored Sector 4 config."""
    def project(value):
        if isinstance(value, dict):
            return {str(key): project(item) for key, item in value.items()
                    if str(key).lower() not in S4_EXECUTION_METADATA_KEYS}
        if isinstance(value, (tuple, list)):
            return [project(item) for item in value]
        return _s3_semantic_json_value(value)
    return project(config)


def sector4_semantic_config_fingerprint(config):
    return _s3_semantic_digest(sector4_semantic_config(config))


def io_s5_stage_sector2(repo, commit, stage_root):
    """Stage the exact published S2 export and verify its current S1 references."""

    def object_from_bytes(payload, label):
        value = json.loads(payload)
        if not isinstance(value, dict):
            raise ValueError(f"{label} must contain a JSON object.")
        return value

    def relative_path(value):
        if (not isinstance(value, str) or not value or "\\" in value or "\x00" in value
                or PurePosixPath(value).is_absolute()
                or any(part in {"", ".", ".."} for part in value.split("/"))
                or not value.endswith((".json", ".csv", ".csv.gz", ".parquet", ".md", ".txt"))):
            raise ValueError(f"Unsafe published S2 metadata path: {value!r}")
        return value

    prefix = "outputs/phase2/sector2/"
    root = Path(stage_root) / "outputs/phase2/sector2"
    catalog_bytes = io_s5_git_blob(repo, commit, prefix + "artifact_catalog.json")
    catalog = object_from_bytes(catalog_bytes, "Published S2 export catalog")
    records = catalog.get("artifacts")
    if catalog.get("schema") != "mmvqa-sector2-export-v1" or not isinstance(records, list) or not records:
        raise ValueError("Publish the supported S2 export catalog to main first.")
    logical_paths, physical_paths, hashes, evidence = set(), set(), {}, {}
    for record in records:
        if not isinstance(record, dict):
            raise ValueError("Published S2 catalog contains a malformed artifact.")
        logical, physical = relative_path(record.get("logical_path")), relative_path(record.get("path"))
        encoding = record.get("encoding")
        if (logical.split("/", 1)[0] not in {"configs", "data", "manifests", "reports", "results"}
                or logical in logical_paths or physical in physical_paths
                or encoding not in {"identity", "gzip"}
                or physical != logical + (".gz" if encoding == "gzip" else "")):
            raise ValueError("Published S2 catalog has duplicate or inconsistent paths/encoding.")
        logical_paths.add(logical)
        physical_paths.add(physical)
        packed = io_s5_git_blob(repo, commit, prefix + physical)
        if len(packed) != record.get("bytes") or hashlib.sha256(packed).hexdigest() != record.get("sha256"):
            raise ValueError(f"Published S2 export checksum failed: {logical}")
        raw = gzip.decompress(packed) if encoding == "gzip" else packed
        digest = hashlib.sha256(raw).hexdigest()
        if logical.startswith(("data/", "manifests/", "results/")) and (
                len(raw) != record.get("source_bytes") or digest != record.get("source_sha256")):
            raise ValueError(f"Published S2 producer-byte checksum failed: {logical}")
        target = root / logical
        target.parent.mkdir(parents=True, exist_ok=True)
        _s6_install_metadata(target, raw)
        hashes[logical] = digest
        evidence[logical] = {"repository_path": prefix + physical, "encoding": encoding,
                             "export_sha256": record["sha256"], "source_sha256": digest}

    required = {"data/sector1_audit_export_report.json", "data/physical_image_inventory.csv",
                "data/metadata_clean.parquet", "manifests/video_manifest.csv",
                "manifests/video_manifest_state.json", "results/decode_audit_state.json",
                "results/frame_alignment_state.json", "results/frame_alignment_attempt_state.json"}
    if not required.issubset(logical_paths):
        raise ValueError(f"Published S2 export lacks required metadata: {sorted(required - logical_paths)}")
    config_relative = relative_path(catalog.get("config_file"))
    if (re.fullmatch(r"configs/phase2_02_video_frame_validation_[0-9_]+_config\.json", config_relative) is None
            or config_relative not in logical_paths):
        raise ValueError("Published S2 catalog must select its exact saved configuration.")
    source2_path = root / config_relative
    source2 = object_from_bytes(source2_path.read_bytes(), "Published S2 configuration")
    state_relatives = {"alignment": "results/frame_alignment_state.json",
                       "decode": "results/decode_audit_state.json",
                       "manifest": "manifests/video_manifest_state.json"}
    state_paths = {name: root / relative for name, relative in state_relatives.items()}
    states = {name: object_from_bytes(path.read_bytes(), f"Published S2 {name} state")
              for name, path in state_paths.items()}
    state_hashes = {name: hashes[relative] for name, relative in state_relatives.items()}
    run_id = source2.get("run_id")
    if not run_id or run_id != catalog.get("run_id") or run_id != states["alignment"].get("run_id"):
        raise ValueError("Published S2 catalog, config and alignment run IDs disagree.")
    attempt_relative = "results/frame_alignment_attempt_state.json"
    attempt = object_from_bytes((root / attempt_relative).read_bytes(), "Published S2 latest attempt")
    if (attempt.get("schema") != "frame-alignment-attempt-v1" or attempt.get("complete") is not True
            or attempt.get("status") != "completed" or not attempt.get("attempt_id")
            or attempt["attempt_id"] != states["alignment"].get("attempt_id")
            or attempt.get("run_id") != run_id
            or attempt.get("final_state_sha256") != state_hashes["alignment"]):
        raise ValueError("The latest published S2 alignment attempt is unfinished or differs from its final state.")

    s1_path = "outputs/phase2/sector1/dataset_audit/audit_export_report.json"
    s1_bytes = io_s5_git_blob(repo, commit, s1_path)
    if s1_bytes != (root / "data/sector1_audit_export_report.json").read_bytes():
        raise ValueError("Published S2 used a different S1 catalog. Rerun/publish S2 from current S1.")
    s1_catalog = object_from_bytes(s1_bytes, "Published S1 catalog")
    for name in ("physical_image_inventory.csv", "metadata_clean.parquet"):
        matching = [item for item in s1_catalog.get("artifacts", [])
                    if isinstance(item, dict) and item.get("filename") == name]
        staged = root / "data" / name
        if (len(matching) != 1 or matching[0].get("file_size_bytes") != staged.stat().st_size
                or matching[0].get("file_sha256") != hashes["data/" + name]):
            raise ValueError(f"The current S1 catalog does not certify published S2 {name}.")
    s1_inventory_path = "outputs/phase2/sector1/dataset_audit/physical_image_inventory.csv"
    if io_s5_git_blob(repo, commit, s1_inventory_path) != (root / "data/physical_image_inventory.csv").read_bytes():
        raise ValueError("Published S2 did not consume the current S1 image inventory.")
    return {"source2": source2, "source2_path": source2_path,
            "dirs2": {name: root / name for name in ("results", "manifests", "configs")},
            "state_paths2": state_paths, "states2": states, "state_hashes2": state_hashes,
            "hashes": hashes, "s1_catalog": s1_catalog,
            "s1_catalog_sha256": hashlib.sha256(s1_bytes).hexdigest(),
            "image_inventory_path": root / "data/physical_image_inventory.csv",
            "attempt": attempt, "attempt_sha256": hashes[attempt_relative],
            "artifact_catalog_sha256": hashlib.sha256(catalog_bytes).hexdigest(),
            "evidence": evidence}


def _s5_validate_reference_chain(context3, context4, states2, state_hashes2, raw2, published2):
    """Verify producer certificates without changing the existing consumed-hash keys."""
    def require(condition, message):
        if not condition:
            raise ValueError(message)

    def digest(value, label):
        require(isinstance(value, str) and re.fullmatch(r"[0-9a-f]{64}", value) is not None,
                f"Missing or malformed {label}; rerun/publish the upstream sector.")
        return value

    def same(actual, expected, label):
        require(actual == expected, f"Published producer reference mismatch: {label}. Rerun/publish the upstream sectors in order.")

    lineage3 = context3["envelope"].get("lineage", {})
    lineage4 = context4["envelope"].get("lineage", {})
    references = lineage3.get("raw_references")
    require(isinstance(references, dict), "S3 lacks validated raw-reference lineage. Rerun/publish S3.")
    require(type(references.get("raw_integrity_version")) is int and references["raw_integrity_version"] == 1,
            "S3 raw-reference contract version is unsupported.")
    for field in ("image_snapshot_id", "video_snapshot_id", "video_state_sha256", "s1_catalog_sha256"):
        digest(references.get(field), "S3 " + field)
    for field, actual in (("sector3_state_sha256", context3["state_sha256"]),
                          ("sector3_config_snapshot_sha256", context3["snapshot_sha256"]),
                          ("sector3_content_id", context3["state"]["content_id"])):
        same(lineage4.get(field), actual, "S4 -> S3 " + field)
    expected_video_reference = {key: references[key] for key in (
        "raw_integrity_version", "video_snapshot_id", "video_state_sha256", "video_count")}
    same(lineage4.get("video_reference"), expected_video_reference, "S4 -> S3 video reference")
    for sector, lineage, key in ((3, lineage3, "source_config_provenance"),
                                  (4, lineage4, "source_config_provenance")):
        source = lineage.get(key, {})
        require(isinstance(source, dict) and source.get("source_branch") == "main"
                and source.get("input_source") == "published_git_objects_only"
                and isinstance(source.get("source_commit"), str)
                and re.fullmatch(r"[0-9a-f]{40}", source["source_commit"]) is not None,
                f"S{sector} must first be rerun and published using its GitHub-main input loader.")
    for name in ("manifest", "alignment", "decode"):
        state = states2[name]
        require(state.get("complete") is True and type(state.get("raw_integrity_version")) is int
                and state["raw_integrity_version"] == 1, f"S2 {name} raw-reference contract is incomplete.")
    for name in ("manifest", "alignment"):
        require(states2[name].get("raw_integrity_complete") is True, f"S2 {name} raw integrity is incomplete.")
    require(states2["decode"].get("all_videos_decoded") is True, "S2 decoding is incomplete.")
    same(references["video_state_sha256"], state_hashes2["manifest"], "S3 -> S2 video state")
    same(references["s1_catalog_sha256"], published2["s1_catalog_sha256"], "S3 -> current S1 catalog")
    same(references["image_snapshot_id"], published2["s1_catalog"].get("image_snapshot_id"), "S3 -> S1 image snapshot")
    same(references["video_snapshot_id"], states2["manifest"].get("video_snapshot_id"), "S3 -> S2 video snapshot")
    for name, expected in (("video_state_sha256", state_hashes2["manifest"]),
                           ("video_manifest_sha256", published2["hashes"]["manifests/video_manifest.csv"]),
                           ("video_snapshot_id", references["video_snapshot_id"])):
        same(states2["decode"].get(name), expected, "S2 decode " + name)
    expected_catalogs = {name: references[name] for name in ("s1_catalog_sha256", "video_state_sha256")}
    same(states2["alignment"].get("raw_reference_catalogs"), expected_catalogs, "S2 alignment catalogs")
    for field, logical in (("audit_export_report.json", "data/sector1_audit_export_report.json"),
                           ("physical_image_inventory.csv", "data/physical_image_inventory.csv"),
                           ("metadata_clean.parquet", "data/metadata_clean.parquet"),
                           ("video_manifest.csv", "manifests/video_manifest.csv"),
                           ("video_manifest_state.json", "manifests/video_manifest_state.json")):
        same(states2["alignment"].get("input_sha256", {}).get(field), published2["hashes"][logical],
             "S2 alignment input " + field)
    for field, expected in expected_catalogs.items():
        same(published2["source2"].get("frame_raw_integrity", {}).get(field), expected, "S2 config " + field)
    for name, state_hash in state_hashes2.items():
        same(lineage3.get("state_sha256", {}).get(name), state_hash, "S3 -> S2 " + name + " state")
    same(lineage3.get("state_sha256", {}).get("alignment_attempt"), published2["attempt_sha256"],
         "S3 -> latest S2 attempt")
    same(lineage3.get("sector2_artifact_catalog_sha256"), published2["artifact_catalog_sha256"], "S3 -> S2 export catalog")
    videos, confirmed = raw2["video_manifest"], raw2["df_alignment_confirmed"]
    for field, expected in (("video_count", len(videos)), ("confirmed_annotation_count", len(confirmed))):
        require(type(references.get(field)) is int, f"S3 {field} must be an integer.")
        same(references[field], expected, "S3 " + field)
    # Compare every confirmed reference to the certified inventories, without media I/O.
    images = pd.read_csv(published2["image_inventory_path"], dtype={"image_relpath": "string", "image_sha256": "string"})
    for table, key, label in ((images, "image_relpath", "S1 images"), (videos, "video_key", "S2 videos")):
        require(table[key].notna().all() and table[key].is_unique, f"{label} needs unique identities.")
    image_index, video_index = images.set_index("image_relpath"), videos.set_index("video_key")
    for target, key, index, source in (
        ("source_image_sha256", "image_relpath", image_index, "image_sha256"),
        ("source_image_size_bytes", "image_relpath", image_index, "image_size_bytes"),
        ("video_relpath", "video_key", video_index, "video_relpath"),
        ("source_video_sha256", "video_key", video_index, "video_sha256"),
        ("source_video_size_bytes", "video_key", video_index, "video_size_bytes"),
    ):
        require(confirmed[target].eq(confirmed[key].map(index[source])).fillna(False).all(),
                f"Confirmed {target} differs from the published source inventory.")
    for field in ("image_snapshot_id", "video_snapshot_id"):
        require(confirmed[field].eq(references[field]).fillna(False).all(),
                f"Confirmed {field} differs from its producing snapshot.")
    return copy.deepcopy(references)


S5_SOURCE_RAW_REFERENCE_COLUMNS = (
    "source_image_sha256", "source_image_size_bytes",
    "source_video_sha256", "source_video_size_bytes",
    "image_snapshot_id", "video_snapshot_id",
)


S5_SEGMENT_RAW_REFERENCE_MAP = {
    "target_image_sha256": "source_image_sha256",
    "target_image_size_bytes": "source_image_size_bytes",
    "source_video_sha256": "source_video_sha256",
    "source_video_size_bytes": "source_video_size_bytes",
    "source_video_relpath": "video_relpath",
    "image_snapshot_id": "image_snapshot_id",
    "video_snapshot_id": "video_snapshot_id",
}


def _s5_require_raw_columns(table, columns, name):
    if not isinstance(table, pd.DataFrame) or not table.columns.is_unique:
        raise TypeError(f"{name} must be a DataFrame with unique columns.")
    missing = sorted(set(columns) - set(table.columns))
    if missing:
        raise ValueError(
            f"{name} lacks certified raw references: {missing}. "
            "Rerun and publish Sector 4 from the current certified Sector 3 outputs."
        )


def _s5_validate_raw_values(table, sha_columns, size_columns, path_columns, name):
    for column in sha_columns:
        values = table[column].astype("string")
        if not values.str.fullmatch(r"[0-9a-f]{64}", na=False).all():
            raise ValueError(f"{name}.{column} requires nonempty SHA-256 values.")
    for column in size_columns:
        values = pd.to_numeric(table[column], errors="coerce")
        boolean_values = table[column].map(lambda value: isinstance(value, (bool, np.bool_)))
        if (boolean_values.any() or values.isna().any() or values.le(0).any()
                or values.mod(1).ne(0).any() or not np.isfinite(values.astype("float64")).all()):
            raise ValueError(f"{name}.{column} requires positive integer byte sizes.")
    for column in path_columns:
        for value in table[column]:
            if (not isinstance(value, str) or not value or value != value.strip()
                    or "\\" in value or PurePosixPath(value).is_absolute()
                    or any(part in ("", ".", "..") for part in value.split("/"))):
                raise ValueError(f"{name}.{column} requires canonical relative file paths.")


def validate_segment_raw_references(labelled_manifest):
    """Require consistent identities without equating different JPEG file paths."""
    required = (*S5_SOURCE_RAW_REFERENCE_COLUMNS, "video_key", "image_relpath", "video_relpath")
    _s5_require_raw_columns(labelled_manifest, required, "Sector 5 source")
    _s5_validate_raw_values(
        labelled_manifest,
        ("source_image_sha256", "source_video_sha256", "image_snapshot_id", "video_snapshot_id"),
        ("source_image_size_bytes", "source_video_size_bytes"),
        ("image_relpath", "video_relpath"), "Sector 5 source",
    )
    keys = labelled_manifest["video_key"].astype("string")
    if keys.isna().any() or keys.str.strip().eq("").any():
        raise ValueError("Sector 5 source has a missing video identity.")
    for column in ("image_snapshot_id", "video_snapshot_id"):
        if labelled_manifest[column].nunique(dropna=False) > 1:
            raise ValueError(f"Sector 5 source mixes different {column} references.")
    image_fields = ["source_image_sha256", "source_image_size_bytes", "image_snapshot_id"]
    image_counts = labelled_manifest.groupby("image_relpath", observed=True)[image_fields].nunique(dropna=False)
    if image_counts.gt(1).any(axis=1).any():
        raise ValueError("Annotations of the same source image disagree on its raw reference.")
    video_fields = ["video_relpath", "source_video_sha256", "source_video_size_bytes", "video_snapshot_id"]
    video_counts = labelled_manifest.groupby("video_key", observed=True)[video_fields].nunique(dropna=False)
    if video_counts.gt(1).any(axis=1).any():
        raise ValueError("Annotations of the same source video disagree on its raw reference.")
    if labelled_manifest.groupby("video_relpath", observed=True)["video_key"].nunique(dropna=False).gt(1).any():
        raise ValueError("One source video path is associated with multiple video keys.")


def _s5_validate_target_frame_references(members, targets):
    """One selected physical frame must have one raw image content identity."""
    keys = ["video_key", "opencv_frame_index"]
    selected = targets[keys].drop_duplicates()
    annotations = members.merge(selected, on=keys, how="inner", validate="many_to_one")
    fields = [*S5_SOURCE_RAW_REFERENCE_COLUMNS, "video_relpath"]
    counts = annotations.groupby(keys, observed=True)[fields].nunique(dropna=False)
    if counts.gt(1).any(axis=1).any():
        raise ValueError(
            "Annotations of a representative physical frame disagree on raw image/video references. "
            "Different image paths are allowed only when their SHA-256 and byte size agree."
        )


def validate_segment_manifest_raw_references(segment_manifest, members):
    """Check targets in vectorized tables; check JSON against plain annotation dictionaries."""
    validate_segment_raw_references(members)
    required = (*S5_SEGMENT_RAW_REFERENCE_MAP, "finding_segment_id", "video_key",
                "target_frame_number", "target_opencv_frame_index", "target_image_annotation_id", "target_image_relpath",
                "target_annotations_json", "target_annotation_count")
    _s5_require_raw_columns(segment_manifest, required, "Finding segment manifest")
    _s5_require_raw_columns(members, ("finding_segment_id", "annotation_id", "frame_number", "opencv_frame_index"), "Segment members")
    for column in S5_SEGMENT_RAW_REFERENCE_MAP:
        expected_dtype = "Int64" if column.endswith("_size_bytes") else "string"
        if str(segment_manifest[column].dtype) != expected_dtype:
            raise ValueError(f"Finding segment manifest requires {column} dtype {expected_dtype}.")
    _s5_validate_raw_values(
        segment_manifest,
        ("target_image_sha256", "source_video_sha256", "image_snapshot_id", "video_snapshot_id"),
        ("target_image_size_bytes", "source_video_size_bytes"),
        ("target_image_relpath", "source_video_relpath"), "Finding segment manifest",
    )
    if not segment_manifest["finding_segment_id"].is_unique:
        raise ValueError("Finding segment manifest contains duplicate segment IDs.")
    if set(segment_manifest["finding_segment_id"]) != set(members["finding_segment_id"]):
        raise ValueError("Segment raw-reference validation found inconsistent segment membership.")
    _s5_validate_target_frame_references(members, segment_manifest.rename(
        columns={"target_opencv_frame_index": "opencv_frame_index"}))

    # Match all target annotations once; avoid 22,000+ pandas group/sort/index operations.
    target_keys = segment_manifest[["finding_segment_id", "target_frame_number"]].rename(
        columns={"target_frame_number": "frame_number"})
    target = members.merge(target_keys, on=["finding_segment_id", "frame_number"],
                           how="inner", sort=False, validate="many_to_one")
    if set(target["finding_segment_id"]) != set(segment_manifest["finding_segment_id"]):
        raise ValueError("A segment target has no corresponding source annotation.")
    target = target.sort_values(["finding_segment_id", "annotation_id"], kind="stable")
    selected = segment_manifest.set_index("finding_segment_id")
    first = target.drop_duplicates("finding_segment_id").set_index("finding_segment_id").reindex(selected.index)
    identity_map = {
        "target_image_annotation_id": "annotation_id",
        "target_image_relpath": "image_relpath",
        "target_opencv_frame_index": "opencv_frame_index",
        "video_key": "video_key",
    }
    for target_column, source_column in identity_map.items():
        if not selected[target_column].eq(first[source_column]).fillna(False).all():
            raise ValueError("Segment target differs from its deterministic source annotation.")
    for target_column, source_column in S5_SEGMENT_RAW_REFERENCE_MAP.items():
        if not selected[target_column].eq(first[source_column]).fillna(False).all():
            raise ValueError(f"Segment target raw reference mismatch: {target_column}.")
    target_counts = target.groupby("finding_segment_id", sort=False, observed=True).size().reindex(selected.index)
    if not selected["target_annotation_count"].eq(target_counts).fillna(False).all():
        raise ValueError("Target annotation reference collection has incorrect coverage.")

    annotation_fields = ("image_relpath", "video_relpath", *S5_SOURCE_RAW_REFERENCE_COLUMNS)
    expected_records = {}
    expected_ids = {}
    # All these objects are Python scalars/dictionaries; no pandas access in the JSON loop.
    for record in target[["finding_segment_id", "annotation_id", *annotation_fields]].to_dict(orient="records"):
        annotation_id = record["annotation_id"]
        if annotation_id in expected_records:
            raise ValueError("Target annotation reference collection lost or duplicated annotations.")
        expected_records[annotation_id] = record
        expected_ids.setdefault(record["finding_segment_id"], set()).add(annotation_id)
    for segment_id, encoded in segment_manifest[["finding_segment_id", "target_annotations_json"]].itertuples(
            index=False, name=None):
        try:
            records = json.loads(encoded)
        except (ValueError, TypeError) as error:
            raise ValueError("Target annotation references are not valid JSON.") from error
        ids = expected_ids[segment_id]
        if (not isinstance(records, list) or any(not isinstance(row, dict) for row in records)
                or len(records) != len(ids)):
            raise ValueError("Target annotation reference collection has incorrect coverage.")
        recorded_ids = [row.get("annotation_id") for row in records]
        if (len(set(recorded_ids)) != len(recorded_ids) or set(recorded_ids) != ids):
            raise ValueError("Target annotation reference collection lost or duplicated annotations.")
        for record in records:
            expected = expected_records[record["annotation_id"]]
            for column in annotation_fields:
                if record.get(column) != expected[column]:
                    raise ValueError(f"Target annotation raw reference mismatch: {column}.")


def io_s5_git(repo, *arguments):
    """Run Git without shell expansion, prompts or credential tracing."""
    environment = {key: value for key, value in os.environ.items()
                   if not key.startswith("GIT_TRACE") and key != "GIT_CURL_VERBOSE"}
    environment["GIT_TERMINAL_PROMPT"] = "0"
    process = subprocess.run(["git", *(["-C", str(repo)] if repo is not None else []), *arguments],
                             env=environment, capture_output=True)
    if process.returncode:
        raise RuntimeError("Cannot load published main inputs: "
                           + process.stderr.decode("utf-8", errors="replace").strip())
    return process.stdout


def io_s5_fetch_main(repo_url, repo):
    """Fetch fresh main and pin it once; no local checkout can supply input data."""
    io_s5_git(None, "clone", "--quiet", "--bare", "--filter=blob:none", "--depth=1",
              "--single-branch", "--branch=main", "--", repo_url, str(repo))
    commit = io_s5_git(repo, "rev-parse", "refs/heads/main^{commit}").decode().strip()
    if re.fullmatch(r"[0-9a-f]{40}", commit) is None:
        raise RuntimeError("Published main did not resolve to a full commit SHA.")
    return commit


def _s5_git_relative(value):
    if (not isinstance(value, str) or not value or "\\" in value or "\x00" in value
            or PurePosixPath(value).is_absolute()
            or any(part in {"", ".", ".."} for part in value.split("/"))):
        raise ValueError(f"Unsafe published metadata path: {value!r}")
    return value


def io_s5_stage_catalog(repo, commit, stage_root, sector):
    """Materialize only catalog-declared blobs, then reuse the existing typed reader."""
    prefix = f"outputs/phase2/sector{sector}"
    relative_state = f"configs/sector{sector}_state.json"
    payload = io_s5_git_blob(repo, commit, f"{prefix}/{relative_state}")
    state = json.loads(payload)
    if (not isinstance(state, dict) or state.get("schema_version") != 2
            or state.get("complete") is not True
            or state.get("content_id") != _p3_json_hash(_p3_catalog_meaning(state))):
        raise RuntimeError(f"Publish a complete, current Sector {sector} catalog to main first.")
    records = state["artifacts"]
    paths = [_p3_relative(_s5_git_relative(item["relative_path"])) for item in records]
    if len(paths) != len(set(paths)) or {relative_state, f"configs/sector{sector}_publication_receipt.json"}.intersection(paths):
        raise RuntimeError(f"Sector {sector} catalog contains duplicate or operational entries.")
    root = stage_root / prefix
    target = root / relative_state
    target.parent.mkdir(parents=True, exist_ok=True)
    _s6_install_metadata(target, payload)
    for relative, record in zip(paths, records):
        payload = io_s5_git_blob(repo, commit, f"{prefix}/{relative}")
        if len(payload) != record["bytes"] or hashlib.sha256(payload).hexdigest() != record["sha256"]:
            raise RuntimeError(f"Published Sector {sector} checksum failed: {relative}")
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        _s6_install_metadata(target, payload)
    return io_s5_read_catalog(root, sector)


def sector5_published_source_identity(lineage):
    """Bind source authority and evidence without invalidation by unrelated main commits."""
    source = lineage.get("published_source", {})
    if (source.get("source_branch") != "main"
            or source.get("input_source") != "published_git_objects_only"
            or re.fullmatch(r"[0-9a-f]{40}", str(source.get("source_commit", ""))) is None):
        raise ValueError("Load the verified published main chain before computing Sector 5.")
    return {key: value for key, value in source.items() if key != "source_commit"}


S5_SECTOR3_INPUTS = (
    "labelled_frame_manifest", "video_frame_manifest",
    "video_class_matrix", "video_class_support",
)


S5_SECTOR4_RESULTS = (
    "labelled_frame_manifest_with_split",
    "video_split_manifest",
    "frame_split_manifest",
)


S5_REQUIRED_LABELLED_COLUMNS = {
    "annotation_id", "annotation_status", "alignment_training_eligible",
    "video_key", "finding_class", "finding_class_normalized",
    "clinical_group", "frame_number", "opencv_frame_index", "frame_index_offset",
    "filename", "image_path", "image_relpath", "has_bbox", "bbox_spatially_usable",
    "bbox_validation_status", "bbox_xmin", "bbox_ymin", "bbox_xmax", "bbox_ymax", "split",
}


def _s5_json(path):
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"Expected a JSON object: {path}")
    return value


def _s5_checked_hash(path, expected):
    if not isinstance(expected, str) or re.fullmatch(r"[0-9a-f]{64}", expected) is None:
        raise ValueError(f"Missing or invalid committed SHA-256: {path}")
    actual = _p3_file_hash(path)
    if actual != expected:
        raise RuntimeError(f"Artifact changed after its completed audit: {path}")
    return actual


def io_s5_read_catalog(root, sector):
    """Read one current Sector 3/4 catalog, never choose a config by timestamp."""
    root = Path(root).resolve()
    state_path = _p3_safe_path(root, f"configs/sector{sector}_state.json")
    if not state_path.is_file():
        raise FileNotFoundError(f"Run/save Sector {sector} first; current catalog missing: {state_path}")
    state_hash = _p3_file_hash(state_path)
    state = _s5_json(state_path)
    if state.get("schema_version") != 2 or state.get("complete") is not True:
        raise RuntimeError(f"Sector {sector} catalog is incomplete or has an unsupported schema.")
    if state.get("content_id") != _p3_json_hash(_p3_catalog_meaning(state)):
        raise RuntimeError(f"Sector {sector} catalog content fingerprint is invalid.")
    records = {item["relative_path"]: item for item in state["artifacts"]}
    operational = {f"configs/sector{sector}_state.json", f"configs/sector{sector}_publication_receipt.json"}
    if len(records) != len(state["artifacts"]) or set(records) & operational:
        raise RuntimeError(f"Sector {sector} catalog has duplicate or operational artifact entries.")
    for relative, record in records.items():
        path = _p3_safe_path(root, relative)
        if not path.is_file() or path.stat().st_size != record["bytes"]:
            raise RuntimeError(f"Sector {sector} cataloged file missing or size changed: {relative}")
        _s5_checked_hash(path, record["sha256"])
    if state["config_snapshot"] not in records:
        raise RuntimeError(f"Sector {sector} current config snapshot is absent from its catalog.")
    snapshot_path = _p3_safe_path(root, state["config_snapshot"])
    envelope = _s5_json(snapshot_path)
    semantic = sector3_semantic_config_fingerprint if sector == 3 else sector4_semantic_config_fingerprint
    if (envelope.get("semantic_config_fingerprint") != state["semantic_config_fingerprint"]
            or semantic(envelope["effective_config"]) != state["semantic_config_fingerprint"]):
        raise RuntimeError(f"Sector {sector} effective config disagrees with its catalog.")
    for name, descriptor in state["tables"].items():
        if not {descriptor["relative_path"], descriptor["schema_path"]}.issubset(records):
            raise RuntimeError(f"Sector {sector} table/schema absent from catalog: {name}")
        schema = _s5_json(_p3_safe_path(root, descriptor["schema_path"]))
        if schema.get("artifact") != descriptor["relative_path"] or schema.get("fingerprint") != descriptor["fingerprint"]:
            raise RuntimeError(f"Sector {sector} table schema disagrees with its catalog: {name}")
    summary = state["summary"]
    if not {summary["summary_relative_path"], summary["report_relative_path"]}.issubset(records):
        raise RuntimeError(f"Sector {sector} summary/report absent from catalog.")
    if (_p3_json_hash(_s5_json(_p3_safe_path(root, summary["summary_relative_path"]))) != summary["fingerprint"]
            or records[summary["report_relative_path"]]["sha256"] != summary["report_fingerprint"]):
        raise RuntimeError(f"Sector {sector} summary/report disagrees with its catalog.")
    for relative in state.get("obsolete_paths", []):
        if not _p3_relative(relative).startswith("results/") or relative in records:
            raise RuntimeError(f"Sector {sector} catalog has an invalid obsolete-result entry.")
    return {"root": root, "state": state, "envelope": envelope, "config": envelope["effective_config"],
            "state_path": state_path, "state_sha256": state_hash,
            "snapshot_path": snapshot_path, "snapshot_sha256": _p3_file_hash(snapshot_path)}


def _s5_required_tables(context, names):
    missing = sorted(set(names) - set(context["state"]["tables"]))
    if missing:
        raise KeyError(f"Current catalog at {context['root']} lacks required tables: {missing}")
    return {name: _p3_read_table(context["root"], context["state"]["tables"][name]) for name in names}


def _s5_identity_multiset(table, columns):
    values = table[columns].astype("string")
    for column in columns:
        if column in {"frame_number", "opencv_frame_index", "aligned_frame_index"} or column.startswith("bbox_"):
            values[column] = pd.to_numeric(table[column], errors="coerce").astype("Float64").astype("string")
    return values.fillna("").value_counts(sort=False).sort_index()


def _s5_validate_frame_splits(labelled, split_manifest, frame_split_manifest):
    """Validate authoritative physical-frame assignments and video/split memberships."""
    frame_keys = ["video_key", "opencv_frame_index"]
    pair_keys = ["video_key", "split"]
    allowed = ["train", "validation", "test"]
    for name, table, keys in (
        ("labelled annotations", labelled, frame_keys),
        ("frame_split_manifest", frame_split_manifest, frame_keys),
        ("video_split_manifest", split_manifest, pair_keys),
    ):
        missing = sorted(set(keys + ["split"]) - set(table.columns))
        if missing:
            raise KeyError(f"Sector 4 {name} lacks split fields: {missing}")
        for column in keys + ["split"]:
            values = table[column].astype("string")
            if (values.isna() | values.str.strip().eq("")).any():
                raise ValueError(f"Sector 4 {name} has null/empty {column} values.")
        if not table["split"].isin(allowed).all():
            raise ValueError(f"Sector 4 {name} contains unsupported split names.")
    if frame_split_manifest.duplicated(frame_keys).any():
        raise ValueError("Sector 4 frame_split_manifest requires one row per video/decoded-frame key.")
    if split_manifest.duplicated(pair_keys).any():
        raise ValueError("Sector 4 video_split_manifest requires unique (video_key, split) pairs.")
    indices = frame_split_manifest["opencv_frame_index"]
    numeric = pd.to_numeric(indices, errors="coerce")
    if (numeric.isna() | numeric.lt(0) | numeric.mod(1).ne(0)).any() or (
        not np.isfinite(numeric.astype("float64")).all()
        or indices.map(lambda value: isinstance(value, (bool, np.bool_))).any()
    ):
        raise ValueError("Sector 4 frame_split_manifest requires finite non-negative integer decoded-frame indices.")
    frame_assignments = labelled[frame_keys + ["split"]].drop_duplicates()
    if frame_assignments.duplicated(frame_keys).any():
        raise ValueError("All annotations/classes on one physical frame must share the same split.")
    reference = frame_split_manifest[frame_keys + ["split"]].copy()
    reference["opencv_frame_index"] = numeric.astype("Int64")
    comparison = frame_assignments.merge(
        reference, on=frame_keys, how="outer", validate="one_to_one",
        suffixes=("_annotation", "_manifest"), indicator=True,
    )
    if not comparison["_merge"].eq("both").all() or not comparison[
        "split_annotation"
    ].eq(comparison["split_manifest"]).fillna(False).all():
        raise ValueError("Accepted annotations disagree with the authoritative Sector 4 frame split manifest (frame coverage or split assignment).")
    membership = frame_assignments[pair_keys].drop_duplicates().merge(
        split_manifest[pair_keys], on=pair_keys, how="outer",
        validate="one_to_one", indicator=True,
    )
    if not membership["_merge"].eq("both").all():
        raise ValueError("Sector 4 video/split memberships disagree with the accepted frame assignments.")
    expected_counts = labelled.groupby(pair_keys, observed=True, sort=True).agg(
        retained_annotation_count=("annotation_id", "size"),
        retained_unique_frame_count=("opencv_frame_index", "nunique"),
        retained_class_count=("finding_class_normalized", "nunique"),
    )
    saved_counts = split_manifest.set_index(pair_keys).reindex(expected_counts.index)
    for column in expected_counts:
        if column in saved_counts and not pd.to_numeric(
            saved_counts[column], errors="coerce"
        ).eq(expected_counts[column]).fillna(False).all():
            raise ValueError(f"Sector 4 video/split summary has inconsistent {column} values.")


def _s5_validate_loaded_frames(labelled, sector3_labelled, videos, split_manifest, confirmed, frame_split_manifest):
    validate_segment_raw_references(labelled)
    validate_segment_raw_references(sector3_labelled)
    validate_segment_raw_references(confirmed)
    missing = sorted(S5_REQUIRED_LABELLED_COLUMNS - set(labelled))
    if missing:
        raise KeyError(f"Sector 4 labelled-frame artifact lacks Sector 5 input fields: {missing}")
    if labelled.empty:
        raise ValueError("Sector 5 requires at least one accepted labelled annotation.")
    for column in ("annotation_id", "video_key", "finding_class_normalized", "clinical_group", "split"):
        values = labelled[column].astype("string")
        if (values.isna() | values.str.strip().eq("")).any():
            raise ValueError(f"Sector 5 input has missing/empty {column} values.")
    if not labelled["annotation_id"].is_unique:
        raise ValueError("Sector 4 must preserve unique source annotation_id values.")
    for column in ("frame_number", "opencv_frame_index", "frame_index_offset"):
        values = pd.to_numeric(labelled[column], errors="coerce")
        invalid = values.isna() | ~np.isfinite(values.astype("float64")) | values.mod(1).ne(0)
        if column != "frame_index_offset":
            invalid = invalid | values.lt(0)
        if invalid.any() or labelled[column].map(lambda value: isinstance(value, (bool, np.bool_))).any():
            raise ValueError(f"Sector 5 input requires genuine finite integer {column} values.")
        labelled[column] = values.astype("Int64")
    if not labelled["opencv_frame_index"].eq(labelled["frame_number"] + labelled["frame_index_offset"]).all():
        raise ValueError("Accepted decoded indices disagree with source frame numbers plus verified offsets.")
    if labelled.groupby("video_key", observed=True)["frame_index_offset"].nunique().gt(1).any():
        raise ValueError("Accepted annotations have inconsistent verified offsets within a video.")
    if not labelled["annotation_status"].eq("source_expert_annotation_alignment_confirmed").all():
        raise ValueError("Sector 5 can consume only expert annotations with confirmed alignment.")
    if not labelled["alignment_training_eligible"].eq(True).all():
        raise ValueError("Sector 5 input includes annotations rejected by alignment.")
    if videos["video_key"].isna().any() or not videos["video_key"].is_unique:
        raise ValueError("The completed decoded video inventory needs unique non-null video keys.")
    bounds = labelled["video_key"].map(videos.set_index("video_key")["frame_count"])
    if bounds.isna().any() or not labelled["opencv_frame_index"].lt(bounds).all():
        raise ValueError("Accepted decoded frame indices lie outside audited video bounds.")
    if not videos["frame_count_source"].eq("completed_sector2_decode_audit").all():
        raise ValueError("Video bounds must come from completed Sector 2 decoding.")
    _s5_validate_frame_splits(labelled, split_manifest, frame_split_manifest)
    # Preserve every expert bbox row. Compare annotation identities and multiplicities,
    # and never turn duplicate frame/class rows into new labels or discard them here.
    identity_columns = [column for column in (
        "annotation_id", "filename", "image_key", "video_key", "frame_number",
        "opencv_frame_index", "finding_class_normalized", "bbox_xmin", "bbox_ymin", "bbox_xmax", "bbox_ymax",
        "image_relpath", "video_relpath", "source_image_sha256", "source_image_size_bytes",
        "source_video_sha256", "source_video_size_bytes", "image_snapshot_id", "video_snapshot_id",
    ) if column in sector3_labelled]
    if not _s5_identity_multiset(labelled, identity_columns).equals(_s5_identity_multiset(sector3_labelled, identity_columns)):
        raise ValueError("Sector 4 labelled annotations differ from the current Sector 3 evidence.")
    source_columns = [column for column in (
        "filename", "image_key", "video_key", "frame_number", "finding_class_normalized",
        "bbox_xmin", "bbox_ymin", "bbox_xmax", "bbox_ymax",
        "image_relpath", "video_relpath", "source_image_sha256", "source_image_size_bytes",
        "source_video_sha256", "source_video_size_bytes", "image_snapshot_id", "video_snapshot_id",
    ) if column in confirmed and column in sector3_labelled]
    if not _s5_identity_multiset(confirmed, source_columns).equals(_s5_identity_multiset(sector3_labelled, source_columns)):
        raise ValueError("Sector 3 accepted annotations do not preserve current Sector 2 confirmed evidence.")


def _s5_rebase_live_paths(table, storage_root):
    result = table.copy()
    for path_column, relative_column in (("image_path", "image_relpath"), ("video_path", "video_relpath")):
        if path_column not in result or relative_column not in result:
            continue
        paths = []
        for value in result[relative_column]:
            if pd.isna(value):
                paths.append(pd.NA)
                continue
            relative = PurePosixPath(str(value))
            if relative.is_absolute() or "\\" in str(value) or any(part in {"", ".", ".."} for part in str(value).split("/")):
                raise ValueError(f"Unsafe portable path in {relative_column}: {value!r}")
            paths.append(str(storage_root.joinpath(*relative.parts)))
        result[path_column] = pd.Series(paths, index=result.index).astype(result[path_column].dtype)
    return result


def io_load_sector5_context(bootstrap, settings):
    """Read/verify the current 2 -> 3 -> 4 chain; return config, inputs and lineage."""
    if not isinstance(bootstrap, dict) or not isinstance(settings, dict):
        raise TypeError("BOOTSTRAP and SECTOR5_SETTINGS must be dictionaries.")
    allowed_settings = set(SECTOR5_DEFAULTS) | {"local_output_dir", "export_dir", "push", "dry_run", "github_overrides"}
    unknown = sorted(set(settings) - allowed_settings)
    if unknown:
        raise KeyError(f"Unexpected Sector 5 algorithm settings: {unknown}")
    storage_root = Path(bootstrap["storage_root"]).expanduser().resolve()
    published = io_s5_load_published_chain(bootstrap)
    context3, context4 = published["context3"], published["context4"]
    root3, source4 = context3["root"], context4["config"]
    inputs3 = _s5_required_tables(context3, S5_SECTOR3_INPUTS)
    inputs4 = _s5_required_tables(context4, S5_SECTOR4_RESULTS)
    published2 = published["sector2"]
    source2, source2_path = published2["source2"], published2["source2_path"]
    dirs2 = published2["dirs2"]
    state_paths2 = published2["state_paths2"]
    states2, state_hashes2 = published2["states2"], published2["state_hashes2"]
    run_id = states2["alignment"].get("run_id")
    threshold_keys = {"min_ssim": "frame_alignment_min_ssim", "min_margin": "frame_alignment_min_margin",
                      "candidate_offsets": "frame_index_offset_candidates"}
    if any(states2["alignment"].get("effective_settings", {}).get(recorded) != source2.get(key)
           for recorded, key in threshold_keys.items()):
        raise ValueError("Sector 2 config snapshot disagrees with the completed alignment decision settings.")
    hashes2 = {}
    for family, required in (("alignment", {"frame_alignment_confirmed.parquet", "frame_alignment_excluded.csv"}),
                             ("decode", {"decode_audit.csv"})):
        committed = states2[family].get("output_sha256", {})
        if not required.issubset(committed):
            raise ValueError(f"Sector 2 {family} state lacks required committed output hashes.")
        for filename, digest in committed.items():
            if Path(filename).name != filename or "/" in filename or "\\" in filename:
                raise ValueError("Sector 2 state must list simple committed output filenames.")
            hashes2[filename] = _s5_checked_hash(dirs2["results"] / filename, digest)
    hashes2["video_manifest.csv"] = _s5_checked_hash(dirs2["manifests"] / "video_manifest.csv", states2["manifest"].get("csv_sha256"))
    prior2 = context3["state"]["input_sha256"]
    for filename in ("frame_alignment_confirmed.parquet", "decode_audit.csv", "video_manifest.csv"):
        recorded = {digest for path, digest in prior2.items() if PurePosixPath(str(path)).name == filename}
        if recorded != {hashes2[filename]}:
            raise RuntimeError(f"Current Sector 3 was not built from current Sector 2 {filename}; rerun/save/publish Sector 3 then Sector 4.")
    for name in S5_SECTOR3_INPUTS:
        descriptor = context3["state"]["tables"][name]
        for field in ("relative_path", "schema_path"):
            actual = _p3_file_hash(_p3_safe_path(root3.resolve(), descriptor[field]))
            if context4["state"]["input_sha256"].get(f"{name}/{field}") != actual:
                raise RuntimeError(f"Current Sector 4 was not built from current Sector 3 {name}/{field}; rerun/save/publish Sector 4.")
    raw2 = {"df_alignment_confirmed": pd.read_parquet(dirs2["results"] / "frame_alignment_confirmed.parquet"),
            "frame_alignment_excluded": pd.read_csv(dirs2["results"] / "frame_alignment_excluded.csv", dtype="string"),
            "decode_audit": pd.read_csv(dirs2["results"] / "decode_audit.csv", dtype={"video_key": "string"}),
            "video_manifest": pd.read_csv(dirs2["manifests"] / "video_manifest.csv", dtype={"video_key": "string"})}
    if (len(raw2["df_alignment_confirmed"]) != states2["alignment"].get("confirmed_annotation_rows")
            or len(raw2["frame_alignment_excluded"]) != states2["alignment"].get("excluded_annotation_rows")
            or len(raw2["df_alignment_confirmed"]) + len(raw2["frame_alignment_excluded"]) != states2["alignment"].get("original_annotation_rows")):
        raise ValueError("Sector 2 confirmed/excluded annotation counts disagree with its completed alignment state.")
    if states2["decode"].get("all_videos_decoded") is not True:
        raise ValueError("Every Sector 2 source video must finish decoding before Sector 5.")
    for name, family in (("video_manifest", "manifest"), ("decode_audit", "decode")):
        table = raw2[name]
        if (len(table) != states2[family].get("video_count") or table["video_key"].isna().any()
                or not table["video_key"].is_unique):
            raise ValueError(f"Sector 2 {name} identities/counts disagree with its completed state.")
    if set(raw2["video_manifest"]["video_key"]) != set(raw2["decode_audit"]["video_key"]):
        raise ValueError("Sector 2 video inventory and decode audit contain different video keys.")
    # S2 records certified alignment paths; normalize against its own producer root.
    confirmed = raw2["df_alignment_confirmed"]
    for relative_column, absolute_column in (("image_relpath", "alignment_image_path"),
                                             ("video_relpath", "alignment_video_path")):
        relative_values = confirmed[absolute_column].map(
            lambda value: _s5_git_relative(PurePosixPath(str(value)).relative_to(
                PurePosixPath(source2["storage_root"])).as_posix())).astype("string")
        if relative_column in confirmed and not confirmed[relative_column].eq(relative_values).fillna(False).all():
            raise ValueError(f"S2 alignment path contradicts {relative_column}.")
        confirmed[relative_column] = relative_values
    raw_references = _s5_validate_reference_chain(
        context3, context4, states2, state_hashes2, raw2, published2)
    labelled = inputs4["labelled_frame_manifest_with_split"].copy()
    _s5_validate_loaded_frames(labelled, inputs3["labelled_frame_manifest"], inputs3["video_frame_manifest"],
                              inputs4["video_split_manifest"], raw2["df_alignment_confirmed"],
                              inputs4["frame_split_manifest"])
    config = copy.deepcopy(source4)
    decisions = []
    for key, fallback in SECTOR5_DEFAULTS.items():
        override = settings.get(key)
        value = override if override is not None else source4.get(key, fallback)
        minimum = 1 if key == "segment_max_gap_frames" else 2
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)) or value < minimum:
            raise ValueError(f"{key} must be an integer >= {minimum}.")
        config[key] = int(value)
        decisions.append({"config_key": key, "effective_value": int(value),
                          "resolution": "sector5_override" if override is not None else "inherited_sector4" if key in source4 else "declared_sector5_default"})
    sector5_settings = copy.deepcopy(settings)
    sector5_settings.setdefault("local_output_dir", "outputs/phase2/sector5")
    sector5_settings.setdefault("export_dir", "outputs/phase2/sector5")
    if sector5_settings["export_dir"] != "outputs/phase2/sector5":
        raise ValueError("Sector 5 export_dir must be outputs/phase2/sector5.")
    for flag in ("push", "dry_run"):
        if flag in settings and not isinstance(settings[flag], bool):
            raise ValueError(f"SECTOR5_SETTINGS[{flag!r}] must be a boolean.")
    github = copy.deepcopy(source4.get("github", {}))
    github_overrides = copy.deepcopy(settings.get("github_overrides", {}))
    if not isinstance(github_overrides, dict) or set(github_overrides) - {"token_secret_name"}:
        raise ValueError("Sector 5 github_overrides supports only token_secret_name; repository and branch are inherited.")
    if "token_secret_name" in github_overrides:
        name = github_overrides["token_secret_name"]
        if not isinstance(name, str) or not name.strip() or re.search(r"\s", name):
            raise ValueError("token_secret_name must be a nonempty secret reference without whitespace.")
    github.update(github_overrides)
    github.update({"repo_output_dir": sector5_settings["export_dir"],
                   "push": settings.get("push", github.get("push", False)),
                   "dry_run": settings.get("dry_run", github.get("dry_run", False)),
                   "commit_message": "Phase 2 Sector 5: publish finding segments and temporal supervision"})
    github.pop("confirm_push", None)
    config.update({"phase": 2, "sector": 5, "storage_root": str(storage_root),
                   "sector5": sector5_settings, "github": github})
    for key in S4_EXECUTION_METADATA_KEYS:
        config.pop(key, None)
    # Copies used for access are rebased only after validating the saved bytes and identities.
    runtime3 = {name: _s5_rebase_live_paths(table, storage_root) for name, table in inputs3.items()}
    runtime4 = {name: _s5_rebase_live_paths(table, storage_root) for name, table in inputs4.items()}
    runtime4["labelled_frame_manifest_with_split"] = _s5_rebase_live_paths(labelled, storage_root)
    inputs = {"sector2": raw2, "sector3": runtime3, "sector4": runtime4}
    consumed = {f"sector2/{name}": digest for name, digest in hashes2.items()}
    consumed_paths = {f"sector2/{name}": str((dirs2["manifests"] if name == "video_manifest.csv" else dirs2["results"]) / name)
                      for name in hashes2}
    for name, path in state_paths2.items():
        consumed[f"sector2/state/{name}"] = state_hashes2[name]
        consumed_paths[f"sector2/state/{name}"] = str(path)
    if source2_path is not None:
        consumed["sector2/config_snapshot"] = _p3_file_hash(source2_path)
        consumed_paths["sector2/config_snapshot"] = str(source2_path)
    for sector, context, names in ((3, context3, S5_SECTOR3_INPUTS), (4, context4, S5_SECTOR4_RESULTS)):
        for name in names:
            for field in ("relative_path", "schema_path"):
                relative = context["state"]["tables"][name][field]
                consumed[f"sector{sector}/{name}/{field}"] = _p3_file_hash(_p3_safe_path(context["root"], relative))
                consumed_paths[f"sector{sector}/{name}/{field}"] = str(_p3_safe_path(context["root"], relative))
        consumed[f"sector{sector}/state"] = context["state_sha256"]
        consumed_paths[f"sector{sector}/state"] = str(context["state_path"])
        consumed[f"sector{sector}/config_snapshot"] = context["snapshot_sha256"]
        consumed_paths[f"sector{sector}/config_snapshot"] = str(context["snapshot_path"])
    lineage = {"input_sha256": consumed, "input_descriptors": consumed_paths, "sector2_run_id": run_id,
               "sector2_states": states2, "sector2_state_sha256": state_hashes2,
               "sector2_config_snapshot": str(source2_path) if source2_path else None,
               "sector2_config_snapshot_sha256": _p3_file_hash(source2_path) if source2_path else None,
               "upstream": {f"sector{sector}": {"root": str(context["root"]), "content_id": context["state"]["content_id"],
                   "state_sha256": context["state_sha256"], "config_snapshot": str(context["snapshot_path"]),
                   "config_snapshot_sha256": context["snapshot_sha256"]} for sector, context in ((3, context3), (4, context4))},
               "config_inheritance_report": pd.DataFrame.from_records(decisions),
               "config_inheritance_policy": "Published main S2/S3/S4 at one pinned commit; inherit S4 effective config with explicit S5 overrides."}
    for context in (context3, context4):
        _s5_checked_hash(context["state_path"], context["state_sha256"])
    for name, path in state_paths2.items():
        _s5_checked_hash(path, state_hashes2[name])
    for filename, expected in hashes2.items():
        parent = dirs2["manifests"] if filename == "video_manifest.csv" else dirs2["results"]
        _s5_checked_hash(parent / filename, expected)

    lineage["source_table_fingerprint"] = sector3_table_fingerprint(
        runtime4["labelled_frame_manifest_with_split"]
    )

    lineage["raw_references"] = raw_references
    lineage["published_source"] = {
        **published["provenance"],
        "sector2_artifact_catalog_sha256": published2["artifact_catalog_sha256"],
        "s1_catalog_sha256": raw_references["s1_catalog_sha256"],
        "alignment_attempt_sha256": published2["attempt_sha256"],
    }
    lineage["published_inputs"] = {}
    for key, path in consumed_paths.items():
        relative = Path(path).relative_to(published["stage_root"]).as_posix()
        if relative.startswith("outputs/phase2/sector2/"):
            logical = relative.removeprefix("outputs/phase2/sector2/")
            evidence = copy.deepcopy(published2["evidence"][logical])
        else:
            evidence = {"repository_path": relative, "encoding": "identity",
                        "export_sha256": consumed[key], "source_sha256": consumed[key]}
        lineage["published_inputs"][key] = evidence
    # Keep this private workspace alive for the existing pre-save checksum gate.
    # Only config/lineage/tables are persisted, never this operational handle.
    return {"config": config, "inputs": inputs, "lineage": lineage,
            "_source_workspace": published["workspace"]}


S6_SECTOR5_REQUIRED_TABLES = (
    "finding_segment_manifest", "labelled_frame_manifest_with_segments",
)


def _s6_portable_path(value, storage_root, field):
    """Rebase a declared portable path without touching the filesystem."""
    if value is None or value is pd.NA or pd.isna(value):
        return pd.NA
    text = str(value)
    relative = PurePosixPath(text)
    if (not text or relative.is_absolute() or "\\" in text
            or any(part in {"", ".", ".."} for part in text.split("/"))):
        raise ValueError(f"Unsafe storage-relative path in {field}: {value!r}")
    return str(Path(storage_root).joinpath(*relative.parts))


def _s6_rebase_live_paths(table, storage_root):
    """Return a copy with live paths rebuilt only from committed relpaths."""
    result = _s5_rebase_live_paths(table, storage_root)
    for path_column, relative_column in (
        ("target_image_path", "target_image_relpath"),
        ("context_image_path", "context_image_relpath"),
    ):
        if path_column in result and relative_column in result:
            paths = result[relative_column].map(
                lambda value: _s6_portable_path(value, storage_root, relative_column))
            result[path_column] = paths.astype(result[path_column].dtype)
    if "target_annotations_json" in result:
        def rebase_annotations(value):
            if pd.isna(value):
                return pd.NA
            annotations = json.loads(str(value))
            if not isinstance(annotations, list) or any(not isinstance(item, dict) for item in annotations):
                raise ValueError("Sector 5 target_annotations_json must contain an annotation list.")
            for annotation in annotations:
                if "image_path" in annotation:
                    if "image_relpath" not in annotation:
                        raise KeyError("A saved target annotation lacks its portable image_relpath.")
                    path = _s6_portable_path(annotation["image_relpath"], storage_root, "target_annotations_json/image_relpath")
                    annotation["image_path"] = None if pd.isna(path) else path
            return json.dumps(annotations, ensure_ascii=False, allow_nan=False, separators=(",", ":"))
        result["target_annotations_json"] = result["target_annotations_json"].map(rebase_annotations).astype("string")
    return result


def _s6_validate_sector5_tables(inputs5, current4, video_frames):
    """Preserve all source expert annotations and current physical-frame split assignments."""
    labelled = inputs5["labelled_frame_manifest_with_segments"]
    segments = inputs5["finding_segment_manifest"]
    required_labelled = set(current4.columns) | {"finding_segment_id"}
    missing = sorted(required_labelled - set(labelled.columns))
    if missing:
        raise KeyError(f"Sector 5 member manifest lacks preserved Sector 4 fields: {missing}")
    if (labelled["annotation_id"].isna().any() or not labelled["annotation_id"].is_unique
            or set(labelled["annotation_id"]) != set(current4["annotation_id"])):
        raise ValueError("Sector 5 annotation IDs do not preserve the current accepted Sector 4 evidence.")
    left = labelled.loc[:, current4.columns].sort_values("annotation_id", kind="stable").reset_index(drop=True)
    right = current4.sort_values("annotation_id", kind="stable").reset_index(drop=True)
    try:
        pd.testing.assert_frame_equal(left, right, check_dtype=False, check_categorical=False)
    except AssertionError as error:
        raise ValueError("Sector 5 changed accepted source annotations, bounding boxes or Sector 4 splits.") from error
    required_segments = {
        "finding_segment_id", "video_key", "finding_class", "finding_class_normalized", "clinical_group", "split",
        "verified_start_frame", "verified_end_frame", "verified_frame_count", "verified_annotation_count",
        "target_frame_number", "target_opencv_frame_index", "target_image_path", "target_image_relpath",
        "target_image_annotation_id", "target_annotation_ids_json", "target_annotations_json",
        "target_annotation_count", "temporal_grounding_candidate", "verified_temporal_boundary_available", "temporal_supervision_level",
    }
    missing = sorted(required_segments - set(segments.columns))
    if missing:
        raise KeyError(f"Sector 5 segment manifest lacks Sector 6 fields: {missing}")
    if segments["finding_segment_id"].isna().any() or not segments["finding_segment_id"].is_unique:
        raise ValueError("Sector 5 segment IDs must be unique and non-null.")
    if labelled["finding_segment_id"].isna().any() or set(labelled["finding_segment_id"]) != set(segments["finding_segment_id"]):
        raise ValueError("Sector 5 segment identities disagree with annotation memberships.")
    if not segments["temporal_grounding_candidate"].isin([True, False]).all():
        raise ValueError("Sector 5 temporal-grounding flags must be non-null booleans.")
    if not segments["verified_temporal_boundary_available"].eq(False).all():
        raise ValueError("Observed finding anchors cannot be treated as verified clinical boundaries.")
    group = labelled.groupby("finding_segment_id", sort=False, observed=True)
    invariants = ["video_key", "finding_class_normalized", "clinical_group", "split"]
    if group[invariants].nunique(dropna=False).gt(1).any(axis=1).any():
        raise ValueError("One finding segment contains conflicting source video, finding, taxonomy or split.")
    expected = group.agg(
        video_key=("video_key", "first"), finding_class_normalized=("finding_class_normalized", "first"),
        clinical_group=("clinical_group", "first"), split=("split", "first"),
        verified_start_frame=("frame_number", "min"), verified_end_frame=("frame_number", "max"),
        verified_frame_count=("frame_number", "nunique"), verified_annotation_count=("annotation_id", "size"),
    ).sort_index()
    actual = segments.set_index("finding_segment_id").loc[expected.index, expected.columns]
    try:
        # Identical validated IDs may use object or StringDtype after Parquet
        # readback/groupby. Ignore index storage dtype only; labels, order,
        # index names and every summary value still have to agree.
        pd.testing.assert_frame_equal(actual, expected, check_dtype=False,
                                      check_index_type=False, check_categorical=False)
    except AssertionError as error:
        raise ValueError("Sector 5 summary counts, observed ranges or split assignments disagree with every retained annotation.") from error
    lookup = labelled.set_index("annotation_id")
    anchor_positions = labelled.groupby(["finding_segment_id", "frame_number"], sort=False, observed=True).indices
    for target in segments.to_dict("records"):
        segment_id = target["finding_segment_id"]
        positions = anchor_positions.get((segment_id, target["target_frame_number"]), np.empty(0, dtype="int64"))
        members = labelled.iloc[positions]
        ids = json.loads(str(target["target_annotation_ids_json"]))
        annotation_records = json.loads(str(target["target_annotations_json"]))
        if (members.empty or not isinstance(ids, list) or len(ids) != len(set(ids))
                or set(ids) != set(members["annotation_id"])
                or int(target["target_annotation_count"]) != len(members)
                or not isinstance(annotation_records, list)
                or any(not isinstance(item, dict) for item in annotation_records)
                or {item.get("annotation_id") for item in annotation_records} != set(ids)
                or len(annotation_records) != len(members)):
            raise ValueError(f"Sector 5 target annotation collection is incomplete: {segment_id}")
        if target["target_image_annotation_id"] not in ids:
            raise ValueError(f"Sector 5 representative annotation does not belong to its target frame: {segment_id}")
        representative = lookup.loc[target["target_image_annotation_id"]]
        for target_column, member_column in (
            ("video_key", "video_key"), ("finding_class_normalized", "finding_class_normalized"),
            ("split", "split"), ("target_frame_number", "frame_number"),
            ("target_opencv_frame_index", "opencv_frame_index"),
            ("target_image_relpath", "image_relpath"), ("target_image_path", "image_path"),
        ):
            saved, source = target[target_column], representative[member_column]
            if pd.isna(saved) or pd.isna(source) or saved != source:
                raise ValueError(f"Sector 5 representative target disagrees with its source annotation: {segment_id}/{target_column}")
        for annotation in annotation_records:
            source = lookup.loc[annotation["annotation_id"]]
            for name, saved in annotation.items():
                if name == "annotation_id":
                    continue
                if name not in source.index:
                    raise ValueError(f"Sector 5 target annotation has an unknown source field: {name}")
                live = source[name]
                saved_missing, live_missing = pd.isna(saved), pd.isna(live)
                if saved_missing != live_missing or (not saved_missing and saved != live):
                    raise ValueError(f"Sector 5 target annotation collection changed expert metadata: {segment_id}/{name}")
    bounds = segments["video_key"].map(video_frames.set_index("video_key")["frame_count"])
    if bounds.isna().any() or not segments["target_opencv_frame_index"].ge(0).all() or not segments["target_opencv_frame_index"].lt(bounds).all():
        raise ValueError("Sector 5 target decoded indices lie outside current completed Sector 2 video bounds.")


def _s6_install_metadata(path, payload):
    """Keep matching local metadata bytes; atomically replace only missing/changed bytes."""
    path = Path(path)
    expected = hashlib.sha256(payload).hexdigest()
    if path.is_symlink():
        raise RuntimeError(f'Unsafe local metadata symlink: {path}')
    if path.is_file() and path.stat().st_size == len(payload) and _p3_file_hash(path) == expected:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(prefix='.' + path.name + '.', suffix='.tmp', dir=path.parent, delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(payload)
        if _p3_file_hash(temporary) != expected:
            raise RuntimeError(f'Local Git metadata writeback failed: {path.name}')
        temporary.replace(path)
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def io_s7_fetch_main(repo_url, repo):
    repo = Path(repo)
    if not repo.exists():
        return io_s5_fetch_main(repo_url, repo)
    if io_s5_git(repo, 'rev-parse', '--is-bare-repository').decode().strip() != 'true':
        raise RuntimeError('The source cache must be a bare repository, never a working-tree input override.')
    configured = io_s5_git(repo, 'remote', 'get-url', 'origin').decode().strip()
    if configured.rstrip('/').removesuffix('.git') != repo_url.rstrip('/').removesuffix('.git'):
        raise ValueError('The local Git object cache points at another source repository.')
    io_s5_git(repo, 'fetch', '--quiet', '--depth=1', '--filter=blob:none', 'origin',
              '+refs/heads/main:refs/heads/main')
    commit = io_s5_git(repo, 'rev-parse', 'refs/heads/main^{commit}').decode().strip()
    if re.fullmatch(r'[0-9a-f]{40}', commit) is None:
        raise RuntimeError('Published main did not resolve to a full immutable commit SHA.')
    return commit


S6_STATE_PATH = 'configs/sector6_state.json'


S6_RECEIPT_PATH = 'configs/sector6_publication_receipt.json'


S6_EXECUTION_RECEIPT_PATH = 'configs/sector6_execution_receipt.json'


S6_LINEAGE_PATH = 'configs/sector6_lineage.json'


S6_CONFIG_PATH = 'configs/sector6_config.json'


S6_RESULT_NAMES = frozenset({'temporal_manifest', 'temporal_extraction_requests', 'extracted_temporal_frames'})


S6_REPORT_NAMES = frozenset({'temporal_window_report', 'temporal_extraction_failures', 'temporal_image_audit', 'temporal_status_report'})


S6_OPERATIONAL_KEYS = frozenset({
    'sector6_staged_sources', 'local_stat', 'local_file_stats', 'image_verification',
    'work_dir', 'local_workspace_root', 'source_workspace', '_source_workspace', 'local_root', 'local_storage_root',
    'elapsed_seconds', 'elapsed_s', 'duration_seconds', 'wall_time_seconds', 'timings',
    'image_audit_execution', 'copied_file_count', 'reused_file_count',
    'copied_bytes', 'reused_bytes', 'decoded_image_count', 'reused_image_count',
})


def _p6_drop_runtime(value, strip_acquisition=False):
    if isinstance(value, dict):
        return {str(key): _p6_drop_runtime(item, strip_acquisition) for key, item in value.items()
                if str(key).lower() not in S6_OPERATIONAL_KEYS
                and (not strip_acquisition or str(key).lower() not in {'source_commit', 'acquisition_commit'})}
    if isinstance(value, list):
        return [_p6_drop_runtime(item, strip_acquisition) for item in value]
    return value


def _p6_export_config(config):
    clean = _p6_drop_runtime(json.loads(_p3_json_text(config)), strip_acquisition=True)
    if 'sector6' in clean and clean['sector6'].get('drive_storage_root'):
        clean['storage_root'] = clean['sector6']['drive_storage_root']
    return sector4_semantic_config(clean)


def sector6_semantic_config_fingerprint(config):
    return _s3_semantic_digest(_p6_export_config(config))


def sector6_processing_signature(config, lineage):
    hashes, core_hash = lineage.get('input_sha256'), lineage.get('core_source_sha256')
    if not isinstance(hashes, dict) or not hashes or not isinstance(core_hash, str):
        raise ValueError('Sector 6 needs checked input hashes and its active code identity.')
    return _p3_json_hash({'phase': 2, 'sector': 6, 'schema_version': 2,
                         'semantic_config_fingerprint': sector6_semantic_config_fingerprint(config),
                         'input_sha256': hashes, 'core_source_sha256': core_hash})


def _p6_metadata_path(relative):
    relative = _p3_relative(relative)
    if PurePosixPath(relative).suffix.lower() not in {'.parquet', '.csv', '.json', '.md'}:
        raise ValueError('Only metadata tables/configuration/reports belong in the GitHub Sector 6 bundle.')
    if relative in {S6_RECEIPT_PATH, S6_EXECUTION_RECEIPT_PATH}:
        raise ValueError('Operational receipts are not published artifacts.')
    return relative


def _s7_rebase_extra_image_paths(table, storage_root):
    """Rebase every paired image path and the saved official candidate references."""
    result = table.copy()
    for column in result.columns:
        if column.endswith('image_path'):
            relative_column = column[:-len('path')] + 'relpath'
            if relative_column in result:
                values = result[relative_column].map(
                    lambda value: _s6_portable_path(value, storage_root, relative_column))
                result[column] = values.astype(result[column].dtype)
    if 'context_official_images_json' in result:
        def rebase_candidates(value):
            if pd.isna(value):
                return pd.NA
            candidates = json.loads(str(value))
            if not isinstance(candidates, list) or any(not isinstance(item, dict) for item in candidates):
                raise ValueError('Official candidate images must be a JSON list of descriptors.')
            for candidate in candidates:
                if 'image_path' in candidate:
                    if 'image_relpath' not in candidate:
                        raise KeyError('Official candidate image lacks image_relpath.')
                    path = _s6_portable_path(candidate['image_relpath'], storage_root, 'candidate/image_relpath')
                    candidate['image_path'] = None if pd.isna(path) else path
            return json.dumps(candidates, ensure_ascii=False, allow_nan=False, sort_keys=True, separators=(',', ':'))
        result['context_official_images_json'] = result['context_official_images_json'].map(rebase_candidates).astype('string')
    return result


def _s7_inherit_configuration(source6, settings, storage_root, local_root):
    # S6's saved effective configuration is authoritative, including overrides
    # that were absent from Sector 5. Only the current storage root is rebased.
    config = copy.deepcopy(source6)
    config["storage_root"] = str(storage_root)
    decisions = []
    for key, fallback in S7_DEFAULTS.items():
        override = settings.get(key)
        value = override if override is not None else source6.get(key, fallback)
        config[key] = copy.deepcopy(value)
        decisions.append({"config_key": key, "effective_value_json": _s3_semantic_json(value),
                          "resolution": "sector7_override" if override is not None else
                          "inherited_sector6" if key in source6 else "declared_sector7_default"})
    sector7 = {key: copy.deepcopy(config[key]) for key in S7_DEFAULTS}
    for key, fallback in (("local_output_dir", "outputs/phase2/sector7"),
                          ("export_dir", "outputs/phase2/sector7")):
        sector7[key] = settings.get(key, fallback)
    if sector7["export_dir"] != "outputs/phase2/sector7":
        raise ValueError("Sector 7 export_dir must be outputs/phase2/sector7.")
    local_dir = sector7["local_output_dir"]
    if not isinstance(local_dir, str) or not local_dir.strip():
        raise ValueError("Sector 7 local_output_dir must be a nonempty directory string.")
    if not Path(local_dir).expanduser().is_absolute():
        _s6_portable_path(local_dir, storage_root, "local_output_dir")
    github = copy.deepcopy(source6.get("github", {}))
    overrides = copy.deepcopy(settings.get("github_overrides", {}))
    if not isinstance(overrides, dict) or set(overrides) - {"token_secret_name"}:
        raise ValueError(
            "Sector 7 github_overrides supports only token_secret_name; repository and branch are inherited.")
    if "token_secret_name" in overrides:
        name = overrides["token_secret_name"]
        if not isinstance(name, str) or not name.strip() or re.search(r"\s", name):
            raise ValueError("token_secret_name must be a nonempty secret reference without whitespace.")
    for flag in ("push", "dry_run"):
        value = settings.get(flag, github.get(flag, False))
        if not isinstance(value, bool):
            raise ValueError(f"SECTOR7_SETTINGS[{flag!r}] must be a boolean.")
        sector7[flag] = value
    sector7["github_overrides"] = overrides
    github.update(overrides)
    github.update({"repo_output_dir": sector7["export_dir"],
                   "push": sector7["push"], "dry_run": sector7["dry_run"],
                   "commit_message": "Phase 2 Sector 7: publish image quality metrics and review flags"})
    github.pop("confirm_push", None)
    config.update({"phase": 2, "sector": 7, "sector7": sector7, "github": github})
    for key in S4_EXECUTION_METADATA_KEYS:
        config.pop(key, None)

    sector7["drive_storage_root"] = str(storage_root)
    sector7["local_workspace_root"] = str(local_root)
    config["sector7"] = sector7
    return config, decisions


# Mutable acquisition bookkeeping is deliberately outside the core-code constants.
_s7_git_read_records = {}


def io_s5_git_blob(repo, commit, relative):
    """Read a regular S1–S6 metadata blob from the one pinned main commit."""
    if re.fullmatch(r'[0-9a-f]{40}', str(commit)) is None:
        raise ValueError('A full pinned main commit SHA is required.')
    relative = _s5_git_relative(relative)
    if (not re.match(r'outputs/phase2/sector[1-6]/', relative)
            or not relative.endswith(('.json', '.csv', '.csv.gz', '.parquet', '.md', '.txt'))):
        raise ValueError('S7 reads only published upstream metadata, never raw media or notebook code.')
    entry = io_s5_git(repo, 'ls-tree', '-z', commit, '--', relative)
    if (not entry or entry.count(b'\0') != 1 or b'\t' not in entry
            or entry.split(b'\t', 1)[1] != relative.encode('utf-8') + b'\0'):
        raise FileNotFoundError(f'Pinned main lacks a regular metadata blob: {relative}')
    fields = entry.split(b'\t', 1)[0].split(b' ')
    if fields[:2] not in ([b'100644', b'blob'], [b'100755', b'blob']):
        raise ValueError(f'Published metadata cannot be a symlink or submodule: {relative}')
    payload = io_s5_git(repo, 'cat-file', 'blob', f'{commit}:{relative}')
    oid = hashlib.sha1(b'blob ' + str(len(payload)).encode('ascii') + b'\0' + payload).hexdigest()
    if fields[2].decode() != oid:
        raise RuntimeError(f'Git blob identity verification failed: {relative}')
    record = {'sha256': hashlib.sha256(payload).hexdigest(), 'bytes': len(payload), 'git_blob_oid': oid}
    files = _s7_git_read_records.setdefault((str(Path(repo).resolve()), commit), {})
    if relative in files and files[relative] != record:
        raise RuntimeError('A pinned Git metadata object changed while loading.')
    files[relative] = record
    _s6_install_metadata(Path(repo).parent / 'blob-cache' / oid, payload)
    return payload


def io_s5_load_published_chain(bootstrap):
    """Supply the existing S7-pinned snapshot to the copied S5 contract reader."""
    published = bootstrap.get('_s7_published_context')
    if not isinstance(published, dict):
        raise RuntimeError('S7 must pin published main before loading the upstream chain.')
    return published


def _p6_read_state(root):
    """Verify the current S6 metadata catalog, producer identities and deferred status."""
    root = Path(root).resolve()
    state_path = _p3_safe_path(root, S6_STATE_PATH)
    if not state_path.is_file():
        return None
    state = _s5_json(state_path)
    if (state.get('schema_version') != 2 or state.get('complete') is not True
            or state.get('content_id') != _p3_json_hash(_p3_catalog_meaning(state))):
        raise RuntimeError('Published S6 catalog is incomplete or its fingerprint is invalid.')
    if (not isinstance(state.get('artifacts'), list)
            or not all(isinstance(record, dict) for record in state['artifacts'])
            or not isinstance(state.get('tables'), dict)
            or not all(isinstance(record, dict) for record in state['tables'].values())):
        raise RuntimeError('Published S6 artifact/table descriptors are malformed.')
    if set(state['tables']) != S6_RESULT_NAMES | S6_REPORT_NAMES:
        raise RuntimeError('Publish the complete current S6 metadata bundle before S7.')
    records = {record['relative_path']: record for record in state['artifacts']}
    operational = {S6_STATE_PATH, S6_RECEIPT_PATH, S6_EXECUTION_RECEIPT_PATH}
    if len(records) != len(state['artifacts']) or operational.intersection(records):
        raise RuntimeError('Published S6 catalog has duplicate or operational artifact entries.')
    for relative, expected in records.items():
        path = _p3_safe_path(root, _p6_metadata_path(relative))
        if (not path.is_file() or path.stat().st_size != expected['bytes']
                or _p3_file_hash(path) != expected['sha256']):
            raise RuntimeError(f'Published S6 metadata checksum failed: {relative}')
    if state.get('config_snapshot') != S6_CONFIG_PATH or not {S6_CONFIG_PATH, S6_LINEAGE_PATH}.issubset(records):
        raise RuntimeError('S6 must publish its current config and lineage at their declared stable paths.')
    envelope = _s5_json(_p3_safe_path(root, S6_CONFIG_PATH))
    config = envelope.get('effective_config')
    if not isinstance(config, dict) or config.get('phase') != 2 or config.get('sector') != 6:
        raise RuntimeError('Published S6 effective config is malformed.')
    if (envelope.get('current_lineage_path') != S6_LINEAGE_PATH
            or envelope.get('semantic_config_fingerprint') != state['semantic_config_fingerprint']
            or sector6_semantic_config_fingerprint(config) != state['semantic_config_fingerprint']):
        raise RuntimeError('Published S6 effective config differs from its catalog.')
    if config.get('temporal_context_split_policy') != 'deferred':
        raise RuntimeError('S7 requires the current deferred S6 material contract; rerun/publish S6.')
    lineage = _s5_json(_p3_safe_path(root, S6_LINEAGE_PATH))
    if (lineage.get('input_sha256') != state['input_sha256']
            or lineage.get('core_source_sha256') != state['core_source_sha256']
            or not isinstance(lineage.get('input_descriptors'), dict)
            or set(lineage['input_descriptors']) != set(state['input_sha256'])
            or sector6_processing_signature(config, lineage) != state['processing_signature']):
        raise RuntimeError('Published S6 processing identity differs from its saved provenance.')
    for name, descriptor in state['tables'].items():
        if not {descriptor['relative_path'], descriptor['schema_path']}.issubset(records):
            raise RuntimeError(f'Published S6 table/schema is absent from its catalog: {name}')
        schema = _s5_json(_p3_safe_path(root, descriptor['schema_path']))
        if schema.get('artifact') != descriptor['relative_path'] or schema.get('fingerprint') != descriptor['fingerprint']:
            raise RuntimeError(f'Published S6 table schema differs from its descriptor: {name}')
    summary_descriptor = state['summary']
    if not {summary_descriptor['summary_relative_path'], summary_descriptor['report_relative_path']}.issubset(records):
        raise RuntimeError('Published S6 summary/report is absent from its catalog.')
    summary = _s5_json(_p3_safe_path(root, summary_descriptor['summary_relative_path']))
    if (_p3_json_hash(summary) != summary_descriptor['fingerprint']
            or records[summary_descriptor['report_relative_path']]['sha256'] != summary_descriptor['report_fingerprint']):
        raise RuntimeError('Published S6 summary/report differs from its catalog.')
    if (summary.get('phase') != 2 or summary.get('sector') != 6
            or summary.get('split_policy') != 'deferred'
            or summary.get('split_assignment_status') != 'pending'
            or summary.get('training_ready') is not False
            or summary.get('split_excluded_context_rows') != 0
            or summary.get('validation_passed') is not True
            or summary.get('execution_outcome') != 'complete'):
        raise RuntimeError('S6 must certify complete material with deferred, pending splits and training_ready=false.')
    for relative in state.get('obsolete_paths', []):
        if not _p3_relative(relative).startswith('results/') or relative in records:
            raise RuntimeError('Published S6 obsolete-result entry is invalid.')
    return state


def io_s7_stage_sector6(repo, commit, stage_root):
    """Stage only catalog-declared S6 metadata from immutable Git objects."""
    prefix = 'outputs/phase2/sector6'
    payload = io_s5_git_blob(repo, commit, prefix + '/' + S6_STATE_PATH)
    state = json.loads(payload)
    if (not isinstance(state, dict) or state.get('schema_version') != 2
            or state.get('complete') is not True
            or state.get('content_id') != _p3_json_hash(_p3_catalog_meaning(state))):
        raise RuntimeError('Publish a complete current S6 catalog to main before S7.')
    root = Path(stage_root) / prefix
    records = state.get('artifacts')
    if not isinstance(records, list) or not all(isinstance(record, dict) for record in records):
        raise RuntimeError('Published S6 catalog lacks valid artifact records.')
    paths = [_p6_metadata_path(record['relative_path']) for record in records]
    if len(paths) != len(set(paths)) or S6_STATE_PATH in paths:
        raise RuntimeError('Published S6 catalog has duplicate or operational paths.')
    for relative, record in zip(paths, records):
        artifact = io_s5_git_blob(repo, commit, prefix + '/' + relative)
        if len(artifact) != record['bytes'] or hashlib.sha256(artifact).hexdigest() != record['sha256']:
            raise RuntimeError(f'Pinned-main S6 artifact differs from its catalog: {relative}')
        _s6_install_metadata(_p3_safe_path(root, relative), artifact)
    _s6_install_metadata(_p3_safe_path(root, S6_STATE_PATH), payload)
    checked = _p6_read_state(root)
    config_path = _p3_safe_path(root, checked['config_snapshot'])
    return {'root': root, 'state': checked, 'state_path': root / S6_STATE_PATH,
            'state_sha256': hashlib.sha256(payload).hexdigest(),
            'snapshot_path': config_path, 'snapshot_sha256': _p3_file_hash(config_path),
            'config': _s5_json(config_path)['effective_config'],
            'lineage': _s5_json(root / S6_LINEAGE_PATH),
            'summary': _s5_json(root / checked['summary']['summary_relative_path'])}


def io_s7_load_published_snapshot(bootstrap):
    """Pin main once and stage S1–S6 certificates; Drive is not metadata authority."""
    repo_url = str(bootstrap.get('repo_url', '')).rstrip('/').removesuffix('.git')
    if (re.fullmatch(r'https://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+', repo_url) is None
            or bootstrap.get('branch', 'main') != 'main'):
        raise ValueError('S7 metadata authority must be one credential-free GitHub HTTPS repository on main.')
    for name in ('sector2_results_dir', 'sector2_manifests_dir', 'sector2_configs_dir',
                 'sector3_dir', 'sector4_dir', 'sector5_dir', 'sector6_dir'):
        if bootstrap.get(name) is not None:
            raise ValueError(f'Local metadata override {name} is unsupported; publish the upstream bundle to main.')
    local = Path(bootstrap['local_workspace_root']).expanduser().resolve()
    drive_root = Path(bootstrap['storage_root']).expanduser().resolve()
    if (local == drive_root or local in drive_root.parents or drive_root in local.parents
            or str(local).startswith('/content/drive/')):
        raise ValueError('S7 local metadata workspace must be separate from its Google Drive media/output root.')
    source_root = local / '.published_sources'
    source_root.mkdir(parents=True, exist_ok=True)
    if source_root.is_symlink():
        raise ValueError('S7 published-source workspace cannot be a symlink.')
    repo = source_root / 'source.git'
    commit = io_s7_fetch_main(repo_url, repo)
    _s7_git_read_records[(str(repo.resolve()), commit)] = {}
    stage_root = source_root / 'metadata' / commit
    stage_root.mkdir(parents=True, exist_ok=True)
    contexts = {sector: io_s5_stage_catalog(repo, commit, stage_root, sector) for sector in (3, 4, 5)}
    for sector, context in contexts.items():
        github = context['config'].get('github', {})
        if (github.get('branch') != 'main'
                or str(github.get('repo_url', '')).rstrip('/').removesuffix('.git') != repo_url):
            raise ValueError(f'Published S{sector} config refers to another repository or branch.')
    published2 = io_s5_stage_sector2(repo, commit, stage_root)
    catalog1 = published2['s1_catalog']
    if catalog1.get('format_version') != 2 or catalog1.get('raw_integrity_version') != 1:
        raise ValueError('S1 must publish its supported complete raw-integrity catalog.')
    provenance = {'repo_url': repo_url, 'source_branch': 'main', 'source_commit': commit,
                  'input_source': 'published_git_objects_only'}
    upstream_files = copy.deepcopy(_s7_git_read_records[(str(repo.resolve()), commit)])
    context6 = io_s7_stage_sector6(repo, commit, stage_root)
    github6 = context6['config'].get('github', {})
    if (github6.get('branch') != 'main'
            or str(github6.get('repo_url', '')).rstrip('/').removesuffix('.git') != repo_url):
        raise ValueError('Published S6 configuration refers to another repository or branch.')
    return {'context3': contexts[3], 'context4': contexts[4], 'context5': contexts[5],
            'context6': context6, 'sector2': published2, 'stage_root': stage_root,
            'workspace': None, 'repo': repo, 'provenance': provenance,
            'upstream_files': upstream_files}


def _s7_validate_s6_source_lineage(context6, current_lineage, published, tables6):
    """Compare every S6 consumed identity with the current certified S1–S5 chain."""
    saved = context6['lineage']
    source = saved.get('github_source', {})
    files = source.get('files')
    if (source.get('source_branch') != 'main'
            or source.get('input_source') != 'published_git_objects_only'
            or str(source.get('repo_url', '')).rstrip('/').removesuffix('.git') != published['provenance']['repo_url']
            or re.fullmatch(r'[0-9a-f]{40}', str(source.get('source_commit', ''))) is None
            or not isinstance(files, dict)
            or source.get('snapshot_sha256') != _s3_semantic_digest(files)):
        raise RuntimeError('Published S6 lacks a valid GitHub-main producer snapshot.')
    if files != published['upstream_files']:
        changed = sorted(key for key in set(files) | set(published['upstream_files'])
                         if files.get(key) != published['upstream_files'].get(key))
        raise RuntimeError('S6 was built from another upstream metadata snapshot. '
                           f'Rerun/publish S6; changed files: {changed[:12]}')
    if saved.get('raw_references') != current_lineage.get('raw_references'):
        raise RuntimeError('Published S6 raw-reference certificates differ from current S1–S5.')
    expected = copy.deepcopy(current_lineage['input_sha256'])
    videos = pd.read_csv(published['sector2']['dirs2']['manifests'] / 'video_manifest.csv',
                         dtype={'video_key': 'string', 'video_sha256': 'string'})
    images = pd.read_csv(published['sector2']['image_inventory_path'],
                         dtype={'image_relpath': 'string', 'image_sha256': 'string'})
    for table, key in ((videos, 'video_key'), (images, 'image_relpath')):
        if table[key].isna().any() or not table[key].is_unique:
            raise RuntimeError('Certified raw-source inventory identities must be unique and non-null.')
    video_hashes = videos.set_index('video_key')['video_sha256']
    image_hashes = images.set_index('image_relpath')['image_sha256']
    extracted = tables6['extracted_temporal_frames']
    sources = extracted[['video_key', 'source_video_sha256']].dropna().drop_duplicates()
    if sources['video_key'].duplicated().any():
        raise RuntimeError('S6 extraction results disagree on a consumed source-video hash.')
    for row in sources.itertuples(index=False):
        if row.video_key not in video_hashes or row.source_video_sha256 != video_hashes.loc[row.video_key]:
            raise RuntimeError(f'S6 source-video hash differs from current S2: {row.video_key}')
        expected['source_video/' + str(row.video_key)] = row.source_video_sha256
    extracted_relpaths = set(extracted['extracted_image_relpath'].dropna().astype(str))
    audit = tables6['temporal_image_audit']
    official = audit.loc[audit['image_readable'].eq(True)
                         & ~audit['context_image_relpath'].isin(extracted_relpaths)]
    for row in official.itertuples(index=False):
        relative = str(row.context_image_relpath)
        if relative not in image_hashes or row.image_sha256 != image_hashes.loc[relative]:
            raise RuntimeError(f'S6 official-image hash differs from current S1: {relative}')
        expected['official_image/' + relative] = row.image_sha256
    if saved['input_sha256'] != expected:
        changed = sorted(key for key in set(saved['input_sha256']) | set(expected)
                         if saved['input_sha256'].get(key) != expected.get(key))
        raise RuntimeError('S6 consumed hashes disagree with current metadata/raw-source certificates. '
                           f'Rerun/publish S6; changed identities: {changed[:12]}')
    summary = context6['summary']
    if summary.get('table_row_counts') != {name: len(frame) for name, frame in tables6.items()}:
        raise RuntimeError('S6 report row counts disagree with its typed manifest/report tables.')
    return True


def io_load_sector7_context(bootstrap, settings):
    """Load verified published S1–S6 metadata; media staging remains a later I/O step."""
    if not isinstance(bootstrap, dict) or not isinstance(settings, dict):
        raise TypeError('BOOTSTRAP and SECTOR7_SETTINGS must be dictionaries.')
    allowed = set(S7_DEFAULTS) | {'local_output_dir', 'export_dir', 'push', 'dry_run', 'github_overrides'}
    unknown = sorted(set(settings) - allowed)
    if unknown:
        raise KeyError(f'Unexpected Sector 7 settings: {unknown}')
    storage_root = Path(bootstrap['storage_root']).expanduser().resolve()
    local_root = Path(bootstrap['local_workspace_root']).expanduser().resolve()
    published = io_s7_load_published_snapshot(bootstrap)
    context5, context6 = published['context5'], published['context6']
    source5 = context5['config']
    if source5.get('phase') != 2 or source5.get('sector') != 5:
        raise RuntimeError('Current S5 must publish a Phase 2 Sector 5 effective configuration.')
    inherited5 = {key: source5.get(key) for key in SECTOR5_DEFAULTS}
    inherited5.update({key: source5.get('sector5', {}).get(key, default) for key, default in (
        ('local_output_dir', 'outputs/phase2/sector5'), ('export_dir', 'outputs/phase2/sector5'))})
    inherited5.update({key: source5.get('github', {}).get(key, False) for key in ('push', 'dry_run')})
    context234 = io_load_sector5_context({**bootstrap, '_s7_published_context': published}, inherited5)
    if context5['state']['input_sha256'] != context234['lineage']['input_sha256']:
        raise RuntimeError('Published S5 was not built from the current S1–S4 chain; rerun/publish upstream sectors.')
    tables5 = _s5_required_tables(context5, tuple(context5['state']['tables']))
    validate_segment_manifest_raw_references(tables5['finding_segment_manifest'], tables5['labelled_frame_manifest_with_segments'])
    if context5['envelope'].get('lineage', {}).get('raw_references') != context234['lineage']['raw_references']:
        raise RuntimeError('Published S5 raw-reference certificates disagree with current S1–S4.')
    runtime5 = {name: _s6_rebase_live_paths(table, storage_root) for name, table in tables5.items()}
    _s6_validate_sector5_tables(runtime5, context234['inputs']['sector4']['labelled_frame_manifest_with_split'],
                                context234['inputs']['sector3']['video_frame_manifest'])
    lineage = copy.deepcopy(context234['lineage'])
    hashes, descriptors = lineage['input_sha256'], lineage['input_descriptors']
    for name, descriptor in context5['state']['tables'].items():
        for field in ('relative_path', 'schema_path'):
            path = _p3_safe_path(context5['root'], descriptor[field])
            key = f'sector5/{name}/{field}'
            hashes[key], descriptors[key] = _p3_file_hash(path), str(path)
    for label, path, digest in (
        ('state', context5['state_path'], context5['state_sha256']),
        ('config_snapshot', context5['snapshot_path'], context5['snapshot_sha256'])):
        hashes['sector5/' + label], descriptors['sector5/' + label] = digest, str(path)
    lineage['upstream']['sector5'] = {'root': str(context5['root']), 'content_id': context5['state']['content_id'],
        'state_sha256': context5['state_sha256'], 'config_snapshot': str(context5['snapshot_path']),
        'config_snapshot_sha256': context5['snapshot_sha256']}
    saved6 = {name: _p3_read_table(context6['root'], descriptor)
              for name, descriptor in context6['state']['tables'].items()}
    _s7_validate_s6_source_lineage(context6, lineage, published, saved6)
    runtime6 = {name: _s7_rebase_extra_image_paths(_s6_rebase_live_paths(table, storage_root), storage_root)
                for name, table in saved6.items()}
    validate_sector7_deferred_split_contract(runtime6['temporal_manifest'],
        context234['inputs']['sector4']['frame_split_manifest'], runtime5['labelled_frame_manifest_with_segments'])
    config, decisions = _s7_inherit_configuration(context6['config'], settings, storage_root, local_root)
    for record in context6['state']['artifacts']:
        key = 'sector6/artifact/' + record['relative_path']
        hashes[key] = record['sha256']
        descriptors[key] = str(_p3_safe_path(context6['root'], record['relative_path']))
    for label, path, digest in (
        ('state', context6['state_path'], context6['state_sha256']),
        ('config_snapshot', context6['snapshot_path'], context6['snapshot_sha256'])):
        hashes['sector6/' + label], descriptors['sector6/' + label] = digest, str(path)
    lineage['upstream']['sector6'] = {'root': str(context6['root']), 'content_id': context6['state']['content_id'],
        'state_sha256': context6['state_sha256'], 'config_snapshot': str(context6['snapshot_path']),
        'config_snapshot_sha256': context6['snapshot_sha256']}
    lineage['sector6_saved_input_sha256'] = copy.deepcopy(context6['lineage']['input_sha256'])
    lineage['sector6_saved_input_descriptors'] = copy.deepcopy(context6['lineage']['input_descriptors'])
    lineage['config_inheritance_report'] = pd.DataFrame.from_records(decisions)
    lineage['config_inheritance_policy'] = 'Pinned-main S1–S6 certificates; current S6 effective config with explicit S7 overrides.'
    files = copy.deepcopy(_s7_git_read_records[(str(Path(published['repo']).resolve()), published['provenance']['source_commit'])])
    for relative, record in files.items():
        key = 'published_git/' + relative
        hashes[key] = record['sha256']
        descriptors[key] = str(Path(published['repo']).parent / 'blob-cache' / record['git_blob_oid'])
    lineage['github_source'] = {**published['provenance'], 'files': files, 'snapshot_sha256': _s3_semantic_digest(files)}
    lineage['github_authority'] = {'repo_url': published['provenance']['repo_url'], 'branch': 'main',
        'commit': published['provenance']['source_commit'], 'files': {path: record['sha256'] for path, record in files.items()}}
    lineage['source_config_provenance'] = copy.deepcopy(published['provenance'])
    for key, digest in hashes.items():
        _s5_checked_hash(descriptors[key], digest)
    inputs = copy.copy(context234['inputs'])
    inputs.update({'sector5': runtime5, 'sector6': runtime6,
                   'sector6_config': copy.deepcopy(context6['config']),
                   'sector6_lineage': copy.deepcopy(context6['lineage'])})
    return {'config': config, 'inputs': inputs, 'lineage': lineage,
            'source6_config': copy.deepcopy(context6['config']), 'source6_lineage': copy.deepcopy(context6['lineage']),
            'source_snapshot': copy.deepcopy(lineage['github_source']), '_published': published,
            '_source_workspace': published['stage_root']}

## 4. Technical QC and deferred split semantics

Build one QC record per distinct image file. A physical frame may have several official annotation-specific files; their identities remain linked while each file receives its own byte and pixel checks. Shared temporal files are measured once and joined back to every reference.

Metrics use a circular field-of-view mask: brightness, contrast, Laplacian blur, underexposure, overexposure and specular fractions. NVIDIA JPEG decoding and CuPy are preferred, with recorded CPU/hybrid fallback.

No current split is used to fit quantiles. Numeric statistical thresholds and quantile-outlier flags are null; `qc_thresholds_calibrated=false`. `qc_requires_review` identifies explicit read/technical failures, not a complete quality pass. `image_technically_usable` means decodable only. The compatibility field `image_usable_for_modelling` and `training_ready` are always false. Source rows and annotations are preserved.

In [30]:
# ------------------------------------------------------------------
# Pure QC transformations. File/image reads are confined to io_ functions.
# ------------------------------------------------------------------

IMAGE_QC_COLUMNS = [
    'image_path', 'image_sha256', 'image_readable', 'image_read_error',
    'image_width', 'image_height', 'brightness_mean', 'contrast_std',
    'blur_laplacian', 'underexposed_fraction', 'overexposed_fraction',
    'specular_fraction', 'image_decode_backend', 'image_qc_backend', 'image_fallback_reason',
]
IMAGE_QC_FLAG_COLUMNS = [
    'qc_blur_outlier', 'qc_contrast_outlier', 'qc_low_brightness_outlier',
    'qc_high_brightness_outlier', 'qc_thresholds_calibrated',
    'qc_requires_review', 'image_technically_usable', 'training_ready', 'image_usable_for_modelling',
]
IMAGE_QC_THRESHOLD_COLUMNS = [
    'blur_laplacian_lower_threshold', 'contrast_std_lower_threshold',
    'brightness_mean_lower_threshold', 'brightness_mean_upper_threshold',
    'threshold_calibration_status', 'threshold_fit_split',
    'calibration_candidate_images', 'calibration_readable_images',
    'total_readable_images',
]
IMAGE_QC_INVENTORY_COLUMNS = [
    'image_relpath', 'image_path', 'physical_frame_id', 'video_key', 'opencv_frame_index',
    'upstream_splits_json', 'upstream_split_count', 'final_split', 'split_assignment_status',
    'used_by_labelled_manifest', 'used_by_temporal_manifest',
]
IMAGE_QC_MANIFEST_COLUMNS = [
    *IMAGE_QC_INVENTORY_COLUMNS,
    *[name for name in IMAGE_QC_COLUMNS if name != 'image_path'],
    *IMAGE_QC_FLAG_COLUMNS, 'qc_assessment_status',
]
IMAGE_READ_FAILURE_REPORT_COLUMNS = [
    'image_relpath', 'image_path', 'physical_frame_id', 'image_read_error',
    'used_by_labelled_manifest', 'used_by_temporal_manifest',
]
QC_REFERENCE_COLUMNS = [
    'source_manifest', 'source_row', 'source_reference_id', 'image_path',
    'image_relpath', 'physical_frame_id', 'video_key', 'opencv_frame_index',
    'upstream_split', 'final_split', 'split_assignment_status', 'reference_status',
]
QC_REFERENCE_COVERAGE_COLUMNS = [
    'source_manifest', 'total_references', 'referenced_paths',
    'missing_path_references', 'pending_path_references',
    'qc_covered_references', 'readable_references', 'review_required_references',
]
QC_SUMMARY_COLUMNS = [
    'qc_status', 'total_unique_images', 'readable_images', 'unreadable_images',
    'review_required_images', 'technically_usable_images', 'model_usable_images',
    'training_ready', 'split_assignment_status', 'qc_assessment_status',
    'threshold_calibration_status', 'threshold_fit_split',
    'calibration_candidate_images', 'calibration_readable_images',
    'nvidia_gpu_decoded_images', 'nvidia_hybrid_decoded_images', 'cpu_decoded_images',
    'gpu_qc_images', 'cpu_qc_images', 'fallback_images',
]
_QC_BOOL_COLUMNS = frozenset({
    'image_readable', 'used_by_labelled_manifest', 'used_by_temporal_manifest', 'qc_reference_covered',
    *IMAGE_QC_FLAG_COLUMNS,
})
_QC_INT_COLUMNS = frozenset({
    'image_width', 'image_height', 'source_row', 'total_references',
    'opencv_frame_index', 'upstream_split_count', 'technically_usable_images',
    'referenced_paths', 'missing_path_references', 'pending_path_references',
    'qc_covered_references', 'readable_references', 'review_required_references',
    'total_unique_images', 'readable_images', 'unreadable_images',
    'review_required_images', 'technically_usable_images', 'model_usable_images',
    'calibration_candidate_images', 'calibration_readable_images',
    'total_readable_images', 'nvidia_gpu_decoded_images', 'nvidia_hybrid_decoded_images',
    'cpu_decoded_images', 'gpu_qc_images', 'cpu_qc_images', 'fallback_images',
})
_QC_FLOAT_COLUMNS = frozenset({
    'brightness_mean', 'contrast_std', 'blur_laplacian',
    'underexposed_fraction', 'overexposed_fraction', 'specular_fraction',
    *IMAGE_QC_THRESHOLD_COLUMNS[:4],
})


def qc_typed_table(frame):
    """Return stable nullable scalar dtypes, also for empty persisted tables."""
    result = frame.copy()
    for name in result:
        dtype = ('boolean' if name in _QC_BOOL_COLUMNS else
                 'Int64' if name in _QC_INT_COLUMNS else
                 'Float64' if name in _QC_FLOAT_COLUMNS else 'string')
        result[name] = result[name].astype(dtype)
    return result.reset_index(drop=True)


def qc_empty_table(columns):
    return qc_typed_table(pd.DataFrame(columns=columns))


def qc_require_columns(frame, required, name):
    missing = sorted(set(required) - set(frame))
    if missing:
        raise KeyError(f'{name} lacks columns: {missing}')


def validate_qc_quantiles(config):
    """Validate the four quantiles without reading data or mutating config."""
    names = {'blur': 'qc_blur_quantile', 'contrast': 'qc_contrast_quantile',
             'brightness_low': 'qc_brightness_low_quantile',
             'brightness_high': 'qc_brightness_high_quantile'}
    defaults = {'blur': 0.01, 'contrast': 0.01,
                'brightness_low': 0.01, 'brightness_high': 0.99}
    raw = {name: config.get(key, defaults[name]) for name, key in names.items()}
    if any(isinstance(value, (bool, np.bool_)) for value in raw.values()):
        raise ValueError('QC quantiles must be numbers, not booleans.')
    quantiles = pd.to_numeric(pd.Series(raw, dtype='object'), errors='coerce').astype('float64')
    if (quantiles.isna() | ~np.isfinite(quantiles) | quantiles.lt(0) | quantiles.gt(1)).any():
        raise ValueError('QC quantiles must be finite numbers between 0 and 1.')
    if quantiles['brightness_low'] >= quantiles['brightness_high']:
        raise ValueError('The lower brightness quantile must precede the upper quantile.')
    return quantiles


def validate_image_qc_config(config):
    """Fail before image reads when the authored QC settings are invalid."""
    validate_qc_quantiles(config)
    radius = config.get('qc_fov_radius_fraction', 0.95)
    if isinstance(radius, (bool, np.bool_)):
        raise ValueError('qc_fov_radius_fraction must be numeric.')
    try:
        radius = float(radius)
    except (TypeError, ValueError):
        raise ValueError('qc_fov_radius_fraction must be a number in (0, 1].') from None
    if not np.isfinite(radius) or not 0 < radius <= 1:
        raise ValueError('qc_fov_radius_fraction must be a finite number in (0, 1].')
    defaults = {'qc_underexposed_pixel_threshold': 20,
                'qc_overexposed_pixel_threshold': 240,
                'qc_specular_value_threshold': 240,
                'qc_specular_saturation_threshold': 30}
    thresholds = {}
    for name, default in defaults.items():
        value = config.get(name, default)
        if isinstance(value, (bool, np.bool_)):
            raise ValueError(f'{name} must be numeric.')
        try:
            value = float(value)
        except (TypeError, ValueError):
            raise ValueError(f'{name} must be a finite number in [0, 255].') from None
        if not np.isfinite(value) or not 0 <= value <= 255:
            raise ValueError(f'{name} must be a finite number in [0, 255].')
        thresholds[name] = value
    if thresholds['qc_underexposed_pixel_threshold'] >= thresholds['qc_overexposed_pixel_threshold']:
        raise ValueError('The underexposed pixel threshold must be below the overexposed threshold.')
    workers = config.get('qc_workers', 1)
    if isinstance(workers, (bool, np.bool_)) or not isinstance(workers, (int, np.integer)) or workers < 1:
        raise ValueError('qc_workers must be a positive integer.')
    fit_split = config.get('qc_threshold_fit_split', 'deferred')
    if fit_split != 'deferred':
        raise ValueError('QC thresholds must remain deferred until a validated final split exists; upstream_split is provenance only.')
    if 'qc_enabled' in config and not isinstance(config['qc_enabled'], (bool, np.bool_)):
        raise ValueError('qc_enabled must be a boolean.')
    if not config.get('qc_enabled', True):
        raise ValueError('Sector 7 QC must be enabled; run it with qc_enabled=True.')
    decoder = config.get('qc_decoder', 'nvimagecodec')
    policy = config.get('qc_gpu_backend_policy', 'gpu_preferred')
    if decoder != 'nvimagecodec' or policy != 'gpu_preferred':
        raise ValueError('Sector 7 requires nvimagecodec with gpu_preferred routing and CPU fallback.')
    gpu_id = config.get('qc_gpu_id', 0)
    batch_size = config.get('qc_decode_batch_size', 64)
    for name, value, minimum in (('qc_gpu_id', gpu_id, 0),
                                 ('qc_decode_batch_size', batch_size, 1)):
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, (int, np.integer)) or value < minimum:
            raise ValueError(f'{name} must be an integer >= {minimum}.')
    return {**thresholds, 'qc_fov_radius_fraction': radius,
            'qc_workers': int(workers), 'qc_threshold_fit_split': 'deferred',
            'qc_decoder': decoder, 'qc_gpu_backend_policy': policy,
            'qc_gpu_id': int(gpu_id), 'qc_decode_batch_size': int(batch_size)}


# Pure numeric QC transformations: explicit CuPy or NumPy, without reads or hidden backend switching.
def _qc_metric_array_module(array_module=None):
    gpu_module = globals().get('cp')
    if array_module is None:
        if gpu_module is None:
            raise RuntimeError('CuPy is unavailable; provide array_module=np for explicit CPU QC.')
        return gpu_module
    if array_module is np or (gpu_module is not None and array_module is gpu_module):
        return array_module
    raise TypeError('array_module must be explicitly CuPy or NumPy.')


def build_capsule_fov_mask(image_height, image_width, radius_fraction, *, array_module=None):
    """Build a circular FOV on the explicitly selected array device."""
    xp = _qc_metric_array_module(array_module)
    if (isinstance(radius_fraction, (bool, np.bool_)) or
            not np.isfinite(radius_fraction) or not 0 < radius_fraction <= 1):
        raise ValueError('qc_fov_radius_fraction must be in (0, 1].')
    if (isinstance(image_height, (bool, np.bool_)) or
            isinstance(image_width, (bool, np.bool_)) or
            not isinstance(image_height, (int, np.integer)) or
            not isinstance(image_width, (int, np.integer)) or
            image_height < 1 or image_width < 1):
        raise ValueError('Image dimensions must be positive integers.')
    yy, xx = xp.ogrid[:image_height, :image_width]
    radius = min(image_height, image_width) / 2.0 * radius_fraction
    return ((xx - (image_width - 1) / 2.0) ** 2 +
            (yy - (image_height - 1) / 2.0) ** 2 <= radius ** 2)


def _qc_eroded_fov_mask(mask, xp):
    """Erode one pixel in every direction, with an excluded image boundary."""
    eroded = xp.zeros_like(mask, dtype=xp.bool_)
    if mask.shape[0] >= 3 and mask.shape[1] >= 3:
        eroded[1:-1, 1:-1] = (
            mask[:-2, :-2] & mask[:-2, 1:-1] & mask[:-2, 2:] &
            mask[1:-1, :-2] & mask[1:-1, 1:-1] & mask[1:-1, 2:] &
            mask[2:, :-2] & mask[2:, 1:-1] & mask[2:, 2:]
        )
    return eroded


def build_unreadable_image_qc_record(image_path, error_message):
    """Keep the persisted schema stable for missing/invalid decoded images."""
    return {
        'image_path': pd.NA if pd.isna(image_path) else str(image_path),
        'image_sha256': pd.NA, 'image_readable': False,
        'image_read_error': str(error_message),
        'image_width': pd.NA, 'image_height': pd.NA,
        **{name: np.nan for name in _QC_FLOAT_COLUMNS if name in IMAGE_QC_COLUMNS},
        'image_decode_backend': pd.NA, 'image_qc_backend': pd.NA, 'image_fallback_reason': pd.NA,
    }


def compute_image_qc(image, config, image_path=None, *, array_module=None):
    """Compute technical QC proxies from RGB uint8 pixels on the selected array device.

    The caller explicitly selects CuPy for GPU QC or NumPy for CPU fallback.
    Both use the same equations and preserve input pixels. On CUDA, only one
    vector of scalar results is copied to the host.
    """
    xp = _qc_metric_array_module(array_module)
    parameters = validate_image_qc_config(config)
    if not isinstance(image, xp.ndarray) or image.size == 0:
        return build_unreadable_image_qc_record(image_path, 'invalid_or_empty_image_array')
    if image.ndim != 3 or image.shape[2] != 3 or image.dtype != xp.uint8:
        return build_unreadable_image_qc_record(image_path, 'expected_rgb_uint8_image')
    height, width = image.shape[:2]
    if height < 3 or width < 3:
        return build_unreadable_image_qc_record(image_path, 'empty_or_insufficient_fov_mask')

    mask = build_capsule_fov_mask(
        height, width, parameters['qc_fov_radius_fraction'], array_module=xp)
    inner_mask = _qc_eroded_fov_mask(mask, xp)[1:-1, 1:-1]

    # BT.601, fixed point, round to the nearest uint8 intensity.
    rgb = image.astype(xp.int32)
    gray = ((4899 * rgb[:, :, 0] + 9617 * rgb[:, :, 1] +
             1868 * rgb[:, :, 2] + 8192) >> 14).astype(xp.uint8)
    gray_float = gray.astype(xp.float64)
    value = rgb.max(axis=2)
    color_range = value - rgb.min(axis=2)
    # The 12-bit saturation lookup matches OpenCV's uint8 HSV rounding.
    divisors = xp.arange(256, dtype=xp.float64)
    saturation_divisor = xp.rint((255 * 4096) / xp.maximum(divisors, 1)).astype(xp.int32)
    saturation_divisor[0] = 0
    saturation = ((color_range * saturation_divisor[value] + 2048) >> 12).astype(xp.uint8)

    fov_count = mask.sum(dtype=xp.float64)
    inner_count = inner_mask.sum(dtype=xp.float64)
    fov_denominator = xp.maximum(fov_count, 1.0)
    inner_denominator = xp.maximum(inner_count, 1.0)
    gray_mean = xp.where(mask, gray_float, 0.0).sum() / fov_denominator
    gray_variance = xp.where(mask, (gray_float - gray_mean) ** 2, 0.0).sum() / fov_denominator

    # Four-neighbour Laplacian on interior pixels only: no wrap and no border term.
    laplacian = (gray_float[:-2, 1:-1] + gray_float[2:, 1:-1] +
                 gray_float[1:-1, :-2] + gray_float[1:-1, 2:] -
                 4.0 * gray_float[1:-1, 1:-1])
    laplacian_mean = xp.where(inner_mask, laplacian, 0.0).sum() / inner_denominator
    laplacian_variance = xp.where(
        inner_mask, (laplacian - laplacian_mean) ** 2, 0.0).sum() / inner_denominator
    underexposed = ((gray < parameters['qc_underexposed_pixel_threshold']) & mask).sum() / fov_denominator
    overexposed = ((gray > parameters['qc_overexposed_pixel_threshold']) & mask).sum() / fov_denominator
    specular = (((value > parameters['qc_specular_value_threshold']) &
                 (saturation < parameters['qc_specular_saturation_threshold'])) & mask).sum() / fov_denominator
    metric_vector = xp.stack((fov_count, inner_count, gray_mean / 255.0,
                              xp.sqrt(xp.maximum(gray_variance, 0.0)) / 255.0,
                              laplacian_variance, underexposed, overexposed, specular))
    values = np.asarray(metric_vector) if xp is np else xp.asnumpy(metric_vector)
    if values[0] == 0 or values[1] == 0:
        return build_unreadable_image_qc_record(image_path, 'empty_or_insufficient_fov_mask')
    metric_names = ('brightness_mean', 'contrast_std', 'blur_laplacian',
                    'underexposed_fraction', 'overexposed_fraction', 'specular_fraction')
    return {
        'image_path': pd.NA if pd.isna(image_path) else str(image_path),
        'image_sha256': pd.NA, 'image_readable': True, 'image_read_error': pd.NA,
        'image_width': int(width), 'image_height': int(height),
        **{name: float(value) for name, value in zip(metric_names, values[2:])},
        'image_decode_backend': pd.NA,
        'image_qc_backend': 'numpy_cpu' if xp is np else 'cupy_gpu',
        'image_fallback_reason': pd.NA,
    }


def _qc_string_or_missing(value):
    return pd.NA if pd.isna(value) or not str(value).strip() else str(value).strip()


def _qc_portable_relpath(value):
    normalized = _qc_string_or_missing(value)
    if pd.isna(normalized):
        return pd.NA
    relative = PurePosixPath(normalized)
    if ('\\' in normalized or relative.is_absolute() or '..' in relative.parts
            or normalized in {'.', ''} or relative.as_posix() != normalized):
        raise ValueError(f'Unsafe or noncanonical image_relpath: {value!r}')
    return normalized


def _qc_physical_frame_ids(frame, name):
    """Canonical video/decoded-frame identity, matching current S6 context_frame_id."""
    qc_require_columns(frame, ['video_key', 'opencv_frame_index'], name)
    videos = frame['video_key'].astype('string')
    values = frame['opencv_frame_index']
    indices = pd.to_numeric(values, errors='coerce')
    if (videos.isna().any() or videos.str.strip().eq('').any() or
            (indices.isna() | ~np.isfinite(indices.astype('float64')) | indices.lt(0) | indices.mod(1).ne(0)).any()
            or values.map(lambda value: isinstance(value, (bool, np.bool_))).astype('boolean').any()):
        raise ValueError(f'{name} requires nonempty video keys and nonnegative integer decoded-frame indices.')
    return pd.Series([json.dumps([str(video), int(index)], separators=(',', ':'))
                      for video, index in zip(videos, indices)], index=frame.index, dtype='string')


def _qc_require_pending_split(frame, name):
    qc_require_columns(frame, ['final_split', 'split_assignment_status'], name)
    if frame['final_split'].notna().any() or not frame['split_assignment_status'].eq('pending').fillna(False).all():
        raise ValueError(f'{name} must leave final_split null and split_assignment_status pending.')


def validate_sector7_deferred_split_contract(temporal_manifest, frame_split_manifest, labelled_manifest=None):
    """Recompute current S6 split provenance without excluding any material.

    S4/S5 assignments describe history, never eligibility for QC or training.
    Shared context frames remain valid inputs even across historical splits.
    """
    keys = ['video_key', 'opencv_frame_index']
    required = keys + ['finding_segment_id', 'finding_class_normalized', 'upstream_split', 'is_target',
        'context_frame_id', 'context_frame_upstream_split', 'context_requested_upstream_split_count',
        'context_upstream_split_conflict', 'context_split_provenance_status', 'final_split',
        'split_assignment_status', 'context_image_path', 'context_image_relpath',
        'context_image_source', 'context_annotation_status', 'context_is_verified',
        'context_is_verified_same_finding', 'image_readable']
    qc_require_columns(temporal_manifest, required, 'Current deferred Sector 6 material')
    legacy = {'split', 'context_split_allowed', 'context_split_status', 'context_frame_split',
              'audit_excluded_context_metadata_json'} & set(temporal_manifest)
    if legacy:
        raise ValueError(f'Legacy split-excluded Sector 6 material is incompatible: {sorted(legacy)}')
    _qc_require_pending_split(temporal_manifest, 'Sector 6 material')
    qc_require_columns(frame_split_manifest, keys + ['split'], 'Sector 4 assignments')
    allowed_splits = {'train', 'validation', 'test'}
    for frame, field, name in ((frame_split_manifest, 'split', 'Sector 4'),
                               (temporal_manifest, 'upstream_split', 'Sector 6')):
        _qc_physical_frame_ids(frame, name)
        if not frame[field].isin(allowed_splits).all():
            raise ValueError(f'{name} has unsupported or missing upstream split provenance.')
    if frame_split_manifest.duplicated(keys).any():
        raise ValueError('Sector 4 assignments must be unique per physical frame.')
    for field in ('is_target', 'image_readable', 'context_upstream_split_conflict',
                  'context_is_verified', 'context_is_verified_same_finding'):
        values = temporal_manifest[field]
        if values.isna().any() or not pd.api.types.is_bool_dtype(values.dtype):
            raise ValueError(f'Sector 6 {field} must contain non-null booleans.')
    if not temporal_manifest['context_frame_id'].eq(
            _qc_physical_frame_ids(temporal_manifest, 'Sector 6')).fillna(False).all():
        raise ValueError('Sector 6 context_frame_id disagrees with its physical frame identity.')
    checked = temporal_manifest.merge(frame_split_manifest[keys + ['split']].rename(
        columns={'split': '_authoritative_split'}), on=keys, how='left', validate='many_to_one')
    known = checked['_authoritative_split'].notna()
    same = checked['upstream_split'].eq(checked['_authoritative_split']).fillna(False)
    memberships = checked.groupby(keys, observed=True)['upstream_split'].transform('nunique')
    conflict = (known & ~same) | memberships.gt(1)
    status = pd.Series(np.select(
        [(known & same).to_numpy(dtype=bool), (~known & memberships.eq(1)).to_numpy(dtype=bool),
         known.to_numpy(dtype=bool)],
        ['labelled_same_upstream_split', 'unlabelled_single_upstream_split',
         'labelled_different_upstream_split'], default='unlabelled_multiple_upstream_splits'),
        index=checked.index, dtype='string')
    ownership = checked['context_frame_upstream_split'].fillna('<unlabelled>').eq(
        checked['_authoritative_split'].fillna('<unlabelled>'))
    counts = pd.to_numeric(checked['context_requested_upstream_split_count'], errors='coerce')
    if (not ownership.all() or not counts.eq(memberships).fillna(False).all()
            or not checked['context_upstream_split_conflict'].eq(conflict).all()
            or not checked['context_split_provenance_status'].eq(status).fillna(False).all()):
        raise ValueError('Sector 6 split provenance disagrees with current physical-frame assignments.')
    if (checked['is_target'] & (~known | ~same)).any():
        raise ValueError('Every temporal target must retain its authoritative upstream assignment.')
    if checked['finding_segment_id'].isna().any():
        raise ValueError('Temporal references require finding-segment identities.')
    windows = checked.groupby('finding_segment_id', observed=True)
    if (not windows['is_target'].sum().eq(1).all() or
            windows['upstream_split'].nunique(dropna=False).gt(1).any() or
            windows['video_key'].nunique(dropna=False).gt(1).any()):
        raise ValueError('Every temporal window requires one target and consistent source video/upstream provenance.')
    if not checked['context_is_verified'].eq(known).all():
        raise ValueError('Sector 6 verified-context flags disagree with authoritative labelled frames.')
    if not checked['context_image_source'].isin(['official_labelled_image', 'extracted_from_video',
            'video_extraction_required', 'missing']).all():
        raise ValueError('Sector 6 contains split-excluded or unsupported image-source states.')
    if not checked['context_annotation_status'].isin(['verified_target', 'verified_same_finding',
            'verified_other_finding', 'unlabelled_context']).all():
        raise ValueError('Sector 6 contains split-excluded or unsupported annotation states.')
    if (not checked.loc[known, 'context_image_source'].eq('official_labelled_image').all()
            or checked.loc[known, ['context_image_path', 'context_image_relpath']].isna().any().any()
            or (checked['image_readable'] & checked['context_image_path'].isna()).any()):
        raise ValueError('Sector 6 suppressed a labelled context or marks an unavailable image readable.')
    if 'extraction_status' in checked and not checked['extraction_status'].dropna().isin(['success', 'failed', 'pending']).all():
        raise ValueError('Sector 6 contains unsupported or split-excluded extraction states.')
    extracted = checked['context_image_source'].eq('extracted_from_video')
    unavailable = checked['context_image_source'].isin(['video_extraction_required', 'missing'])
    if checked.loc[unavailable, ['context_image_path', 'context_image_relpath']].notna().any().any():
        raise ValueError('Unavailable Sector 6 context still exposes an active image path.')
    if extracted.any():
        qc_require_columns(checked, ['extracted_image_path', 'extracted_image_relpath', 'extraction_status'],
                           'Sector 6 extracted context')
        if not checked.loc[extracted, 'extraction_status'].eq('success').fillna(False).all():
            raise ValueError('Active extracted context lacks a successful extraction result.')
        for field in ('image_path', 'image_relpath'):
            if not checked.loc[extracted, 'context_' + field].eq(
                    checked.loc[extracted, 'extracted_' + field]).fillna(False).all():
                raise ValueError('Sector 6 active extracted image differs from its extraction record.')
    extracted_fields = [field for field in ('extracted_image_path', 'extracted_image_relpath',
                        'extracted_image_sha256') if field in checked]
    if checked.loc[unavailable, extracted_fields].notna().any().any():
        raise ValueError('Unavailable Sector 6 context still exposes an extracted image.')
    if labelled_manifest is not None:
        qc_require_columns(labelled_manifest, keys + ['split', 'annotation_id', 'finding_class_normalized',
            'image_path', 'image_relpath'], 'Sector 5 labelled annotations')
        _qc_physical_frame_ids(labelled_manifest, 'Sector 5')
        assignment = labelled_manifest[keys + ['split']].drop_duplicates()
        if assignment.duplicated(keys).any():
            raise ValueError('Sector 5 has conflicting physical-frame assignments.')
        comparison = assignment.merge(frame_split_manifest[keys + ['split']], on=keys,
            how='outer', suffixes=('_s5', '_s4'), validate='one_to_one', indicator=True)
        if not comparison['_merge'].eq('both').all() or not comparison['split_s5'].eq(comparison['split_s4']).fillna(False).all():
            raise ValueError('Sector 5 labelled assignments disagree with current Sector 4.')
        ids = labelled_manifest['annotation_id']
        if ids.isna().any() or not ids.is_unique:
            raise ValueError('Sector 5 annotation identities must be unique and non-null.')
        metadata = labelled_manifest.groupby(keys, as_index=False, observed=True).agg(
            _labels=('finding_class_normalized', lambda values: '|'.join(sorted(values.astype(str).unique()))),
            _ids=('annotation_id', lambda values: json.dumps(sorted(values.astype(str)), separators=(',', ':'))),
            _count=('annotation_id', 'size'))
        qc_require_columns(checked, ['context_verified_labels', 'context_verified_annotation_ids_json',
            'context_verified_annotation_count', 'context_official_image_annotation_id',
            'context_official_image_path', 'context_official_image_relpath'], 'Sector 6 retained annotation metadata')
        checked = checked.merge(metadata, on=keys, how='left', validate='many_to_one')
        for actual, expected in [('context_verified_labels', '_labels'),
                                 ('context_verified_annotation_ids_json', '_ids')]:
            if not checked[actual].fillna('<unlabelled>').eq(checked[expected].fillna('<unlabelled>')).all():
                raise ValueError('Sector 6 discarded or changed verified context annotations.')
        if not pd.to_numeric(checked['context_verified_annotation_count'], errors='coerce').fillna(-1).eq(checked['_count'].fillna(-1)).all():
            raise ValueError('Sector 6 verified annotation counts disagree with Sector 5.')
        same_finding = pd.Series([False if pd.isna(labels) else str(finding) in labels.split('|')
            for labels, finding in zip(checked['_labels'], checked['finding_class_normalized'])], index=checked.index)
        if not checked['context_is_verified_same_finding'].eq(same_finding).all():
            raise ValueError('Sector 6 same-finding metadata disagrees with verified annotations.')
        expected_status = np.select([checked['is_target'].to_numpy(dtype=bool),
            same_finding.to_numpy(dtype=bool), known.to_numpy(dtype=bool)],
            ['verified_target', 'verified_same_finding', 'verified_other_finding'], default='unlabelled_context')
        if not checked['context_annotation_status'].eq(expected_status).all():
            raise ValueError('Sector 6 context annotation status disagrees with retained evidence.')
        official = labelled_manifest[['annotation_id'] + keys + ['image_path', 'image_relpath']].rename(
            columns={'annotation_id': 'context_official_image_annotation_id',
                     **{name: '_selected_' + name for name in keys + ['image_path', 'image_relpath']}})
        selected = checked.loc[known].merge(official, on='context_official_image_annotation_id',
            how='left', validate='many_to_one')
        for name in keys:
            if not selected[name].eq(selected['_selected_' + name]).fillna(False).all():
                raise ValueError('Sector 6 selected an official annotation from a different physical frame.')
        for name in ('image_path', 'image_relpath'):
            if not selected['context_official_' + name].eq(selected['_selected_' + name]).fillna(False).all() or not selected['context_' + name].eq(selected['_selected_' + name]).fillna(False).all():
                raise ValueError('Sector 6 selected image paths disagree with the retained official annotation.')
    return True


def build_qc_reference_table(labelled_manifest, temporal_manifest, config):
    """Keep every reference; upstream splits are provenance, never eligibility."""
    root = Path(str(config['storage_root']))
    if not root.is_absolute() or '..' in root.parts:
        raise ValueError('storage_root must be an absolute path without parent traversal.')
    records = []
    specifications = [(labelled_manifest, 'labelled_manifest', 'image_path', 'image_relpath', 'split'),
                      (temporal_manifest, 'temporal_manifest', 'context_image_path', 'context_image_relpath', 'upstream_split')]
    for source, name, path_column, relative_column, split_column in specifications:
        qc_require_columns(source, [path_column, relative_column, split_column], name)
        identities = _qc_physical_frame_ids(source, name)
        if not source[split_column].isin(['train', 'validation', 'test']).all():
            raise ValueError(f'{name} has unsupported upstream split provenance.')
        if name == 'temporal_manifest' or 'final_split' in source or 'split_assignment_status' in source:
            _qc_require_pending_split(source, name)
        if name == 'labelled_manifest' and 'upstream_split' in source and not source['upstream_split'].eq(source['split']).fillna(False).all():
            raise ValueError('Labelled upstream_split differs from its retained Sector 5 split provenance.')
        id_candidates = ['annotation_id', 'image_annotation_id'] if name == 'labelled_manifest' else ['finding_segment_id']
        id_column = next((column for column in id_candidates if column in source), None)
        read_columns = [path_column, relative_column, split_column, 'video_key', 'opencv_frame_index']
        read_columns += [column for column in (id_column, 'context_image_source', 'extraction_status')
                         if column is not None and column in source and column not in read_columns]
        for position, row in enumerate(source[read_columns].to_dict('records')):
            path = _qc_string_or_missing(row[path_column])
            relative = _qc_portable_relpath(row[relative_column])
            upstream_split = _qc_string_or_missing(row[split_column])
            if pd.notna(path):
                supplied_path = Path(path)
                if not supplied_path.is_absolute() or '..' in supplied_path.parts:
                    raise ValueError(f'{name} has an unsafe absolute image path: {path!r}')
                try:
                    inferred_relative = supplied_path.relative_to(root).as_posix()
                except ValueError:
                    raise ValueError(f'{name} image lies outside storage_root: {path}') from None
                if pd.notna(relative) and relative != inferred_relative:
                    raise ValueError(f'{name} image_path disagrees with image_relpath: {path}')
                relative = _qc_portable_relpath(inferred_relative)
            status = 'referenced_path' if pd.notna(path) else 'missing_image_path'
            if name == 'temporal_manifest':
                image_source = str(row.get('context_image_source', ''))
                extraction_status = str(row.get('extraction_status', ''))
                if 'excluded' in image_source or 'blocked' in extraction_status:
                    raise ValueError('QC cannot consume legacy split-excluded context material.')
                if pd.isna(path) and (image_source == 'video_extraction_required' or
                        extraction_status in {'not_requested', 'pending', 'not_run'}):
                    status = 'pending_context_image'
            records.append({
                'source_manifest': name, 'source_row': position,
                'source_reference_id': row[id_column] if id_column else pd.NA,
                'image_path': path, 'image_relpath': relative,
                'physical_frame_id': identities.iloc[position], 'video_key': row['video_key'],
                'opencv_frame_index': int(row['opencv_frame_index']), 'upstream_split': upstream_split,
                'final_split': pd.NA, 'split_assignment_status': 'pending', 'reference_status': status,
            })
    return qc_typed_table(pd.DataFrame.from_records(records, columns=QC_REFERENCE_COLUMNS))

def build_qc_image_inventory(labelled_manifest, temporal_manifest, config):
    """One QC row per physical image file, irrespective of historical split reuse."""
    references = build_qc_reference_table(labelled_manifest, temporal_manifest, config)
    available = references.loc[references['image_path'].notna()].copy()
    if available.empty:
        return qc_empty_table(IMAGE_QC_INVENTORY_COLUMNS)
    for key, values in [('image_relpath', ['image_path', 'physical_frame_id']),
                        ('image_path', ['image_relpath', 'physical_frame_id'])]:
        if available.groupby(key, observed=True)[values].nunique(dropna=False).gt(1).any().any():
            raise ValueError('One image file maps to conflicting paths or physical-frame identities.')
    result = available.assign(
        used_by_labelled_manifest=available['source_manifest'].eq('labelled_manifest'),
        used_by_temporal_manifest=available['source_manifest'].eq('temporal_manifest'),
    ).groupby('image_relpath', as_index=False, observed=True, sort=True).agg(
        image_path=('image_path', 'first'), physical_frame_id=('physical_frame_id', 'first'),
        video_key=('video_key', 'first'), opencv_frame_index=('opencv_frame_index', 'first'),
        upstream_splits_json=('upstream_split', lambda values: json.dumps(sorted(values.astype(str).unique()), separators=(',', ':'))),
        upstream_split_count=('upstream_split', 'nunique'),
        used_by_labelled_manifest=('used_by_labelled_manifest', 'max'),
        used_by_temporal_manifest=('used_by_temporal_manifest', 'max'))
    result['final_split'] = pd.Series(pd.NA, index=result.index, dtype='string')
    result['split_assignment_status'] = 'pending'
    return qc_typed_table(result[IMAGE_QC_INVENTORY_COLUMNS])

# Prefer pure NVIDIA device decoding, then NVIDIA hybrid, then OpenCV CPU.
S7_GPU_BACKENDS = ('HW_GPU_ONLY', 'GPU_ONLY')
S7_HYBRID_BACKENDS = ('HYBRID_CPU_GPU',)
S7_GPU_PROBE_JPEG_BASE64 = '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAAgACADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwBlFFFABRRRQAUUUUAFFFFAH//Z'


def io_warn_sector7_fallback_once(runtime, reason):
    """One shared UserWarning per execution; retain every reason for provenance."""
    runtime.setdefault('fallback_reasons', set()).add(str(reason))
    if not runtime.get('warning_emitted', False):
        runtime['warning_emitted'] = True
        warnings.warn(
            'Sector 7: GPU-preferred processing is using CPU or NVIDIA hybrid fallback '
            f'({reason}). Processing continues, including PNG images. '
            'Backend counts and detailed reasons are saved in the QC outputs; '
            'no further fallback warnings will be emitted in this run.',
            UserWarning, stacklevel=2)


def io_describe_sector7_gpu(config):
    """Describe optional CUDA availability without decoding or allocating pixels."""
    parameters = validate_image_qc_config(config)
    info = {'device_id': parameters['qc_gpu_id'], 'device_name': 'unavailable',
            'cuda_available': False, 'nvimagecodec_available': nvimgcodec is not None,
            'decoder': 'nvimagecodec/nvjpeg with OpenCV fallback',
            'backends': list(S7_GPU_BACKENDS), 'hybrid_backends': list(S7_HYBRID_BACKENDS),
            'sample_format': 'I_RGB', 'apply_exif_orientation': False,
            'cpu_decode_fallback': True, 'pixel_processing': 'cupy preferred; numpy fallback',
            'unavailable_reason': None}
    if cp is None:
        info['unavailable_reason'] = 'cupy_unavailable'
        return info
    try:
        count = cp.cuda.runtime.getDeviceCount()
        if parameters['qc_gpu_id'] >= count:
            info['unavailable_reason'] = 'selected_cuda_device_unavailable'
            return info
        with cp.cuda.Device(parameters['qc_gpu_id']):
            properties = cp.cuda.runtime.getDeviceProperties(parameters['qc_gpu_id'])
            name = properties['name']
            info.update({'cuda_available': True,
                'device_name': name.decode('utf-8', errors='replace') if isinstance(name, bytes) else str(name),
                'compute_capability': [int(properties['major']), int(properties['minor'])],
                'cuda_runtime_version': int(cp.cuda.runtime.runtimeGetVersion()),
                'cuda_driver_version': int(cp.cuda.runtime.driverGetVersion())})
    except Exception as error:
        info['unavailable_reason'] = f'cuda_initialization_failed:{type(error).__name__}'
    return info


def io_require_sector7_cuda_image(image, device_id):
    """Verify decoder device output before wrapping it; callers can retry on CPU."""
    if image is None:
        raise RuntimeError('NVIDIA GPU decoder returned no image.')
    if image.buffer_kind != nvimgcodec.ImageBufferKind.STRIDED_DEVICE:
        raise RuntimeError('NVIDIA decoder returned host pixels.')
    if int(image.device_id) != int(device_id):
        raise RuntimeError('NVIDIA decoder returned pixels on the wrong CUDA device.')
    interface = getattr(image, '__cuda_array_interface__', None)
    if not isinstance(interface, dict) or not interface.get('data', (0,))[0]:
        raise RuntimeError('Decoded image has no valid CUDA array interface.')
    array = cp.asarray(image)
    if not isinstance(array, cp.ndarray) or int(array.device.id) != int(device_id):
        raise RuntimeError('Decoded pixels could not be wrapped on the selected NVIDIA device.')
    if array.ndim != 3 or array.shape[2] != 3 or array.dtype != cp.uint8:
        raise RuntimeError('NVIDIA decoder must return an interleaved RGB uint8 image.')
    return array


def io_probe_sector7_decoder(runtime, backends):
    """Probe a selected NVIDIA backend without turning capability failures fatal."""
    with cp.cuda.Device(runtime['device_id']), runtime['stream'], warnings.catch_warnings():
        warnings.simplefilter('ignore')  # One pipeline warning owns fallback reporting.
        decoder = nvimgcodec.Decoder(device_id=runtime['device_id'],
            max_num_cpu_threads=runtime['workers'],
            backends=[nvimgcodec.Backend(getattr(nvimgcodec.BackendKind, name)) for name in backends])
        payload = base64.b64decode(S7_GPU_PROBE_JPEG_BASE64)
        code_stream = nvimgcodec.CodeStream(payload)
        owners = None
        try:
            owners = decoder.decode([code_stream], params=runtime['params'], cuda_stream=runtime['stream'].ptr)
            if not isinstance(owners, (list, tuple)) or len(owners) != 1:
                raise RuntimeError('Unexpected NVIDIA JPEG probe result.')
            probe = io_require_sector7_cuda_image(owners[0], runtime['device_id'])
            if tuple(probe.shape) != (32, 32, 3):
                raise RuntimeError('Unexpected baseline JPEG probe dimensions.')
        finally:
            runtime['stream'].synchronize()
    return decoder


def io_get_sector7_hybrid_decoder(runtime):
    """Lazily try GPU-assisted nvJPEG once; all failures remain fallback reasons."""
    if runtime.get('hybrid_attempted', False):
        return runtime.get('hybrid_decoder')
    runtime['hybrid_attempted'] = True
    if not runtime['gpu_metrics_available'] or nvimgcodec is None:
        return None
    try:
        runtime['hybrid_decoder'] = io_probe_sector7_decoder(runtime, S7_HYBRID_BACKENDS)
    except Exception as error:
        runtime['fallback_reasons'].add(f'nvidia_hybrid_unavailable:{type(error).__name__}')
    return runtime.get('hybrid_decoder')


def io_create_sector7_gpu_runtime(config, gpu_info=None):
    """GPU first; missing SDKs, unsupported hardware and CUDA errors permit CPU."""
    parameters = validate_image_qc_config(config)
    info = io_describe_sector7_gpu(config) if gpu_info is None else copy.deepcopy(gpu_info)
    runtime = {'decoder': None, 'device_id': parameters['qc_gpu_id'], 'stream': None,
               'params': None, 'gpu_info': info, 'probe_passed': False,
               'decoder_mode': 'cpu', 'gpu_metrics_available': False,
               'hybrid_decoder': None, 'hybrid_attempted': False,
               'workers': parameters['qc_workers'], 'warning_emitted': False,
               'fallback_reasons': set()}
    if info['device_id'] != runtime['device_id']:
        raise ValueError('GPU environment disagrees with qc_gpu_id.')
    reason = info.get('unavailable_reason') or 'cuda_unavailable'
    if cp is not None and info.get('cuda_available', False):
        try:
            with cp.cuda.Device(runtime['device_id']), warnings.catch_warnings():
                warnings.simplefilter('ignore')
                runtime['stream'] = cp.cuda.Stream(non_blocking=True)
                with runtime['stream']:
                    try:
                        probe = cp.asarray(np.zeros((1,), dtype=np.uint8))
                        if not isinstance(probe, cp.ndarray) or int(probe.device.id) != runtime['device_id']:
                            raise RuntimeError('CUDA allocation used the wrong device.')
                        cp.asnumpy(probe + 1)  # Prove a small kernel + host scalar transfer.
                    finally:
                        runtime['stream'].synchronize()
                runtime['gpu_metrics_available'] = True
        except Exception as error:
            reason = f'cuda_metrics_unavailable:{type(error).__name__}'
    if runtime['gpu_metrics_available'] and nvimgcodec is not None:
        try:
            runtime['params'] = nvimgcodec.DecodeParams(color_spec=nvimgcodec.ColorSpec.SRGB,
                sample_format=nvimgcodec.SampleFormat.I_RGB, apply_exif_orientation=False)
            runtime['decoder'] = io_probe_sector7_decoder(runtime, S7_GPU_BACKENDS)
            runtime.update({'decoder_mode': 'gpu', 'probe_passed': True})
            return runtime
        except Exception as error:
            reason = f'nvidia_gpu_decoder_unavailable:{type(error).__name__}'
            runtime['fallback_reasons'].add(reason)
        hybrid = io_get_sector7_hybrid_decoder(runtime)
        if hybrid is not None:
            runtime.update({'decoder': hybrid, 'decoder_mode': 'nvjpeg_hybrid', 'probe_passed': True})
            io_warn_sector7_fallback_once(runtime, 'nvidia_hybrid_cpu_gpu_decode')
            return runtime
    elif runtime['gpu_metrics_available']:
        reason = 'nvimagecodec_unavailable'
    io_warn_sector7_fallback_once(runtime, reason)
    return runtime


def io_read_sector7_image_snapshot(image_path):
    """Read encoded bytes once; hash precisely the bytes passed to each decoder."""
    if pd.isna(image_path) or not str(image_path).strip():
        return {'record': build_unreadable_image_qc_record(image_path, 'missing_image_path'), 'payload': None}
    path = Path(str(image_path))
    if path.is_symlink():
        return {'record': build_unreadable_image_qc_record(image_path, 'image_symlink_not_supported'), 'payload': None}
    try:
        payload = path.read_bytes()
    except FileNotFoundError:
        return {'record': build_unreadable_image_qc_record(image_path, 'image_file_not_found'), 'payload': None}
    except OSError as error:
        return {'record': build_unreadable_image_qc_record(image_path, f'{type(error).__name__}: {error}'), 'payload': None}
    return {'record': {**build_unreadable_image_qc_record(image_path, 'decode_pending'),
                       'image_sha256': hashlib.sha256(payload).hexdigest()}, 'payload': payload}


def io_quiet_sector7_opencv():
    """Mute repetitive native decoder logs locally; failure rows retain diagnostics."""
    logger = cv2 if hasattr(cv2, 'setLogLevel') else getattr(getattr(cv2, 'utils', None), 'logging', None)
    previous = None
    if logger is not None and hasattr(logger, 'getLogLevel'):
        previous = logger.getLogLevel()
        logger.setLogLevel(0)
    try:
        yield
    finally:
        if previous is not None:
            logger.setLogLevel(previous)


def io_compute_sector7_cpu_snapshot(snapshot, config, runtime, reason):
    """Decode PNG/JPEG/other supported formats on CPU; prefer CUDA for QC."""
    original = snapshot['record']
    io_warn_sector7_fallback_once(runtime, reason)
    failure = {**original, 'image_decode_backend': 'opencv_cpu',
               'image_qc_backend': pd.NA, 'image_fallback_reason': str(reason)}
    try:
        with contextmanager(io_quiet_sector7_opencv)():
            bgr = cv2.imdecode(np.frombuffer(snapshot['payload'], dtype=np.uint8),
                               cv2.IMREAD_COLOR | cv2.IMREAD_IGNORE_ORIENTATION)
        if bgr is None or bgr.size == 0:
            return {**failure, 'image_read_error': 'opencv_decode_failed'}
        rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)
    except Exception as error:
        return {**failure, 'image_read_error': f'opencv_decode_error:{type(error).__name__}'}
    if runtime['gpu_metrics_available']:
        try:
            with cp.cuda.Device(runtime['device_id']), runtime['stream'], warnings.catch_warnings():
                warnings.simplefilter('ignore')
                try:
                    image = cp.asarray(rgb)
                    record = compute_image_qc(image, config, original['image_path'], array_module=cp)
                finally:
                    runtime['stream'].synchronize()
            return {**record, 'image_sha256': original['image_sha256'],
                    'image_decode_backend': 'opencv_cpu', 'image_qc_backend': 'cupy_gpu',
                    'image_fallback_reason': str(reason)}
        except Exception as error:
            runtime['gpu_metrics_available'] = False
            reason = f'{reason};cuda_qc_failed:{type(error).__name__}'
            io_warn_sector7_fallback_once(runtime, reason)
    record = compute_image_qc(rgb, config, original['image_path'], array_module=np)
    return {**record, 'image_sha256': original['image_sha256'],
            'image_decode_backend': 'opencv_cpu', 'image_qc_backend': 'numpy_cpu',
            'image_fallback_reason': str(reason)}


def io_try_sector7_nvidia_batch(snapshots, positions, config, runtime, decoder, backend):
    """Return successful metrics and reasons for retry, keeping all buffers alive."""
    records, failed, code_streams, submitted = {}, {}, [], []
    if not positions:
        return records, failed
    for position in positions:
        try:
            code_stream = nvimgcodec.CodeStream(snapshots[position]['payload'])
            if str(code_stream.codec_name).lower() != 'jpeg':
                raise ValueError('not_jpeg')
            code_streams.append(code_stream)
            submitted.append(position)
        except Exception as error:
            failed[position] = f'nvidia_header_failed:{type(error).__name__}'
    if not submitted:
        return records, failed
    owners = None
    try:
        with cp.cuda.Device(runtime['device_id']), runtime['stream'], warnings.catch_warnings():
            warnings.simplefilter('ignore')
            try:
                owners = decoder.decode(code_streams, params=runtime['params'], cuda_stream=runtime['stream'].ptr)
                if not isinstance(owners, (list, tuple)) or len(owners) != len(submitted):
                    raise RuntimeError('NVIDIA decoder result count mismatch.')
                for position, owner in zip(submitted, owners):
                    try:
                        image = io_require_sector7_cuda_image(owner, runtime['device_id'])
                        record = compute_image_qc(image, config, snapshots[position]['record']['image_path'], array_module=cp)
                        hybrid_reason = 'nvidia_hybrid_cpu_gpu_decode' if backend == 'nvidia_hybrid' else pd.NA
                        records[position] = {**record,
                            'image_sha256': snapshots[position]['record']['image_sha256'],
                            'image_decode_backend': backend, 'image_qc_backend': 'cupy_gpu',
                            'image_fallback_reason': hybrid_reason}
                    except Exception as error:
                        failed[position] = f'{backend}_decode_or_qc_failed:{type(error).__name__}'
            finally:
                runtime['stream'].synchronize()
    except Exception as error:
        records.clear()
        failed.update({position: f'{backend}_batch_failed:{type(error).__name__}' for position in submitted})
    if backend == 'nvidia_hybrid' and records:
        io_warn_sector7_fallback_once(runtime, 'nvidia_hybrid_cpu_gpu_decode')
    return records, failed


def io_compute_sector7_gpu_batch(snapshots, config, runtime):
    """Preserve every image: NVIDIA JPEG first, hybrid retry, CPU decode fallback."""
    if runtime['device_id'] != validate_image_qc_config(config)['qc_gpu_id']:
        raise ValueError('GPU runtime disagrees with qc_gpu_id.')
    records = [copy.copy(snapshot['record']) for snapshot in snapshots]
    reasons, eligible = {}, []
    for position, snapshot in enumerate(snapshots):
        payload = snapshot['payload']
        if payload is None:
            continue
        if not payload:
            records[position]['image_read_error'] = 'empty_encoded_image'
            continue
        if payload.startswith(b'\xff\xd8\xff'):
            eligible.append(position)
        else:
            reasons[position] = ('png_cpu_decode' if payload.startswith(b'\x89PNG\r\n\x1a\n')
                                 else 'format_cpu_decode')
    if runtime.get('decoder') is not None and runtime['gpu_metrics_available']:
        backend = 'nvidia_hybrid' if runtime['decoder_mode'] == 'nvjpeg_hybrid' else 'nvidia_gpu'
        successes, failed = io_try_sector7_nvidia_batch(snapshots, eligible, config, runtime, runtime['decoder'], backend)
        for position, record in successes.items():
            records[position] = record
        if failed and backend == 'nvidia_gpu':
            hybrid = io_get_sector7_hybrid_decoder(runtime)
            if hybrid is not None:
                retried, still_failed = io_try_sector7_nvidia_batch(snapshots, list(failed), config, runtime, hybrid, 'nvidia_hybrid')
                for position, record in retried.items():
                    records[position] = record
                failed = still_failed
        reasons.update(failed)
    else:
        reasons.update({position: 'nvidia_decoder_unavailable' for position in eligible})
    for position, reason in reasons.items():
        records[position] = io_compute_sector7_cpu_snapshot(snapshots[position], config, runtime, reason)
    return records


def io_compute_image_qc(image_path, config, runtime=None):
    """Compatibility wrapper with the same NVIDIA-first/CPU-fallback routing."""
    execution = io_create_sector7_gpu_runtime(config) if runtime is None else runtime
    return io_compute_sector7_gpu_batch([io_read_sector7_image_snapshot(image_path)], config, execution)[0]


def io_compute_qc_for_image_inventory(image_inventory, config, runtime=None):
    """Bounded reads and batches; neither formats nor unavailable CUDA exclude rows."""
    parameters = validate_image_qc_config(config)
    qc_require_columns(image_inventory, IMAGE_QC_INVENTORY_COLUMNS, 'QC inventory')
    if not image_inventory['image_relpath'].is_unique or not image_inventory['image_path'].is_unique:
        raise ValueError('QC inventory identities and paths must be unique.')
    columns = IMAGE_QC_INVENTORY_COLUMNS + [name for name in IMAGE_QC_COLUMNS if name != 'image_path']
    if image_inventory.empty:
        return qc_empty_table(columns)
    execution = io_create_sector7_gpu_runtime(config) if runtime is None else runtime
    paths, records = image_inventory['image_path'].tolist(), []
    with ThreadPoolExecutor(max_workers=parameters['qc_workers']) as executor:
        for start in tqdm(range(0, len(paths), parameters['qc_decode_batch_size']), desc='GPU-preferred image QC batches'):
            snapshots = list(executor.map(io_read_sector7_image_snapshot,
                paths[start:start + parameters['qc_decode_batch_size']]))
            records.extend(io_compute_sector7_gpu_batch(snapshots, config, execution))
    metrics = qc_typed_table(pd.DataFrame.from_records(records, columns=IMAGE_QC_COLUMNS))
    result = image_inventory.merge(metrics, on='image_path', how='left', sort=False, validate='one_to_one')
    return qc_typed_table(result[columns])


def derive_image_qc_thresholds(image_qc_manifest, config):
    """Defer statistical fitting until validated final training assignments exist.

    Historical upstream labels and the future evaluation pool never calibrate
    thresholds here. Pixel metrics remain available for later train-only fitting.
    """
    validate_image_qc_config(config)
    qc_require_columns(image_qc_manifest, ['image_readable', 'image_relpath',
        'brightness_mean', 'contrast_std', 'blur_laplacian'], 'QC metric manifest')
    _qc_require_pending_split(image_qc_manifest, 'QC metric manifest')
    if not image_qc_manifest['image_relpath'].is_unique:
        raise ValueError('QC metrics require one row per image-file identity.')
    readable = image_qc_manifest['image_readable'].fillna(False).astype(bool)
    metrics = image_qc_manifest.loc[readable, ['brightness_mean', 'contrast_std', 'blur_laplacian']].apply(
        pd.to_numeric, errors='coerce')
    if (metrics.isna().any(axis=1) | ~np.isfinite(metrics.astype('float64')).all(axis=1)).any():
        raise RuntimeError('Readable images have missing or non-finite QC metrics.')
    record = {name: np.nan for name in IMAGE_QC_THRESHOLD_COLUMNS[:4]}
    record.update({
        'threshold_calibration_status': 'deferred_final_split_pending', 'threshold_fit_split': 'deferred',
        'calibration_candidate_images': 0, 'calibration_readable_images': 0,
        'total_readable_images': int(readable.sum()),
    })
    return qc_typed_table(pd.DataFrame.from_records([record], columns=IMAGE_QC_THRESHOLD_COLUMNS))

def add_image_qc_flags(image_qc_manifest, image_qc_thresholds):
    """Readable means technically decodable; no pending material is training-ready."""
    qc_require_columns(image_qc_thresholds, IMAGE_QC_THRESHOLD_COLUMNS, 'QC thresholds')
    _qc_require_pending_split(image_qc_manifest, 'QC metric manifest')
    if len(image_qc_thresholds) != 1:
        raise ValueError('Image QC thresholds must contain exactly one status row.')
    threshold = image_qc_thresholds.iloc[0]
    if (threshold['threshold_calibration_status'] != 'deferred_final_split_pending'
            or threshold['threshold_fit_split'] != 'deferred'
            or threshold[IMAGE_QC_THRESHOLD_COLUMNS[:4]].notna().any()
            or threshold['calibration_candidate_images'] != 0
            or threshold['calibration_readable_images'] != 0):
        raise ValueError('Sector 7 cannot consume fitted thresholds while final split assignment is pending.')
    readable = image_qc_manifest['image_readable'].fillna(False).astype(bool)
    result = image_qc_manifest.copy()
    for flag in ('qc_blur_outlier', 'qc_contrast_outlier', 'qc_low_brightness_outlier', 'qc_high_brightness_outlier'):
        result[flag] = pd.Series(pd.NA, index=result.index, dtype='boolean')
    result['qc_thresholds_calibrated'] = False
    result['qc_requires_review'] = ~readable
    result['image_technically_usable'] = readable
    result['training_ready'] = False
    result['image_usable_for_modelling'] = False
    result['qc_assessment_status'] = 'metrics_only_final_split_pending'
    return qc_typed_table(result[IMAGE_QC_MANIFEST_COLUMNS].sort_values('image_relpath', kind='stable'))

def build_image_read_failure_report(image_qc_manifest):
    qc_require_columns(image_qc_manifest, IMAGE_READ_FAILURE_REPORT_COLUMNS + ['image_readable'], 'QC manifest')
    return qc_typed_table(image_qc_manifest.loc[
        ~image_qc_manifest['image_readable'].fillna(False), IMAGE_READ_FAILURE_REPORT_COLUMNS
    ].sort_values('image_relpath', kind='stable'))


def build_qc_reference_reports(labelled_manifest, temporal_manifest, image_qc_manifest, config):
    """Report missing reference rows separately from unreadable physical files."""
    references = build_qc_reference_table(labelled_manifest, temporal_manifest, config)
    missing = qc_typed_table(references.loc[references['image_path'].isna(), QC_REFERENCE_COLUMNS])
    metrics = image_qc_manifest[['image_relpath', 'image_readable', 'qc_requires_review']].copy()
    metrics['_qc_found'] = True
    joined = references.merge(metrics, on='image_relpath', how='left', validate='many_to_one')
    records = []
    for source in ('labelled_manifest', 'temporal_manifest'):
        rows = joined.loc[joined['source_manifest'].eq(source)]
        has_path = rows['image_path'].notna()
        covered = has_path & rows['_qc_found'].astype('boolean').fillna(False).astype(bool)
        records.append({
            'source_manifest': source, 'total_references': len(rows),
            'referenced_paths': int(has_path.sum()),
            'missing_path_references': int((~has_path).sum()),
            'pending_path_references': int(rows['reference_status'].eq('pending_context_image').sum()),
            'qc_covered_references': int(covered.sum()),
            'readable_references': int((covered & rows['image_readable'].fillna(False)).sum()),
            'review_required_references': int((~covered | rows['qc_requires_review'].fillna(True)).sum()),
        })
    covered = joined['image_path'].notna() & joined['_qc_found'].astype('boolean').fillna(False).astype(bool)
    joined['qc_reference_covered'] = covered
    joined['image_readable'] = covered & joined['image_readable'].fillna(False)
    joined['qc_requires_review'] = ~covered | joined['qc_requires_review'].fillna(True)
    reference_report = qc_typed_table(joined[QC_REFERENCE_COLUMNS + [
        'qc_reference_covered', 'image_readable', 'qc_requires_review']])
    return {
        'missing_image_reference_report': missing,
        'image_read_failure_report': build_image_read_failure_report(image_qc_manifest),
        'qc_reference_report': reference_report,
        'qc_reference_coverage_report': qc_typed_table(pd.DataFrame.from_records(
            records, columns=QC_REFERENCE_COVERAGE_COLUMNS)),
    }


def attach_image_qc_to_manifests(labelled_manifest, temporal_manifest, image_qc_manifest, config):
    """Many-to-one enrichment retains every annotation, box and context row.

    Metric columns receive a qc_ prefix so Sector 6 image audit fields survive.
    Original paths, annotations, and upstream provenance are kept. New final
    assignment fields remain pending; technical readability never permits training.
    """
    references = build_qc_reference_table(labelled_manifest, temporal_manifest, config)
    metric_columns = [name for name in IMAGE_QC_COLUMNS if name != 'image_path']
    added_columns = {name: 'qc_' + name for name in metric_columns}
    extra_columns = [name for name in image_qc_manifest
                     if name.startswith('qc_') and name not in IMAGE_QC_FLAG_COLUMNS
                     and name not in added_columns.values()]
    attached = image_qc_manifest[['image_relpath'] + metric_columns + IMAGE_QC_FLAG_COLUMNS + extra_columns].rename(columns=added_columns)
    for name in added_columns.values():
        if name in image_qc_manifest and name != 'image_relpath':
            attached[name] = image_qc_manifest[name].array
    if attached['image_relpath'].isna().any() or not attached['image_relpath'].is_unique:
        raise ValueError('QC enrichment requires unique non-null image identities.')
    outputs = {}
    for source, name in [(labelled_manifest, 'labelled_manifest'), (temporal_manifest, 'temporal_manifest')]:
        reserved = set(attached.columns) - {'image_relpath'}
        collisions = sorted(reserved.intersection(source.columns))
        if collisions:
            raise ValueError(f'{name} already contains Sector 7 columns: {collisions}')
        own_references = references.loc[references['source_manifest'].eq(name)]
        result = source.copy()
        result['_qc_source_position'] = np.arange(len(source))
        result['_qc_join_relpath'] = pd.Series(own_references['image_relpath'].array, index=result.index)
        result['_qc_source_has_path'] = pd.Series(own_references['image_path'].notna().to_numpy(), index=result.index)
        lookup = attached.rename(columns={'image_relpath': '_qc_join_relpath'})
        lookup['qc_reference_covered'] = True
        result = result.merge(lookup, on='_qc_join_relpath', how='left', sort=False, validate='many_to_one')
        covered = result['_qc_source_has_path'] & result['qc_reference_covered'].astype('boolean').fillna(False).astype(bool)
        result['qc_reference_covered'] = covered.astype('boolean')
        quantile_flags = {'qc_blur_outlier', 'qc_contrast_outlier',
                          'qc_low_brightness_outlier', 'qc_high_brightness_outlier'}
        for flag in IMAGE_QC_FLAG_COLUMNS:
            result[flag] = result[flag].astype('boolean')
            if flag not in quantile_flags:
                default = flag == 'qc_requires_review'
                result[flag] = result[flag].fillna(default)
                if flag in {'qc_requires_review', 'image_technically_usable'}:
                    result.loc[~covered, flag] = default
        result['training_ready'] = pd.Series(False, index=result.index, dtype='boolean')
        result['image_usable_for_modelling'] = pd.Series(False, index=result.index, dtype='boolean')
        result['qc_assessment_status'] = pd.Series('metrics_only_final_split_pending', index=result.index, dtype='string')
        if 'upstream_split' not in result:
            result['upstream_split'] = source['split'].reset_index(drop=True).astype('string')
        if 'final_split' not in result:
            result['final_split'] = pd.Series(pd.NA, index=result.index, dtype='string')
        if 'split_assignment_status' not in result:
            result['split_assignment_status'] = pd.Series('pending', index=result.index, dtype='string')
        _qc_require_pending_split(result, name)
        result['qc_image_readable'] = result['qc_image_readable'].astype('boolean').fillna(False)
        result.loc[~covered, 'qc_image_readable'] = False
        result = result.sort_values('_qc_source_position', kind='stable').drop(
            columns=['_qc_source_position', '_qc_join_relpath', '_qc_source_has_path']).reset_index(drop=True)
        if len(result) != len(source) or list(result.columns[:len(source.columns)]) != list(source.columns):
            raise RuntimeError('QC enrichment changed source manifest cardinality or original schema order.')
        outputs['labelled_frame_manifest_with_qc' if name == 'labelled_manifest' else 'temporal_manifest_with_qc'] = result
    return outputs


def build_image_qc_summary(image_qc_manifest, image_qc_thresholds, reports, config):
    row = image_qc_thresholds.iloc[0]
    readable = image_qc_manifest['image_readable'].fillna(False)
    record = {
        'qc_status': 'completed' if config.get('qc_enabled', True) else 'disabled',
        'total_unique_images': len(image_qc_manifest), 'readable_images': int(readable.sum()),
        'unreadable_images': int((~readable).sum()),
        'review_required_images': int(image_qc_manifest['qc_requires_review'].fillna(False).sum()),
        'technically_usable_images': int(image_qc_manifest['image_technically_usable'].fillna(False).sum()),
        'model_usable_images': 0, 'training_ready': False, 'split_assignment_status': 'pending',
        'qc_assessment_status': 'metrics_only_final_split_pending',
        'nvidia_gpu_decoded_images': int(image_qc_manifest['image_decode_backend'].eq('nvidia_gpu').sum()),
        'nvidia_hybrid_decoded_images': int(image_qc_manifest['image_decode_backend'].eq('nvidia_hybrid').sum()),
        'cpu_decoded_images': int((readable & image_qc_manifest['image_decode_backend'].eq('opencv_cpu')).sum()),
        'gpu_qc_images': int((readable & image_qc_manifest['image_qc_backend'].eq('cupy_gpu')).sum()),
        'cpu_qc_images': int((readable & image_qc_manifest['image_qc_backend'].eq('numpy_cpu')).sum()),
        'fallback_images': int(image_qc_manifest['image_fallback_reason'].notna().sum()),
        **{name: row[name] for name in [
            'threshold_calibration_status', 'threshold_fit_split',
            'calibration_candidate_images', 'calibration_readable_images']},
    }
    return qc_typed_table(pd.DataFrame.from_records([record], columns=QC_SUMMARY_COLUMNS))

## 5. Verified persistence, recovery and optional publication

S7 schema 3 catalogs bind the deferred execution contract, configuration, lineage, typed tables, summary and file SHA-256 values. Old schema 2 results are incompatible caches and are recomputed.

A durable transaction journal protects updates. On retry, an interrupted incomplete installation is rolled back before cache inspection; a completely installed and verified new catalog is accepted. Invalid S7 caches are replaced only after validated recomputation, with replaced files retained in a recovery backup. Upstream or image-integrity failures are not treated as disposable-cache failures.

Before publication, check the selected S7 bundle and compare consumed upstream metadata with current GitHub `main`. An unrelated main commit is allowed; changed consumed inputs stop publication. Image binaries, sidecars and local QC checkpoints are not committed.

In [29]:
def _s5_core_code_value(code):
    """Describe executable code without filenames, source lines or debug positions."""
    fields = (
        "co_argcount", "co_posonlyargcount", "co_kwonlyargcount", "co_nlocals",
        "co_stacksize", "co_flags", "co_code", "co_consts", "co_names", "co_varnames",
        "co_name", "co_qualname", "co_cellvars", "co_freevars", "co_exceptiontable",
    )
    return {field: _s5_core_value(getattr(code, field)) for field in fields if hasattr(code, field)}

def _s5_core_value(value, active=None):
    """Canonicalize scalar/container code values and defaults without changing them."""
    if isinstance(value, CodeType):
        return {"code": _s5_core_code_value(value)}
    if value is Ellipsis:
        return {"ellipsis": True}
    if value is None or isinstance(value, (str, bool, int)):
        return value
    if isinstance(value, float):
        return {"float": value.hex()} if math.isfinite(value) else {"float": repr(value)}
    if isinstance(value, complex):
        return {"complex": [_s5_core_value(value.real), _s5_core_value(value.imag)]}
    if isinstance(value, bytes):
        return {"bytes": value.hex()}
    if not isinstance(value, (dict, list, tuple, set, frozenset)):
        raise TypeError(f"Unsupported active core identity value: {type(value).__name__}")
    active = set() if active is None else active
    identity = id(value)
    if identity in active:
        raise ValueError("Cyclic containers cannot define a deterministic core identity.")
    nested = active | {identity}
    if isinstance(value, dict):
        pairs = [[_s5_core_value(key, nested), _s5_core_value(item, nested)] for key, item in value.items()]
        return {"dict": sorted(pairs, key=lambda pair: _s5_core_identity_json(pair[0]))}
    items = [_s5_core_value(item, nested) for item in value]
    if isinstance(value, (set, frozenset)):
        items = sorted(items, key=_s5_core_identity_json)
    return {type(value).__name__: items}

def _s5_core_identity_json(value):
    return json.dumps(value, sort_keys=True, ensure_ascii=False, separators=(",", ":"), allow_nan=False)

def _s5_core_referenced_names(code):
    """Include globals referenced inside comprehensions and other nested code."""
    children = (item for item in code.co_consts if isinstance(item, CodeType))
    return set(code.co_names).union(*( _s5_core_referenced_names(child) for child in children))

def _s5_core_function_value(function):
    closure = tuple(cell.cell_contents for cell in (function.__closure__ or ()))
    return {
        "code": _s5_core_code_value(function.__code__),
        "defaults": _s5_core_value(function.__defaults__),
        "kwdefaults": _s5_core_value(function.__kwdefaults__),
        "closure": _s5_core_value(closure),
    }

def sector6_runtime_core_sha256(entrypoint, namespace, dependency_versions):
    """Fingerprint active core functions, referenced S3 constants and library versions.

    Only Python functions reachable through executable global references and
    referenced ``S5_*`` constants participate. Unrelated configuration, clocks and
    notebook state are ignored. Recursive function graphs terminate through a
    visited-name set; repeated cell executions keep the same identity.
    """
    if not isinstance(entrypoint, FunctionType) or not isinstance(namespace, dict):
        raise TypeError("Provide a Python entrypoint function and its explicit namespace dictionary.")
    if not isinstance(dependency_versions, dict):
        raise TypeError("Dependency versions must be an explicit dictionary.")
    pending = {"entrypoint": entrypoint}
    functions, constants = {}, {}
    while pending:
        name = min(pending)
        function = pending.pop(name)
        if name in functions:
            continue
        functions[name] = _s5_core_function_value(function)
        for reference in sorted(_s5_core_referenced_names(function.__code__)):
            value = namespace.get(reference)
            if isinstance(value, FunctionType) and reference not in functions:
                pending[reference] = value
            elif reference.isupper() and reference in namespace and isinstance(value, (str, bool, int, float, bytes, dict, list, tuple, set, frozenset, type(None))):
                constants[reference] = _s5_core_value(value)
    payload = {
        "schema_version": 1, "functions": functions, "constants": constants,
        "dependency_versions": _s5_core_value(dependency_versions),
    }
    return hashlib.sha256(_s5_core_identity_json(payload).encode("utf-8")).hexdigest()

sector7_runtime_core_sha256 = sector6_runtime_core_sha256

S7_SCHEMA_VERSION = 3
S7_EXECUTION_CONTRACT = {
    'training_ready': False, 'split_policy': 'deferred',
    'split_assignment_status': 'pending',
    'threshold_fit_policy': 'deferred_until_validated_final_split',
}

S7_STATE_PATH = 'configs/sector7_state.json'
S7_RECEIPT_PATH = 'configs/sector7_publication_receipt.json'
S7_LINEAGE_PATH = 'configs/sector7_lineage.json'
S7_RESULT_NAMES = frozenset({'image_qc_inventory', 'image_qc_manifest', 'image_qc_thresholds', 'labelled_frame_manifest_with_qc', 'temporal_manifest_with_qc'})
S7_REPORT_NAMES = frozenset({'image_qc_summary', 'image_read_failure_report', 'qc_reference_report', 'image_qc_source_audit', 'missing_image_reference_report'})
_p7_safe_path = _p3_safe_path
_p7_file_hash = _p3_file_hash

def _p7_write_json(path, value):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(_p3_json_text(value), encoding='utf-8')
    if _p3_json_text(json.loads(path.read_text(encoding='utf-8'))) != _p3_json_text(value):
        raise RuntimeError(f'Sector 7 JSON readback failed: {path.name}')

def _p7_assert_no_secrets(value, path='configuration'):
    """Save credential references, never actual credential material."""
    if isinstance(value, dict):
        for key, item in value.items():
            if str(key).lower() in {'token', 'access_token', 'github_token', 'password', 'api_key', 'authorization', 'secret', 'private_key', 'client_secret'} and item:
                raise ValueError(f'Credential material cannot be saved at {path}.{key}; use token_secret_name.')
            _p7_assert_no_secrets(item, f'{path}.{key}')
    elif isinstance(value, (list, tuple)):
        for item in value:
            _p7_assert_no_secrets(item, path)
    elif isinstance(value, str) and (re.search('https?://[^/\\s]*:[^/@\\s]+@', value) or re.search('(?:gh[pousr]_[A-Za-z0-9_]{20,}|github_pat_[A-Za-z0-9_]{20,})', value)):
        raise ValueError(f'Credential material cannot be saved at {path}.')

def sector7_semantic_config_fingerprint(config):
    projected = sector4_semantic_config(config)
    projected.pop('github', None)
    sector = projected.get('sector7', {})
    for key in ('push', 'dry_run', 'github_overrides'):
        sector.pop(key, None)
    return _s3_semantic_digest(projected)


def sector7_processing_signature(config, lineage):
    """Pure identity of the effective config, consumed input bytes and active code."""
    hashes, core_hash = (lineage.get('input_sha256'), lineage.get('core_source_sha256'))
    if not isinstance(hashes, dict) or not hashes or (not isinstance(core_hash, str)):
        raise ValueError('Sector 7 lineage needs input_sha256 and core_source_sha256.')
    return _p3_json_hash({'phase': 2, 'sector': 7, 'schema_version': S7_SCHEMA_VERSION, 'execution_contract': S7_EXECUTION_CONTRACT, 'semantic_config_fingerprint': sector7_semantic_config_fingerprint(config), 'input_sha256': hashes, 'core_source_sha256': core_hash, 'image_source_audit_sha256': lineage.get('image_source_audit_sha256')})

def _p7_lineage_payload(lineage):
    """Current provenance, excluding clock metadata while retaining input identities.

    Convert diagnostic DataFrames and other supported values before applying
    Sector 4's clock-only projection; hashes, descriptors, dependency versions,
    decoder settings and the upstream artifact chain keep their full meaning.
    """
    return sector4_semantic_config(json.loads(_p3_json_text(lineage)))

def _p7_root(config):
    declared = Path(config.get('sector7', {}).get('local_output_dir', 'outputs/phase2/sector7')).expanduser()
    return (declared if declared.is_absolute() else Path(config['storage_root']) / declared).resolve()

def _p7_validate_lineage(lineage):
    """Recheck every consumed upstream file immediately before publishing local results."""
    hashes, descriptors = (lineage.get('input_sha256'), lineage.get('input_descriptors'))
    if not isinstance(hashes, dict) or not hashes or (not isinstance(descriptors, dict)):
        raise ValueError('Sector 7 lineage needs input_sha256 and input_descriptors from checked input loading.')
    if set(hashes) != set(descriptors):
        raise ValueError('Sector 7 input file descriptors do not match its consumed input hashes.')
    for key, digest in hashes.items():
        if not isinstance(digest, str) or re.fullmatch('[0-9a-f]{64}', digest) is None:
            raise ValueError(f'Invalid consumed input SHA-256 in Sector 7 lineage: {key}')
        path = Path(descriptors[key]).expanduser()
        if not path.is_absolute() or not path.is_file() or path.is_symlink():
            raise RuntimeError(f'Consumed upstream artifact is unavailable or unsafe: {key}')
        if _p3_file_hash(path) != digest:
            raise RuntimeError(f'Consumed upstream artifact changed after loading: {key}; rerun input loading.')
    core_hash = lineage.get('core_source_sha256')
    if not isinstance(core_hash, str) or re.fullmatch('[0-9a-f]{64}', core_hash) is None:
        raise ValueError('Sector 7 lineage lacks the active transformation SHA-256; run the processing-signature cell.')

def _p7_catalog_meaning(state):
    """Bind QC completion separately from deferred training eligibility."""
    return {**_p3_catalog_meaning(state),
            'config_snapshot_fingerprint': state['config_snapshot_fingerprint'],
            'execution_contract': state['execution_contract']}


def _p7_active_artifact_paths(tables, config_snapshot, summary):
    """Catalog only the current snapshot; older versions remain on disk untouched."""
    paths = {config_snapshot, S7_LINEAGE_PATH,
             summary['summary_relative_path'], summary['report_relative_path']}
    for name, descriptor in tables.items():
        paths.update((descriptor['relative_path'], descriptor['schema_path']))
        if name == 'image_qc_summary':
            paths.add(str(PurePosixPath(descriptor['relative_path']).with_suffix('.csv')))
    return paths


def _p7_validate_summary_contract(summary):
    if not isinstance(summary, dict) or summary.get('schema_version') != 2:
        raise RuntimeError('Sector 7 summary must use the deferred-QC schema.')
    if any(summary.get(key) != value for key, value in S7_EXECUTION_CONTRACT.items()):
        raise RuntimeError('Sector 7 summary must explicitly defer splits, calibration and training readiness.')
    if summary.get('material_validation_passed') is not True:
        raise RuntimeError('Sector 7 material validation was not completed.')
    return True


def _p7_validate_deferred_tables(tables):
    """Reject internally consistent hashes that still describe obsolete semantics."""
    if set(tables) != S7_RESULT_NAMES | S7_REPORT_NAMES:
        raise RuntimeError('Sector 7 requires the complete declared table set.')
    for name in ('image_qc_inventory', 'image_qc_manifest',
                 'labelled_frame_manifest_with_qc', 'temporal_manifest_with_qc'):
        frame = tables[name]
        qc_require_columns(frame, ['final_split', 'split_assignment_status'], name)
        if frame['final_split'].notna().any() or not frame['split_assignment_status'].eq('pending').fillna(False).all():
            raise RuntimeError(f'Sector 7 may not assign or inherit final splits: {name}')
    for name in ('image_qc_manifest', 'labelled_frame_manifest_with_qc', 'temporal_manifest_with_qc'):
        frame = tables[name]
        qc_require_columns(frame, ['training_ready', 'image_usable_for_modelling',
                                   'qc_thresholds_calibrated', 'qc_assessment_status'], name)
        for flag in ('training_ready', 'image_usable_for_modelling', 'qc_thresholds_calibrated'):
            if frame[flag].isna().any() or not frame[flag].eq(False).all():
                raise RuntimeError(f'Deferred Sector 7 cannot mark {flag} true or unknown: {name}')
        if not frame['qc_assessment_status'].eq('metrics_only_final_split_pending').fillna(False).all():
            raise RuntimeError(f'Sector 7 must identify metrics-only assessments: {name}')
        for flag in ('qc_blur_outlier', 'qc_contrast_outlier',
                     'qc_low_brightness_outlier', 'qc_high_brightness_outlier'):
            if flag not in frame or frame[flag].notna().any():
                raise RuntimeError(f'Deferred statistical QC flags must remain unevaluated: {name}/{flag}')
    thresholds = tables['image_qc_thresholds']
    if len(thresholds) != 1:
        raise RuntimeError('Sector 7 thresholds must contain one deferred status row.')
    row = thresholds.iloc[0]
    if (row['threshold_calibration_status'] != 'deferred_final_split_pending' or
            row['threshold_fit_split'] != 'deferred' or
            row['calibration_candidate_images'] != 0 or row['calibration_readable_images'] != 0):
        raise RuntimeError('Sector 7 must defer calibration until a validated final split exists.')
    for field in ('blur_laplacian_lower_threshold', 'contrast_std_lower_threshold',
                  'brightness_mean_lower_threshold', 'brightness_mean_upper_threshold'):
        if pd.notna(row[field]):
            raise RuntimeError('Sector 7 cannot persist fitted thresholds in deferred mode.')
    qc = tables['image_qc_manifest']
    if len(qc) != len(tables['image_qc_inventory']) or not qc['image_relpath'].is_unique:
        raise RuntimeError('Sector 7 QC rows must cover its unique-image inventory exactly.')
    if set(qc['image_relpath']) != set(tables['image_qc_inventory']['image_relpath']):
        raise RuntimeError('Sector 7 QC image identities disagree with its inventory.')
    readable = qc['image_readable'].astype('boolean')
    if readable.isna().any() or not qc['image_technically_usable'].eq(readable).fillna(False).all():
        raise RuntimeError('Sector 7 technical usability must reflect image readability only.')
    summary = tables['image_qc_summary']
    if len(summary) != 1:
        raise RuntimeError('Sector 7 requires one QC summary row.')
    observed = summary.iloc[0]
    expected_counts = {
        'total_unique_images': len(qc), 'readable_images': int(readable.sum()),
        'unreadable_images': int((~readable).sum()),
        'technically_usable_images': int(readable.sum()), 'model_usable_images': 0,
        'review_required_images': int(qc['qc_requires_review'].fillna(False).sum()),
        'calibration_candidate_images': 0, 'calibration_readable_images': 0,
    }
    if any(pd.isna(observed.get(key)) or observed[key] != value for key, value in expected_counts.items()):
        raise RuntimeError('Sector 7 summary counts disagree with its current QC rows.')
    if (pd.isna(observed.get('training_ready')) or bool(observed['training_ready']) or
            observed.get('split_assignment_status') != 'pending' or
            observed.get('qc_assessment_status') != 'metrics_only_final_split_pending' or
            observed.get('threshold_calibration_status') != 'deferred_final_split_pending' or
            observed.get('threshold_fit_split') != 'deferred' or
            row['total_readable_images'] != int(readable.sum())):
        raise RuntimeError('Sector 7 summary/calibration readiness disagrees with deferred QC.')
    references = tables['qc_reference_report']
    if len(references) != len(tables['labelled_frame_manifest_with_qc']) + len(tables['temporal_manifest_with_qc']):
        raise RuntimeError('Sector 7 QC reference report must retain every source row.')
    audit = tables['image_qc_source_audit']
    if not audit['image_relpath'].is_unique or set(audit['image_relpath']) != set(qc['image_relpath']):
        raise RuntimeError('Sector 7 source audit must cover exactly the QC image identities.')
    for name, frame in (('QC manifest', qc), ('source audit', audit)):
        digests = frame['image_sha256']
        if not all(isinstance(value, str) and re.fullmatch('[0-9a-f]{64}', value) is not None
                   for value in digests):
            raise RuntimeError(f'Sector 7 {name} requires a non-null lowercase SHA-256 for every encoded image, including undecodable files.')
    comparable = qc[['image_relpath', 'image_sha256']].merge(
        audit[['image_relpath', 'image_sha256']], on='image_relpath', validate='one_to_one',
        suffixes=('_qc', '_audit'))
    if comparable['image_sha256_qc'].ne(comparable['image_sha256_audit']).any():
        raise RuntimeError('Sector 7 QC metrics disagree with the audited image bytes.')
    return True


def _p7_read_snapshot(root):
    """Validate the complete flat catalog, current config, schemas and report bytes."""
    root = Path(root).resolve()
    state_path = _p3_safe_path(root, S7_STATE_PATH)
    if not state_path.is_file():
        return None
    state = json.loads(state_path.read_text(encoding='utf-8'))
    if not isinstance(state, dict):
        raise RuntimeError('Sector 7 catalog must be a JSON object.')
    if state.get('schema_version') != S7_SCHEMA_VERSION or state.get('complete') is not True:
        raise RuntimeError('Sector 7 catalog is incomplete or has an unsupported schema.')
    if state.get('execution_contract') != S7_EXECUTION_CONTRACT:
        raise RuntimeError('Sector 7 catalog has an invalid deferred-QC contract.')
    if state.get('content_id') != _p3_json_hash(_p7_catalog_meaning(state)):
        raise RuntimeError('Sector 7 catalog fingerprint is invalid.')
    if (not isinstance(state.get('tables'), dict) or
            not all(isinstance(value, dict) for value in state['tables'].values()) or
            not isinstance(state.get('artifacts'), list) or
            not all(isinstance(value, dict) for value in state['artifacts']) or
            not isinstance(state.get('summary'), dict)):
        raise RuntimeError('Sector 7 catalog has invalid table/artifact/summary structures.')
    records = {record['relative_path']: record for record in state['artifacts']}
    if len(records) != len(state['artifacts']) or {S7_STATE_PATH, S7_RECEIPT_PATH} & set(records):
        raise RuntimeError('Sector 7 catalog contains duplicate or operational artifact entries.')
    if set(records) != _p7_active_artifact_paths(state['tables'], state['config_snapshot'], state['summary']):
        raise RuntimeError('Sector 7 catalog must contain exactly the current snapshot artifacts.')
    for relative, record in records.items():
        path = _p3_safe_path(root, relative)
        if not path.is_file() or path.stat().st_size != record['bytes'] or _p3_file_hash(path) != record['sha256']:
            raise RuntimeError(f'Sector 7 saved artifact checksum verification failed: {relative}')
    if state['config_snapshot'] not in records:
        raise RuntimeError('Sector 7 current configuration snapshot is absent from its catalog.')
    envelope = json.loads(_p3_safe_path(root, state['config_snapshot']).read_text(encoding='utf-8'))
    if not isinstance(envelope, dict) or not isinstance(envelope.get('effective_config'), dict):
        raise RuntimeError('Sector 7 configuration snapshot has an invalid structure.')
    if state.get('config_snapshot_fingerprint') != _p3_json_hash(sector4_semantic_config(envelope['effective_config'])):
        raise RuntimeError('Sector 7 full effective configuration fingerprint is invalid.')
    if envelope.get('semantic_config_fingerprint') != state['semantic_config_fingerprint'] or sector7_semantic_config_fingerprint(envelope['effective_config']) != state['semantic_config_fingerprint']:
        raise RuntimeError('Sector 7 saved effective configuration disagrees with its catalog.')
    if S7_LINEAGE_PATH not in records:
        raise RuntimeError('Sector 7 current lineage is absent from its catalog.')
    saved_lineage = json.loads(_p3_safe_path(root, S7_LINEAGE_PATH).read_text(encoding='utf-8'))
    if not isinstance(saved_lineage, dict):
        raise RuntimeError('Sector 7 saved lineage must be a JSON object.')
    if saved_lineage.get('input_sha256') != state['input_sha256'] or saved_lineage.get('core_source_sha256') != state['core_source_sha256'] or (not isinstance(saved_lineage.get('input_descriptors'), dict)) or (set(saved_lineage['input_descriptors']) != set(state['input_sha256'])):
        raise RuntimeError('Sector 7 saved current lineage disagrees with its catalog.')
    if _p3_json_hash(saved_lineage) != records[S7_LINEAGE_PATH]['sha256']:
        raise RuntimeError('Sector 7 current lineage is not canonically encoded.')
    if sector7_processing_signature(envelope['effective_config'], saved_lineage) != state['processing_signature']:
        raise RuntimeError('Sector 7 processing signature disagrees with saved provenance.')
    audit_descriptor = state['tables'].get('image_qc_source_audit')
    if audit_descriptor is None or audit_descriptor['fingerprint'] != saved_lineage.get('image_source_audit_sha256'):
        raise RuntimeError('Sector 7 image audit identity disagrees with saved provenance.')
    for name, descriptor in state['tables'].items():
        if not {descriptor['relative_path'], descriptor['schema_path']}.issubset(records):
            raise RuntimeError(f'Sector 7 table/schema absent from catalog: {name}')
        schema = json.loads(_p3_safe_path(root, descriptor['schema_path']).read_text(encoding='utf-8'))
        if not isinstance(schema, dict):
            raise RuntimeError(f'Sector 7 table schema must be a JSON object: {name}')
        if schema.get('artifact') != descriptor['relative_path'] or schema.get('fingerprint') != descriptor['fingerprint']:
            raise RuntimeError(f'Sector 7 saved table schema disagrees with catalog: {name}')
    summary = state['summary']
    if not {summary['summary_relative_path'], summary['report_relative_path']}.issubset(records):
        raise RuntimeError('Sector 7 summary/report is absent from its catalog.')
    saved_summary = json.loads(_p3_safe_path(root, summary['summary_relative_path']).read_text(encoding='utf-8'))
    if _p3_json_hash(saved_summary) != summary['fingerprint'] or records[summary['report_relative_path']]['sha256'] != summary['report_fingerprint']:
        raise RuntimeError('Sector 7 saved summary/report disagrees with its catalog.')
    for relative in state.get('obsolete_paths', []):
        if not _p3_relative(relative).startswith('results/') or relative in records:
            raise RuntimeError('Invalid Sector 7 obsolete-result deletion authorization.')
    if set(state['tables']) != S7_RESULT_NAMES | S7_REPORT_NAMES:
        raise RuntimeError('Sector 7 cached table set is incomplete or obsolete.')
    tables = {name: _p3_read_table(root, descriptor) for name, descriptor in state['tables'].items()}
    for name, table in tables.items():
        descriptor = state['tables'][name]
        schema = json.loads(_p3_safe_path(root, descriptor['schema_path']).read_text(encoding='utf-8'))
        if schema != {**_p3_schema(table), 'artifact': descriptor['relative_path'], 'fingerprint': descriptor['fingerprint']}:
            raise RuntimeError(f'Sector 7 saved schema does not describe the restored table: {name}')
    _p7_validate_deferred_tables(tables)
    if _p3_json_text(saved_summary) != _p3_json_text(_p7_summary(tables)):
        raise RuntimeError('Sector 7 summary does not describe its current typed tables.')
    _p7_validate_summary_contract(saved_summary)
    return {'state': state, 'tables': tables, 'lineage': saved_lineage}

def _p7_read_state(root):
    snapshot = _p7_read_snapshot(root)
    return None if snapshot is None else snapshot['state']

def _p7_local_cache_snapshot(root):
    """Read only Sector 7's disposable cache; never catch upstream/source failures.

    Known catalog, JSON, schema and Parquet validation failures invalidate the
    local cache. Access-denied errors, missing dependencies, memory exhaustion
    and other execution failures still propagate. Invalid catalog paths are
    never used to authorize recovery writes or deletions.
    """
    # Recovery is outside the disposable-cache exception boundary: an unsafe or
    # incomplete transaction must never be hidden by recomputation.
    _p7_recover_interrupted_installs(root)
    try:
        snapshot = _p7_read_snapshot(root)
        if snapshot is None:
            root = Path(root)
            if root.is_dir() and any(root.iterdir()):
                raise RuntimeError('Sector 7 catalog is missing from an existing nonempty output directory.')
        return snapshot, None
    except (RuntimeError, ValueError, KeyError, TypeError, FileNotFoundError) as error:
        return None, f'{type(error).__name__}: {error}'


def io_load_cached_sector7(config, processing_signature):
    """Reuse verified local outputs; invalid local cache causes a fresh computation."""
    snapshot, cache_error = _p7_local_cache_snapshot(_p7_root(config))
    if cache_error is not None:
        print('Sector 7 local cache failed validation; QC will be recomputed. '
              'Existing files are retained until a replacement is verified.')
        return None
    if snapshot is None or snapshot['state']['processing_signature'] != processing_signature:
        return None
    return snapshot

def _p7_summary(tables):
    """Pure summary supplied by the Sector 7 transformation cell."""
    return build_sector7_summary(tables)

def _p7_executive(summary):
    return ('# Phase 2 — Sector 7: Image Quality Control\n\n'
            'Unique labelled and temporal images receive technical quality metrics. '
            'Original annotation and temporal-reference rows are retained.\n\n'
            f"Unique images: {summary['qc']['total_unique_images']}; readable: {summary['qc']['readable_images']}; "
            f"review required: {summary['qc']['review_required_images']}.\n\n"
            'Final split assignment and statistical threshold fitting are deferred. '
            'These outputs are not training-ready; readability records technical accessibility only. '
            'Missing/unreadable images and unresolved references remain explicit QC results.\n\n'
            'Parquet tables, schemas, source lineage and catalog checksums support verified reuse. '
            'Only the small QC summary also has a CSV export; row-level reports remain Parquet. '
            'Image binaries remain on Google Drive.\n')


def _p7_write_table(stage, name, frame, fingerprint, stamp):
    is_result = name in S7_RESULT_NAMES
    base = f'results/{name}' if is_result else f'reports/{name}_{stamp}'
    relative = base + '.parquet'
    path = stage / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    frame.to_parquet(path, index=False, compression='zstd', engine='pyarrow')
    validate_persisted_dataframe(frame, path, name)
    if name == 'image_qc_summary':
        frame.to_csv(stage / (base + '.csv'), index=False)
    schema_relative = base + '_schema.json'
    _p7_write_json(stage / schema_relative, {**_p3_schema(frame), 'artifact': relative, 'fingerprint': fingerprint})
    return {'relative_path': relative, 'schema_path': schema_relative, 'fingerprint': fingerprint}


def _p7_atomic_json(path, value):
    """Durable journal update; a partial JSON write never replaces its predecessor."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + '.next')
    try:
        with temporary.open('w', encoding='utf-8') as stream:
            stream.write(_p3_json_text(value))
            stream.flush()
            os.fsync(stream.fileno())
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def _p7_transaction_prefix(root):
    identity = hashlib.sha256(str(Path(root).resolve()).encode('utf-8')).hexdigest()[:16]
    return '.sector7-transaction-' + identity + '-'


def _p7_install_file(source, target):
    """One atomic installation boundary; also allows process-crash fault testing."""
    target.parent.mkdir(parents=True, exist_ok=True)
    source.replace(target)


def _p7_check_transaction(root, transaction, journal):
    if (not isinstance(journal, dict) or journal.get('schema_version') != 1 or
            journal.get('root') != str(root) or
            journal.get('phase') not in {'preparing', 'installing', 'committed'} or
            not isinstance(journal.get('operations'), list) or
            not isinstance(journal.get('preserve_backup'), bool)):
        raise RuntimeError('Sector 7 recovery journal is malformed; existing files were preserved.')
    paths = []
    for record in journal['operations']:
        if not isinstance(record, dict):
            raise RuntimeError('Sector 7 recovery operation is malformed.')
        relative = _p3_relative(record.get('relative_path'))
        _p3_safe_path(root, relative)
        _p3_safe_path(transaction / 'backup', relative)
        for field in ('old_sha256', 'new_sha256'):
            digest = record.get(field)
            if digest is not None and (not isinstance(digest, str) or re.fullmatch('[0-9a-f]{64}', digest) is None):
                raise RuntimeError('Sector 7 recovery operation lacks a valid byte identity.')
        paths.append(relative)
    if len(set(paths)) != len(paths) or not paths or paths[-1] != S7_STATE_PATH:
        raise RuntimeError('Sector 7 recovery operation ordering is invalid.')
    return True


def _p7_restore_transaction(root, transaction, journal):
    """Validate every backup/current target before restoring any original bytes."""
    _p7_check_transaction(root, transaction, journal)
    for record in journal['operations']:
        relative = record['relative_path']
        target = _p3_safe_path(root, relative)
        old_hash, new_hash = record['old_sha256'], record['new_sha256']
        if old_hash is not None:
            backup = _p3_safe_path(transaction / 'backup', relative)
            if not backup.is_file() or _p3_file_hash(backup) != old_hash:
                raise RuntimeError('Sector 7 recovery backup is incomplete; no originals were discarded.')
        if target.exists():
            if not target.is_file() or _p3_file_hash(target) not in {old_hash, new_hash}:
                raise RuntimeError('Sector 7 output changed outside its interrupted transaction; files were preserved.')
    # Restore the previous state last, just as the new state was installed last.
    for record in journal['operations']:
        relative = record['relative_path']
        target = _p3_safe_path(root, relative)
        if record['old_sha256'] is None:
            target.unlink(missing_ok=True)
        else:
            backup = _p3_safe_path(transaction / 'backup', relative)
            target.parent.mkdir(parents=True, exist_ok=True)
            temporary = target.with_name(target.name + '.sector7-restore')
            try:
                shutil.copyfile(backup, temporary)
                if _p3_file_hash(temporary) != record['old_sha256']:
                    raise RuntimeError('Sector 7 rollback copy failed byte verification.')
                temporary.replace(target)
            finally:
                temporary.unlink(missing_ok=True)
    return True


def _p7_finish_transaction(root, transaction, journal):
    if journal['preserve_backup']:
        destination = Path(tempfile.mkdtemp(prefix='.sector7-recovery-', dir=root.parent))
        destination.rmdir()
        transaction.rename(destination)
        return str(destination / 'backup')
    shutil.rmtree(transaction)
    return None


def _p7_recover_interrupted_installs(root):
    """Recover process-killed installs before consulting or replacing a local cache."""
    root = Path(root).resolve()
    if not root.parent.is_dir():
        return []
    recoveries = []
    for transaction in sorted(root.parent.glob(_p7_transaction_prefix(root) + '*')):
        if transaction.is_symlink() or not transaction.is_dir():
            raise RuntimeError('Unsafe Sector 7 transaction directory; recovery stopped.')
        journal_path = transaction / 'journal.json'
        if not journal_path.is_file():
            # A process may die between mkdir and the initial journal. No file
            # operation is authorized until that journal has been committed.
            entries = list(transaction.iterdir())
            if any(path.name != 'journal.json.next' or not path.is_file() or path.is_symlink() for path in entries):
                raise RuntimeError('Sector 7 transaction has no valid journal; retained for inspection.')
            shutil.rmtree(transaction)
            continue
        journal = json.loads(journal_path.read_text(encoding='utf-8'))
        _p7_check_transaction(root, transaction, journal)
        if journal['phase'] == 'preparing':
            shutil.rmtree(transaction)
            recoveries.append('discarded_incomplete_backup')
            continue
        if journal['phase'] == 'installing':
            state_path = _p3_safe_path(root, S7_STATE_PATH)
            state_operation = journal['operations'][-1]
            complete = False
            if state_path.is_file() and _p3_file_hash(state_path) == state_operation['new_sha256']:
                try:
                    complete = _p7_read_snapshot(root) is not None
                except (RuntimeError, ValueError, KeyError, TypeError, FileNotFoundError):
                    complete = False
            if not complete:
                _p7_restore_transaction(root, transaction, journal)
                shutil.rmtree(transaction)
                recoveries.append('rolled_back_interrupted_install')
                continue
            journal['phase'] = 'committed'
            _p7_atomic_json(journal_path, journal)
        backup = _p7_finish_transaction(root, transaction, journal)
        recoveries.append({'status': 'completed_verified_install', 'backup_root': backup})
    return recoveries


def _p7_install(stage, root, changed_paths, obsolete_paths, preserve_backup=False):
    """Journaled install: preserve originals before the first mutation, state last."""
    root, stage = Path(root).resolve(), Path(stage).resolve()
    _p7_recover_interrupted_installs(root)
    root.mkdir(parents=True, exist_ok=True)
    sequence = [path for path in changed_paths if path != S7_STATE_PATH] + list(obsolete_paths) + [S7_STATE_PATH]
    operations = []
    for relative in dict.fromkeys(sequence):
        relative = _p3_relative(relative)
        target, source = _p3_safe_path(root, relative), _p3_safe_path(stage, relative)
        if target.exists() and not target.is_file():
            raise RuntimeError('Sector 7 output replacement requires a regular file.')
        operations.append({'relative_path': relative,
                           'old_sha256': _p3_file_hash(target) if target.is_file() else None,
                           'new_sha256': _p3_file_hash(source) if source.is_file() else None})
    if operations[-1]['new_sha256'] is None:
        raise RuntimeError('Sector 7 installation requires a staged completed state.')
    transaction = Path(tempfile.mkdtemp(prefix=_p7_transaction_prefix(root), dir=root.parent))
    journal = {'schema_version': 1, 'root': str(root), 'phase': 'preparing',
               'preserve_backup': bool(preserve_backup), 'operations': operations}
    journal_path = transaction / 'journal.json'
    _p7_atomic_json(journal_path, journal)
    installing = False
    try:
        for record in operations:
            if record['old_sha256'] is not None:
                relative = record['relative_path']
                backup = _p3_safe_path(transaction / 'backup', relative)
                backup.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(_p3_safe_path(root, relative), backup)
                with backup.open('rb') as stream:
                    os.fsync(stream.fileno())
                if _p3_file_hash(backup) != record['old_sha256']:
                    raise RuntimeError('Sector 7 output changed while its recovery backup was created.')
        journal['phase'] = 'installing'
        _p7_atomic_json(journal_path, journal)
        installing = True
        for record in operations:
            relative = record['relative_path']
            target, source = _p3_safe_path(root, relative), _p3_safe_path(stage, relative)
            current_hash = _p3_file_hash(target) if target.is_file() else None
            if current_hash != record['old_sha256']:
                raise RuntimeError('Sector 7 output changed during installation; refusing to overwrite it.')
            if record['new_sha256'] is None:
                target.unlink(missing_ok=True)
            else:
                _p7_install_file(source, target)
        if _p7_read_snapshot(root) is None:
            raise RuntimeError('Sector 7 installed snapshot is missing.')
        journal['phase'] = 'committed'
        _p7_atomic_json(journal_path, journal)
    except BaseException:
        if installing:
            _p7_restore_transaction(root, transaction, journal)
        shutil.rmtree(transaction)
        raise
    return _p7_finish_transaction(root, transaction, journal)

def io_persist_sector7(tables, config, lineage):
    """Save/read back Sector 7 outputs; leave all saved files untouched when unchanged."""
    print("S7 | Validating configurations, sources and existing results...",
          flush=True)
    signature = sector7_processing_signature(config, lineage)
    if not isinstance(tables, dict) or not tables or any((not isinstance(frame, pd.DataFrame) for frame in tables.values())):
        raise TypeError('Sector 7 output tables must be a nonempty dictionary of DataFrames.')
    if set(tables) != S7_RESULT_NAMES | S7_REPORT_NAMES:
        raise ValueError('Pass all Sector 7 result and report tables.')
    if sector3_table_fingerprint(tables['image_qc_source_audit']) != lineage.get('image_source_audit_sha256'):
        raise ValueError('Sector 7 source audit changed after signature preparation; rerun cache/computation.')
    _p7_assert_no_secrets(config)
    _p7_assert_no_secrets(lineage)
    _p7_validate_lineage(lineage)
    _p7_validate_deferred_tables(tables)
    root = _p7_root(config)
    previous_snapshot, cache_error = _p7_local_cache_snapshot(root)
    previous = None if previous_snapshot is None else previous_snapshot['state']
    config_hash = sector7_semantic_config_fingerprint(config)
    snapshot_hash = _p3_json_hash(sector4_semantic_config(config))
    provenance = {'input_sha256': copy.deepcopy(lineage['input_sha256']), 'core_source_sha256': lineage['core_source_sha256']}
    lineage_payload = _p7_lineage_payload(lineage)
    _p7_assert_no_secrets(lineage_payload, 'lineage')
    lineage_hash = _p3_json_hash(lineage_payload)
    fingerprints = {
        name: sector3_table_fingerprint(table)
        for name, table in tqdm(
            tables.items(),
            total=len(tables),
            desc="S7 | Table stamps",
            unit="table",
            dynamic_ncols=True,
        )
    }
    summary = _p7_summary(tables)
    _p7_validate_summary_contract(summary)
    summary_hash = _p3_json_hash(summary)
    report_text = _p7_executive(summary)
    report_hash = hashlib.sha256(report_text.encode('utf-8')).hexdigest()
    same_tables = previous is not None and set(fingerprints) == set(previous['tables']) and all((previous['tables'][name]['fingerprint'] == value for name, value in fingerprints.items()))
    if previous and same_tables and all((previous[key] == value for key, value in provenance.items())) and (previous.get('config_snapshot_fingerprint') == snapshot_hash and previous['semantic_config_fingerprint'] == config_hash and previous['summary']['fingerprint'] == summary_hash and (previous['processing_signature'] == signature) and (previous['summary']['report_fingerprint'] == report_hash) and any((record['relative_path'] == S7_LINEAGE_PATH and record['sha256'] == lineage_hash for record in previous['artifacts']))):
        io_validate_sector7_source_audit(tables['image_qc_source_audit'])
        return {'status': 'unchanged', 'root': str(root), 'local_root': str(root), 'state': previous, 'artifacts': previous['artifacts'], 'changed_paths': []}
    root.parent.mkdir(parents=True, exist_ok=True)
    stage = Path(tempfile.mkdtemp(prefix='.sector7-stage-', dir=root.parent))
    stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
    try:
        catalog = {record['relative_path']: record for record in previous['artifacts']} if previous else {}
        descriptors, obsolete = ({}, set(previous.get('obsolete_paths', [])) if previous else set())
        if catalog.get(S7_LINEAGE_PATH, {}).get('sha256') != lineage_hash:
            _p7_write_json(stage / S7_LINEAGE_PATH, lineage_payload)
        config_snapshot = previous['config_snapshot'] if previous else None
        if not previous or previous.get('config_snapshot_fingerprint') != snapshot_hash:
            config_snapshot = f'configs/sector7_config_{stamp}.json'
            _p7_write_json(stage / config_snapshot, {'schema_version': S7_SCHEMA_VERSION, 'changed_at_utc': stamp, 'semantic_config_fingerprint': config_hash, 'effective_config': config, 'current_lineage_path': S7_LINEAGE_PATH, 'lineage': lineage})
        for name, frame in tqdm(
            sorted(tables.items()),
            total=len(tables),
            desc="S7 | Save / reuse tables",
            unit="table",
            dynamic_ncols=True,
            ):
            old = previous['tables'].get(name) if previous else None
            if old and old['fingerprint'] == fingerprints[name]:
                descriptors[name] = old
            else:
                descriptors[name] = _p7_write_table(stage, name, frame, fingerprints[name], stamp)
                if old and old['relative_path'].startswith('results/') and (old['relative_path'] != descriptors[name]['relative_path']):
                    for relative in (old['relative_path'], old['schema_path']):
                        obsolete.add(relative)
                        catalog.pop(relative, None)
        previous_summary = previous['summary'] if previous else {}
        summary_path = previous_summary.get('summary_relative_path')
        if previous_summary.get('fingerprint') != summary_hash:
            summary_path = f'reports/summary_{stamp}.json'
            _p7_write_json(stage / summary_path, summary)
        report_path = previous_summary.get('report_relative_path')
        if catalog.get(report_path, {}).get('sha256') != report_hash:
            report_path = f'reports/executive_report_{stamp}.md'
            (stage / report_path).write_text(report_text, encoding='utf-8')
        summary_descriptor = {'fingerprint': summary_hash, 'summary_relative_path': summary_path, 'report_fingerprint': report_hash, 'report_relative_path': report_path}
        active_paths = _p7_active_artifact_paths(descriptors, config_snapshot, summary_descriptor)
        catalog = {path: record for path, record in catalog.items() if path in active_paths}
        changed = []
        for path in sorted(stage.rglob('*')):
            if path.is_file():
                relative = path.relative_to(stage).as_posix()
                record = {'relative_path': relative, 'sha256': _p3_file_hash(path), 'bytes': path.stat().st_size}
                if catalog.get(relative) == record:
                    path.unlink()
                else:
                    catalog[relative] = record
                    changed.append(relative)
        obsolete.difference_update(catalog)
        state = {'schema_version': S7_SCHEMA_VERSION, 'execution_contract': copy.deepcopy(S7_EXECUTION_CONTRACT), 'complete': True, 'processing_signature': signature, 'semantic_config_fingerprint': config_hash, 'config_snapshot': config_snapshot, 'config_snapshot_fingerprint': snapshot_hash, **provenance, 'tables': descriptors, 'summary': summary_descriptor, 'artifacts': [catalog[path] for path in sorted(catalog)], 'obsolete_paths': sorted(obsolete)}
        state['content_id'] = _p3_json_hash(_p7_catalog_meaning(state))
        state['changed_at_utc'] = stamp
        _p7_write_json(stage / S7_STATE_PATH, state)
        changed.append(S7_STATE_PATH)
        _p7_validate_lineage(lineage)
        io_validate_sector7_source_audit(tables['image_qc_source_audit'])
        recovery_backup = _p7_install(stage, root, changed, sorted(obsolete),
                                      preserve_backup=cache_error is not None)
        print("S7 | Install and check final results...",
              flush=True)
        return {'status': 'updated', 'root': str(root), 'local_root': str(root), 'state': state, 'artifacts': state['artifacts'], 'changed_paths': changed,
                'cache_recovery': None if cache_error is None else
                    {'reason': cache_error, 'backup_root': recovery_backup}}
    finally:
        shutil.rmtree(stage, ignore_errors=True)

def _p7_read_github_token(secret_name):
    if not isinstance(secret_name, str) or not secret_name or re.search('\\s', secret_name):
        raise ValueError('github.token_secret_name must be a nonempty secret reference.')
    token = os.environ.get(secret_name)
    if isinstance(token, str) and token.strip():
        return token.strip()
    if userdata is None:
        raise RuntimeError(f'GitHub secret {secret_name!r} is unavailable; run from Colab or supply an environment variable with this name.')
    try:
        token = userdata.get(secret_name)
    except Exception as error:
        raise RuntimeError(f'Cannot read Colab secret {secret_name!r} ({type(error).__name__}). Enable Notebook access. Saved Sector 7 outputs can be reused.') from None
    if not isinstance(token, str) or not token.strip():
        raise RuntimeError('GitHub secret is empty or invalid.')
    return token.strip()

def _p7_git_options(config):
    """Validate inherited repository settings and confine exports to Sector 7."""
    github, sector = (config.get('github', {}), config.get('sector7', {}))
    if not isinstance(github, dict) or not isinstance(sector, dict):
        raise TypeError('github and sector7 configuration must be dictionaries.')

    def flag(name, default):
        value = sector.get(name, github.get(name, default))
        if not isinstance(value, bool):
            raise TypeError(f'{name} must be a Python/JSON boolean.')
        return value
    push, dry_run = (flag('push', True), flag('dry_run', False))
    if not push and (not dry_run):
        return {'github': github, 'push': False, 'dry_run': False, 'branch': github.get('branch', 'main'), 'export_dir': 'outputs/phase2/sector7', 'export_parts': PurePosixPath('outputs/phase2/sector7')}
    maximum_mib = github.get('max_file_size_mib', 20)
    if (isinstance(maximum_mib, bool) or not isinstance(maximum_mib, (int, float)) or
            not math.isfinite(maximum_mib) or maximum_mib <= 0):
        raise ValueError('github.max_file_size_mib must be a positive finite number.')
    allow_local = github.get('allow_local_test_remote', sector.get('allow_local_test_remote', False))
    if not isinstance(allow_local, bool):
        raise TypeError('allow_local_test_remote must be a Python/JSON boolean.')
    export_dir = sector.get('export_dir', github.get('repo_output_dir', 'outputs/phase2/sector7'))
    if not isinstance(export_dir, str) or export_dir != 'outputs/phase2/sector7':
        raise ValueError('Sector 7 exports must use outputs/phase2/sector7.')
    export_parts = PurePosixPath(export_dir)
    repo_url = github.get('repo_url')
    if not isinstance(repo_url, str) or not repo_url or repo_url != repo_url.strip():
        raise ValueError('github.repo_url must be configured.')
    parsed = urlsplit(repo_url)
    github_remote = parsed.scheme == 'https' and parsed.netloc == 'github.com' and (parsed.username is None) and (parsed.password is None) and (not parsed.query) and (not parsed.fragment) and (re.fullmatch('/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+(?:\\.git)?', parsed.path) is not None)
    if not github_remote:
        if not allow_local:
            raise ValueError('Only credential-free HTTPS github.com repository URLs are allowed.')
        if parsed.scheme == 'file' and (not parsed.netloc) and (not parsed.query) and (not parsed.fragment):
            remote_path = Path(unquote(parsed.path)).resolve()
        elif not parsed.scheme and (not parsed.netloc):
            remote_path = Path(repo_url).resolve()
        else:
            raise ValueError('The explicitly enabled test remote must be a local filesystem repository.')
        if not remote_path.is_dir():
            raise ValueError('The local test repository does not exist.')
        repo_url = str(remote_path)
    branch = github.get('branch', 'main')
    if not isinstance(branch, str) or not branch or branch.startswith('-') or any((c in branch for c in '\r\n\x00')):
        raise ValueError('Invalid Git branch name.')
    author_name = next((github[key] for key in ('git_username', 'git_user_name', 'git_author_name', 'author_name', 'github_username', 'user_name') if github.get(key)), None)
    author_email = next((github[key] for key in ('git_email', 'git_user_email', 'git_author_email', 'author_email', 'user_email') if github.get(key)), None)
    if push and (not dry_run):
        if not isinstance(author_name, str) or not author_name.strip() or (not isinstance(author_email, str)) or (not author_email.strip()):
            raise ValueError('Configure the inherited Git author name and email before publishing.')
        if any((c in author_name + author_email for c in '\r\n\x00')):
            raise ValueError('Git author name and email must be single-line values.')
    return {'github': github, 'repo_url': repo_url, 'github_remote': github_remote, 'branch': branch, 'push': push, 'dry_run': dry_run, 'export_dir': export_dir, 'export_parts': export_parts, 'author_name': author_name, 'author_email': author_email, 'max_file_size_mib': float(maximum_mib)}

def _p7_git_session(options):
    """Return a private, temporary Git session; leave existing checkouts untouched."""

    @contextmanager
    def session():
        secret_name = options['github'].get('token_secret_name', 'GITHUB_TOKEN')
        token = _p7_read_github_token(secret_name) if options['github_remote'] and secret_name else None
        with tempfile.TemporaryDirectory(prefix='sector7-git-') as temporary:
            temporary_root = Path(temporary)
            checkout = temporary_root / 'repository'
            checkout.mkdir()
            askpass = temporary_root / 'askpass.py'
            askpass.write_text("#!/usr/bin/env python3\nimport os, sys\nprompt = sys.argv[1].lower() if len(sys.argv) > 1 else ''\nsys.stdout.write('x-access-token' if 'username' in prompt else os.environ.get('_P7_GITHUB_TOKEN', ''))\n", encoding='utf-8')
            askpass.chmod(448)
            hooks = temporary_root / 'hooks'
            hooks.mkdir()
            child_env = {key: value for key, value in os.environ.items() if not key.startswith(('GIT_TRACE', 'GIT_CONFIG_KEY_', 'GIT_CONFIG_VALUE_')) and key not in {'GIT_CURL_VERBOSE', 'SSH_ASKPASS'}}
            for variable in ('GIT_DIR', 'GIT_WORK_TREE', 'GIT_INDEX_FILE', 'GIT_CONFIG', 'GIT_CONFIG_COUNT', 'GIT_COMMON_DIR', 'GIT_OBJECT_DIRECTORY', 'GIT_ALTERNATE_OBJECT_DIRECTORIES', 'GIT_NAMESPACE', '_P7_GITHUB_TOKEN', 'GIT_AUTHOR_NAME', 'GIT_AUTHOR_EMAIL', 'GIT_COMMITTER_NAME', 'GIT_COMMITTER_EMAIL', 'GIT_AUTHOR_DATE', 'GIT_COMMITTER_DATE'):
                child_env.pop(variable, None)
            child_env.update({'GIT_TERMINAL_PROMPT': '0', 'GIT_ASKPASS': str(askpass), 'GIT_CONFIG_NOSYSTEM': '1', 'GIT_CONFIG_GLOBAL': os.devnull, 'GIT_LITERAL_PATHSPECS': '1'})
            if token:
                child_env['_P7_GITHUB_TOKEN'] = token

            def git(*args, allowed=(0,)):
                result = subprocess.run(['git', '-c', 'credential.helper=', '-c', f'core.askPass={askpass}', '-c', f'core.hooksPath={hooks}', *args], cwd=checkout, env=child_env, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
                if result.returncode not in allowed:
                    raise RuntimeError(f'Sector 7 Git {args[0]} failed (exit {result.returncode}).')
                return result
            git('check-ref-format', '--branch', options['branch'])
            git('init', '--quiet')
            git('remote', 'add', 'origin', options['repo_url'])
            yield (checkout, git)
    return session()

def io_fetch_sector7(config):
    """Fetch and report the latest remote tip without modifying the user's checkout."""
    options = _p7_git_options(config)
    if not options['push'] and (not options['dry_run']):
        return {'status': 'not_requested', 'branch': options['branch']}
    with _p7_git_session(options) as (_, git):
        git('fetch', '--quiet', 'origin', f"refs/heads/{options['branch']}")
        tip = git('rev-parse', 'FETCH_HEAD').stdout.strip()
        return {'status': 'fetched', 'branch': options['branch'], 'remote_tip': tip}

def _p7_check_export_size(path, relative, maximum_mib):
    size = Path(path).stat().st_size
    if size > maximum_mib * 1024 * 1024:
        raise RuntimeError(f'Sector 7 export exceeds github.max_file_size_mib: {relative} '
                           f'is {size / (1024 * 1024):.3f} MiB ({size} bytes); limit {maximum_mib:g} MiB.')
    return True


def _p7_repository_path(checkout, relative):
    """Repository paths may be deeper than the flat per-sector artifact layout."""
    if not isinstance(relative, str) or not relative or '\\' in relative:
        raise ValueError('Invalid authoritative repository path.')
    parts = PurePosixPath(relative)
    if parts.is_absolute() or parts.as_posix() != relative or any(part in {'.', '..', '.git'} for part in parts.parts):
        raise ValueError('Unsafe authoritative repository path.')
    root = Path(checkout).resolve()
    current = root
    for part in parts.parts:
        current = current / part
        if current.is_symlink():
            raise RuntimeError('Authoritative repository paths cannot contain symlinks.')
    current.resolve().relative_to(root)
    return current


def _p7_validate_remote_upstream(checkout, lineage, options):
    """Current main must still contain the exact upstream bytes consumed by QC."""
    authority = lineage.get('github_authority')
    if (not isinstance(authority, dict) or not isinstance(authority.get('files'), dict) or
            not authority['files'] or not isinstance(authority.get('commit'), str) or
            re.fullmatch('[0-9a-f]{40,64}', authority['commit']) is None):
        raise RuntimeError('Sector 7 publication requires pinned authoritative GitHub upstream metadata.')
    if (str(authority.get('repo_url', '')).removesuffix('.git').rstrip('/') !=
            str(options['repo_url']).removesuffix('.git').rstrip('/') or
            authority.get('branch') != options['branch']):
        raise RuntimeError('Sector 7 publication target differs from its authoritative upstream source.')
    consumed = set(lineage.get('input_sha256', {}).values())
    for relative, expected in authority['files'].items():
        path = _p7_repository_path(checkout, relative)
        if (relative.startswith('outputs/phase2/sector7/') or
                not isinstance(expected, str) or re.fullmatch('[0-9a-f]{64}', expected) is None or
                expected not in consumed):
            raise RuntimeError('Sector 7 upstream publication guard contains an invalid/unconsumed artifact.')
        if not path.is_file() or _p3_file_hash(path) != expected:
            raise RuntimeError(f'Current remote upstream metadata changed after QC: {relative}; reload and rerun Sector 7.')
    return True


def io_push_sector7(persisted, config):
    """Publish a catalog-verified Sector 7 snapshot with an ordinary non-force push.

    Only catalog artifacts, the Sector 7 state, and recorded obsolete result files
    are staged. The commit starts at the latest remote branch; races are retried.
    Existing checkouts, local edits and other pipeline sectors remain untouched.
    """
    options = _p7_git_options(config)
    branch, export_parts = (options['branch'], options['export_parts'])
    outcome = {'status': 'prepared', 'branch': branch, 'export_dir': options['export_dir'], 'pushed': False, 'dry_run': options['dry_run']}
    if not options['push'] and (not options['dry_run']):
        return {**outcome, 'status': 'not_requested'}
    root_value = persisted.get('local_root', persisted.get('root'))
    if root_value is None:
        raise ValueError('The persisted Sector 7 root is missing.')
    root = Path(root_value).resolve()
    _p7_recover_interrupted_installs(root)
    snapshot = _p7_read_snapshot(root)
    state = None if snapshot is None else snapshot['state']
    if state is None:
        raise RuntimeError('Sector 7 has no valid persisted snapshot to publish.')
    if persisted.get('state') != state:
        raise RuntimeError('Sector 7 changed after persistence; save it again before publishing.')
    artifacts = state.get('artifacts')
    if not isinstance(artifacts, list) or not artifacts:
        raise ValueError('Sector 7 state must contain a nonempty artifact catalog.')
    relative_paths, records = ([], {})
    for artifact in artifacts:
        if not isinstance(artifact, dict):
            raise ValueError('Invalid Sector 7 artifact record.')
        relative = artifact.get('relative_path')
        source = _p7_safe_path(root, relative)
        if not source.is_file() or source.is_symlink():
            raise RuntimeError(f'Missing or unsafe Sector 7 artifact: {relative}')
        _p7_check_export_size(source, relative, options['max_file_size_mib'])
        if _p7_file_hash(source) != artifact.get('sha256') or source.stat().st_size != artifact.get('bytes'):
            raise RuntimeError(f'Sector 7 artifact verification failed: {relative}')
        if relative in records:
            raise ValueError('Sector 7 artifact catalog has duplicate paths.')
        records[relative] = artifact
        relative_paths.append(relative)
    state_relative = 'configs/sector7_state.json'
    state_source = _p7_safe_path(root, state_relative)
    if state_source.is_symlink() or json.loads(state_source.read_text(encoding='utf-8')) != state:
        raise RuntimeError('Sector 7 state changed during publisher verification.')
    _p7_check_export_size(state_source, state_relative, options['max_file_size_mib'])
    if state_relative not in relative_paths:
        relative_paths.append(state_relative)
    obsolete_paths = state.get('obsolete_paths', [])
    if not isinstance(obsolete_paths, list) or any((not isinstance(path, str) for path in obsolete_paths)):
        raise ValueError('Sector 7 obsolete_paths must be a list of recorded relative paths.')
    for relative in obsolete_paths:
        _p7_safe_path(root, relative)
        if not relative.startswith('results/') or relative in relative_paths:
            raise ValueError('Only obsolete recorded result files may be deleted from the export.')
    outcome['count'] = len(relative_paths)
    with _p7_git_session(options) as (checkout, git):
        for attempt in range(1, 4):
            git('fetch', '--quiet', 'origin', f'refs/heads/{branch}')
            remote_tip = git('rev-parse', 'FETCH_HEAD').stdout.strip()
            git('checkout', '--quiet', '--detach', remote_tip)
            _p7_validate_remote_upstream(checkout, snapshot['lineage'], options)

            def export_target(relative):
                relative_path = PurePosixPath(relative)
                if relative_path.is_absolute() or any((p in {'.', '..', '.git'} for p in relative_path.parts)) or '\\' in relative:
                    raise ValueError('Invalid export artifact path.')
                target = checkout.joinpath(*export_parts.parts, *relative_path.parts)
                current = checkout
                for part in (*export_parts.parts, *relative_path.parts):
                    current = current / part
                    if current.is_symlink():
                        raise RuntimeError('The Git export path contains a symlink.')
                return target
            staged_paths = []
            for relative in relative_paths:
                source, target = (_p7_safe_path(root, relative), export_target(relative))
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(source, target)
                if relative in records:
                    record = records[relative]
                    if _p7_file_hash(target) != record['sha256'] or target.stat().st_size != record['bytes']:
                        raise RuntimeError('A Sector 7 artifact changed while being copied.')
                if relative == state_relative and json.loads(target.read_text(encoding='utf-8')) != state:
                    raise RuntimeError('The exported Sector 7 state changed while being copied.')
                staged_paths.append(target.relative_to(checkout).as_posix())
            for relative in obsolete_paths:
                target = export_target(relative)
                git_relative = target.relative_to(checkout).as_posix()
                tracked = bool(git('ls-files', '--', git_relative).stdout.strip())
                if target.exists():
                    if not target.is_file():
                        raise RuntimeError('An obsolete Sector 7 result path is not a file.')
                    target.unlink()
                if tracked:
                    staged_paths.append(git_relative)
            git('add', '--', *sorted(set(staged_paths)))
            changed = git('diff', '--cached', '--name-only', '-z').stdout
            changed_paths = [path for path in changed.split('\x00') if path]
            if any((not path.startswith(options['export_dir'] + '/') for path in changed_paths)):
                raise RuntimeError('The publication contains a change outside Sector 7.')
            outcome.update({'remote_tip': remote_tip, 'changed_paths': changed_paths, 'attempt': attempt})
            if _p7_read_state(root) != state:
                raise RuntimeError('Sector 7 changed during export; save it again before publishing.')
            if not changed_paths:
                return {**outcome, 'status': 'unchanged'}
            if options['dry_run']:
                return {**outcome, 'status': 'dry_run'}
            git('-c', f"user.name={options['author_name']}", '-c', f"user.email={options['author_email']}", 'commit', '--quiet', '-m', 'Update Phase 2 Sector 7 image quality control')
            commit = git('rev-parse', 'HEAD').stdout.strip()
            git('fetch', '--quiet', 'origin', f'refs/heads/{branch}')
            latest_tip = git('rev-parse', 'FETCH_HEAD').stdout.strip()
            if latest_tip != remote_tip:
                continue
            git('merge-base', '--is-ancestor', remote_tip, 'HEAD')
            pushed = git('push', '--quiet', 'origin', f'HEAD:refs/heads/{branch}', allowed=(0, 1, 128))
            if pushed.returncode == 0:
                return {**outcome, 'status': 'published', 'pushed': True, 'commit': commit}
            git('fetch', '--quiet', 'origin', f'refs/heads/{branch}')
            if git('rev-parse', 'FETCH_HEAD').stdout.strip() == remote_tip:
                raise RuntimeError('Sector 7 Git push failed. Check repository access and token permissions; the saved results remain available for retry.')
        raise RuntimeError('The remote branch kept changing; rerun the Sector 7 publication cell.')

## 6. Source staging and resumable orchestration

Build expected image identities from all S5 labelled files and every S6 temporal reference. Conflicting or missing expected hashes fail before QC. A valid SSD file is reused after SHA-256 verification; a missing/corrupt SSD copy is recopied from Drive through a temporary file and installed only when its bytes match the committed reference. Extracted-image provenance is checked separately.

QC hashes the exact encoded bytes sent to the decoder. Verified metric parts are stored under the SSD workspace and are reused only for matching inputs, active code, configuration and dependency/GPU identity. A corrupt part is recomputed. Source bytes or provenance changing during processing stops completion.

A hash-valid image that the decoder cannot read remains an explicit QC failure row. Missing or hash-mismatched source bytes require repair from the authoritative upstream material; S7 never adopts their new hash automatically.

In [27]:
def validate_persisted_dataframe(expected_dataframe, persisted_path, artifact_name):
    """Read back exact Parquet contents, column order and dtypes."""
    path = Path(persisted_path)
    if not path.is_file():
        raise FileNotFoundError(f'Persisted artifact missing: {artifact_name}: {path}')
    restored = pd.read_parquet(path, engine='pyarrow')
    pd.testing.assert_frame_equal(expected_dataframe.reset_index(drop=True), restored,
                                  check_exact=True, check_dtype=True)
    return True

def io_sector7_dependency_versions():
    """Bind required CPU and optional GPU libraries to cache identity."""
    versions = {key: importlib.metadata.version(key) for key in ('numpy','pandas','pyarrow','tqdm')}
    versions['opencv'] = cv2.__version__
    versions['cupy'] = None if cp is None else cp.__version__
    versions['gpu_import_errors'] = copy.deepcopy(S7_GPU_IMPORT_ERRORS)
    for prefix in ('nvidia-nvimgcodec', 'nvidia-nvjpeg'):
        installed = {}
        for family in ('cu12', 'cu13'):
            distribution = f'{prefix}-{family}'
            try:
                installed[distribution] = importlib.metadata.version(distribution)
            except importlib.metadata.PackageNotFoundError:
                pass
        versions[prefix] = installed
    versions['python'] = platform.python_version()
    return versions

def io_mount_storage(bootstrap):
    """Mount Google Drive when requested; support already mounted local copies."""
    if bootstrap.get('mount_google_drive',False):
        if drive is None:
            if not Path(bootstrap['storage_root']).is_dir():
                raise RuntimeError('Open in Colab or select an existing mounted storage_root.')
        else:
            drive.mount('/content/drive',force_remount=False)
    if not Path(bootstrap['storage_root']).is_dir():
        raise FileNotFoundError('storage_root does not exist; mount/copy the saved Sector 2–6 outputs first.')

# Source identities come from the pinned, checked S5/S6 metadata, never from new bytes.

def _s7s_digest(value, field):
    if not isinstance(value, str) or re.fullmatch(r'[0-9a-f]{64}', value) is None:
        raise ValueError(f'Missing or invalid committed SHA-256 in {field}.')
    return value


def _s7s_relative(value):
    if not isinstance(value, str) or not value or '\\' in value:
        raise ValueError(f'Invalid image-relative path: {value!r}')
    parts = value.split('/')
    if PurePosixPath(value).is_absolute() or any(p in {'', '.', '..', '.git'} for p in parts):
        raise ValueError(f'Unsafe image-relative path: {value!r}')
    return value


def _s7s_integer(value, field, minimum=None):
    if isinstance(value, (bool, np.bool_)) or pd.isna(value):
        raise ValueError(f'Invalid integer in {field}.')
    number = int(value)
    if value != number or (minimum is not None and number < minimum):
        raise ValueError(f'Invalid integer in {field}.')
    return number


def _s7s_json(value):
    return json.dumps(value, ensure_ascii=False, allow_nan=False, sort_keys=True, separators=(',', ':'))


def build_sector7_source_expectations(inputs, image_inventory, config):
    """Cross-check all image identities and hashes, including labelled frames outside S6."""
    labelled = inputs['sector5']['labelled_frame_manifest_with_segments']
    sector6 = inputs['sector6']
    temporal, audit = sector6['temporal_manifest'], sector6['temporal_image_audit']
    extracted, requests = sector6['extracted_temporal_frames'], sector6['temporal_extraction_requests']
    qc_require_columns(image_inventory, ['image_relpath', 'image_path', 'video_key', 'opencv_frame_index'], 'QC inventory')
    qc_require_columns(labelled, ['image_relpath', 'video_key', 'opencv_frame_index',
        'source_image_sha256', 'source_image_size_bytes', 'source_video_sha256'], 'S5 source images')
    qc_require_columns(temporal, ['context_image_relpath', 'video_key', 'opencv_frame_index',
        'image_sha256', 'context_image_source', 'frame_index_offset', 'extracted_image_relpath',
        'extracted_image_sha256', 'source_video_sha256', 'decoder_backend'], 'S6 source references')
    qc_require_columns(audit, ['context_image_relpath', 'image_sha256', 'image_readable'], 'S6 image audit')
    qc_require_columns(extracted, ['extracted_image_relpath', 'video_key', 'opencv_frame_index',
        'extracted_image_sha256', 'source_video_sha256', 'decoder_backend', 'extraction_status'], 'S6 extracted images')
    qc_require_columns(requests, ['output_relpath', 'video_key', 'opencv_frame_index', 'frame_index_offset'], 'S6 extraction requests')
    if not image_inventory['image_relpath'].is_unique or not image_inventory['image_path'].is_unique:
        raise ValueError('QC inventory must have unique file identities and paths.')
    expected, video_hashes = {}, {}

    def add(relative, video_key, frame_index, digest, authority, byte_count=None):
        relative = _s7s_relative(relative)
        if not isinstance(video_key, str) or not video_key:
            raise ValueError(f'Missing physical video identity: {relative}')
        index = _s7s_integer(frame_index, 'opencv_frame_index', 0)
        digest = _s7s_digest(digest, f'{authority}/{relative}')
        size = None if byte_count is None or pd.isna(byte_count) else _s7s_integer(byte_count, 'source_image_size_bytes', 1)
        old = expected.get(relative)
        if old is not None:
            if (old['video_key'], old['opencv_frame_index'], old['expected_sha256']) != (video_key, index, digest):
                raise ValueError(f'Conflicting committed image identity or SHA-256: {relative}')
            if old['expected_bytes'] is not None and size is not None and old['expected_bytes'] != size:
                raise ValueError(f'Conflicting committed image byte count: {relative}')
            if size is not None:
                old['expected_bytes'] = size
            old['authorities'].add(authority)
        else:
            expected[relative] = {'image_relpath': relative, 'video_key': video_key,
                'opencv_frame_index': index, 'expected_sha256': digest, 'expected_bytes': size,
                'authorities': {authority}, 'expected_provenance_json': None}

    columns = ['image_relpath', 'video_key', 'opencv_frame_index', 'source_image_sha256',
               'source_image_size_bytes', 'source_video_sha256']
    for row in labelled[columns].drop_duplicates().itertuples(index=False):
        add(row.image_relpath, row.video_key, row.opencv_frame_index,
            row.source_image_sha256, 'sector5', row.source_image_size_bytes)
        digest = _s7s_digest(row.source_video_sha256, f'S5 source video {row.video_key}')
        if row.video_key in video_hashes and video_hashes[row.video_key] != digest:
            raise ValueError(f'Conflicting committed source-video SHA-256: {row.video_key}')
        video_hashes[row.video_key] = digest

    audit_by_path = {}
    for row in audit[['context_image_relpath', 'image_sha256', 'image_readable']].itertuples(index=False):
        rel = _s7s_relative(row.context_image_relpath)
        if rel in audit_by_path:
            raise ValueError(f'Duplicate S6 image audit path: {rel}')
        if not isinstance(row.image_readable, (bool, np.bool_)) or not row.image_readable:
            raise ValueError(f'S6 has not completed its readable-image audit: {rel}')
        audit_by_path[rel] = _s7s_digest(row.image_sha256, f'S6 audit {rel}')
    source_config = inputs.get('sector6_config', {})
    source_lineage = inputs.get('sector6_lineage', {})
    temporal_paths, extracted_paths, temporal_extraction_identity = set(), set(), {}
    tcols = ['context_image_relpath', 'video_key', 'opencv_frame_index', 'image_sha256', 'context_image_source',
             'frame_index_offset', 'extracted_image_relpath', 'extracted_image_sha256', 'source_video_sha256', 'decoder_backend']
    for row in temporal[tcols].drop_duplicates().itertuples(index=False):
        rel = _s7s_relative(row.context_image_relpath)
        if audit_by_path.get(rel) != row.image_sha256:
            raise ValueError(f'S6 temporal reference and image audit disagree: {rel}')
        if row.context_image_source == 'official_labelled_image':
            if rel not in expected or 'sector5' not in expected[rel]['authorities']:
                raise ValueError(f'S6 official image has no authoritative S5 source: {rel}')
        elif row.context_image_source == 'extracted_from_video':
            if (pd.isna(row.extracted_image_relpath) or row.extracted_image_relpath != rel
                    or pd.isna(row.extracted_image_sha256) or row.extracted_image_sha256 != row.image_sha256
                    or pd.isna(row.source_video_sha256) or row.source_video_sha256 != video_hashes.get(str(row.video_key))
                    or pd.isna(row.decoder_backend) or row.decoder_backend != source_config.get('temporal_context_decoder')):
                raise ValueError(f'S6 temporal extraction provenance disagrees with its published sources: {rel}')
            identity = (str(row.video_key), _s7s_integer(row.opencv_frame_index, 'temporal frame', 0),
                        _s7s_integer(row.frame_index_offset, 'temporal extraction offset'))
            if rel in temporal_extraction_identity and temporal_extraction_identity[rel] != identity:
                raise ValueError(f'Conflicting S6 temporal extraction frame identities: {rel}')
            temporal_extraction_identity[rel] = identity
            extracted_paths.add(rel)
        else:
            raise ValueError(f'S6 image source is not a completed materialization: {rel}')
        add(rel, row.video_key, row.opencv_frame_index, row.image_sha256, 'sector6')
        temporal_paths.add(rel)
    if temporal_paths != set(audit_by_path):
        raise ValueError('S6 image audit coverage disagrees with its temporal references.')

    request_map = {}
    for row in requests[['output_relpath', 'video_key', 'opencv_frame_index', 'frame_index_offset']].itertuples(index=False):
        rel = _s7s_relative(row.output_relpath)
        if rel in request_map:
            raise ValueError(f'Duplicate S6 extraction request path: {rel}')
        request_map[rel] = (str(row.video_key), _s7s_integer(row.opencv_frame_index, 'request frame', 0),
                            _s7s_integer(row.frame_index_offset, 'request offset'))
        if temporal_extraction_identity.get(rel) != request_map[rel]:
            raise ValueError(f'S6 temporal extraction and request identities disagree: {rel}')
    if set(request_map) != extracted_paths:
        raise ValueError('S6 extraction requests do not cover exactly the video-derived context files.')

    if extracted_paths:
        decoder_signature = _s7s_digest(source_lineage.get('decoder_signature'), 'S6 decoder signature')
        nvdec_runtime = source_lineage.get('nvdec_runtime')
        if not isinstance(nvdec_runtime, dict) or not nvdec_runtime:
            raise ValueError('S6 extracted images require committed NVDEC runtime provenance.')
    extracted_seen = set()
    for row in extracted.itertuples(index=False):
        rel = _s7s_relative(row.extracted_image_relpath)
        if rel in extracted_seen or rel not in extracted_paths:
            raise ValueError(f'Unexpected or duplicate S6 extraction result: {rel}')
        extracted_seen.add(rel)
        if row.extraction_status not in {'success', 'reused'}:
            raise ValueError(f'S6 extraction is not complete: {rel}')
        identity = request_map[rel]
        if identity[:2] != (str(row.video_key), _s7s_integer(row.opencv_frame_index, 'physical frame', 0)):
            raise ValueError(f'S6 extraction request/result physical identity mismatch: {rel}')
        source_sha = _s7s_digest(row.source_video_sha256, f'S6 source video {row.video_key}')
        if video_hashes.get(str(row.video_key)) != source_sha:
            raise ValueError(f'S6 extraction source video disagrees with S5 provenance: {rel}')
        backend = source_config.get('temporal_context_decoder')
        if row.decoder_backend != backend or backend != 'nvdec':
            raise ValueError(f'S6 extraction backend disagrees with its committed configuration: {rel}')
        extension = PurePosixPath(rel).suffix.lower()
        declared_extension = '.' + str(source_config.get('temporal_context_image_format', '')).lower().lstrip('.')
        if extension != declared_extension:
            raise ValueError(f'S6 extraction format disagrees with its configuration: {rel}')
        if extension in {'.jpg', '.jpeg'}:
            encoding = [int(cv2.IMWRITE_JPEG_QUALITY), _s7s_integer(source_config.get('temporal_context_jpeg_quality'), 'JPEG quality', 1)]
        elif extension == '.png':
            encoding = [int(cv2.IMWRITE_PNG_COMPRESSION), _s7s_integer(source_config.get('temporal_context_png_compression'), 'PNG compression', 0)]
        else:
            raise ValueError(f'Unsupported S6 extraction format: {extension}')
        add(rel, str(row.video_key), row.opencv_frame_index, row.extracted_image_sha256, 'sector6_extraction')
        expected[rel]['expected_provenance_json'] = _s7s_json({
            'schema_version': 1, 'image_sha256': row.extracted_image_sha256,
            'identity': {'schema_version': 1, 'source_video_sha256': source_sha,
                'video_key': identity[0], 'opencv_frame_index': identity[1], 'frame_index_offset': identity[2],
                'decoder_backend': backend, 'decoder_signature': decoder_signature,
                'nvdec_runtime': nvdec_runtime, 'encoding_extension': extension, 'encoding_parameters': encoding}})
    if extracted_seen != extracted_paths:
        raise ValueError('S6 extraction results do not cover all video-derived context images.')

    if set(image_inventory['image_relpath']) != set(expected):
        raise ValueError('QC image inventory does not cover exactly all S5/S6 image files.')
    rows = []
    storage_root = Path(config['storage_root']).expanduser().resolve()
    for row in image_inventory.itertuples(index=False):
        item = expected[row.image_relpath]
        if (str(row.video_key), _s7s_integer(row.opencv_frame_index, 'physical frame', 0)) != (item['video_key'], item['opencv_frame_index']):
            raise ValueError(f'QC inventory physical identity disagrees with committed sources: {row.image_relpath}')
        expected_path = storage_root.joinpath(*PurePosixPath(row.image_relpath).parts)
        if Path(str(row.image_path)) != expected_path:
            raise ValueError(f'QC image access path disagrees with its portable identity: {row.image_relpath}')
        rows.append({**{k: v for k, v in item.items() if k != 'authorities'},
            'image_path': str(expected_path), 'expected_hash_sources_json': _s7s_json(sorted(item['authorities']))})
    columns = ['image_relpath', 'video_key', 'opencv_frame_index', 'expected_sha256', 'expected_bytes',
               'expected_provenance_json', 'image_path', 'expected_hash_sources_json']
    result = pd.DataFrame.from_records(rows, columns=columns)
    for col in columns:
        result[col] = result[col].astype('Int64' if col in {'opencv_frame_index', 'expected_bytes'} else 'string')
    return result


def _s7s_safe_file(root, relative):
    root = Path(root).expanduser().absolute()
    relative = _s7s_relative(relative)
    # Reject even an in-root symlink: every access path has one physical meaning.
    for parent in (root, *root.parents):
        if parent.is_symlink():
            raise ValueError(f'Symlink storage root is unsupported: {parent}')
    candidate = root
    for part in PurePosixPath(relative).parts:
        candidate = candidate / part
        if candidate.is_symlink():
            raise ValueError(f'Symlink image path is unsupported: {candidate}')
    candidate.resolve().relative_to(root.resolve())
    return candidate


def _s7s_stat(path):
    st = Path(path).stat()
    if not stat.S_ISREG(st.st_mode):
        raise RuntimeError(f'Source is not a regular file: {path}')
    return st.st_size, st.st_mtime_ns, st.st_ctime_ns, st.st_ino


def _s7s_hash_file(path, max_bytes):
    """Read bounded bytes once and reject a concurrent file replacement."""
    before = _s7s_stat(path)
    if before[0] > max_bytes:
        raise RuntimeError(f'Image/source exceeds its configured byte limit: {path}')
    h, count = hashlib.sha256(), 0
    with Path(path).open('rb') as handle:
        for block in iter(lambda: handle.read(4 * 1024 * 1024), b''):
            count += len(block)
            if count > max_bytes:
                raise RuntimeError(f'Source grew beyond its configured byte limit: {path}')
            h.update(block)
    if count != before[0] or _s7s_stat(path) != before:
        raise RuntimeError(f'Source changed during SHA-256 verification: {path}')
    return h.hexdigest(), count


def _s7s_provenance(payload, expected_json, image_relative):
    """Validate committed image/source identity; OpenCV version is informational."""
    try:
        proof, expected = json.loads(payload.decode('utf-8')), json.loads(expected_json)
    except (UnicodeDecodeError, json.JSONDecodeError, TypeError) as error:
        raise ValueError(f'Invalid extraction provenance: {image_relative}') from error
    if not isinstance(proof, dict) or type(proof.get('schema_version')) is not int or proof.get('schema_version') != expected['schema_version'] or proof.get('image_sha256') != expected['image_sha256']:
        raise ValueError(f'Extraction provenance image/hash mismatch: {image_relative}')
    identity = proof.get("identity")
    if not isinstance(identity, dict):
        raise ValueError(
            f"Extraction provenance identity is missing: {image_relative}"
        )

    informational_fields = {"opencv_version", "decoder_signature", "nvdec_runtime"}

    required_identity = {
        key: value
        for key, value in expected["identity"].items()
        if key not in informational_fields
    }

    mismatches = [
        key
        for key, value in required_identity.items()
        if key not in identity
        or _s7s_json(identity[key]) != _s7s_json(value)
    ]

    if mismatches:
        raise ValueError(
            f"Extraction provenance identity mismatch "
            f"({', '.join(sorted(mismatches))}): {image_relative}"
        )
    return proof



def _s7s_read_provenance(path, expected_json, relative):
    """Parse and hash the same bounded sidecar bytes once."""
    before = _s7s_stat(path)
    if before[0] > 1024 * 1024:
        raise ValueError(f'Invalid or oversized extraction provenance: {relative}')
    with Path(path).open('rb') as handle:
        payload = handle.read(1024 * 1024 + 1)
    if len(payload) != before[0] or _s7s_stat(path) != before:
        raise RuntimeError(f'Extraction provenance changed during verification: {relative}')
    _s7s_provenance(payload, expected_json, relative)
    return hashlib.sha256(payload).hexdigest(), len(payload)


def _s7s_staging_workers(config):
    """Use dedicated copy concurrency; retain legacy qc_workers fallback."""
    value = config.get('qc_staging_workers', config.get('qc_workers', 16))
    if isinstance(value, bool) or not isinstance(value, (int, np.integer)) or value < 1:
        raise ValueError('qc_staging_workers must be a positive integer.')
    return int(value)


def _s7s_atomic_copy(source, destination, expected_sha, expected_bytes, config, provenance_json=None):
    """Hash a single Drive-to-SSD copy, then atomically install verified bytes."""
    maximum = int(config.get('qc_max_image_bytes', 64 * 1024 * 1024)) if provenance_json is None else 1024 * 1024
    reserve = int(config.get('qc_staging_reserve_bytes', 2 * 1024 ** 3))
    workers = _s7s_staging_workers(config)
    destination.parent.mkdir(parents=True, exist_ok=True)
    if shutil.disk_usage(destination.parent).free < reserve + maximum * workers:
        raise OSError('Insufficient SSD space for bounded concurrent staging and the reserved free space.')
    before = _s7s_stat(source)
    if before[0] > maximum:
        raise RuntimeError(f'Source is not a regular bounded file: {source}')
    if expected_bytes is not None and before[0] != expected_bytes:
        raise RuntimeError(f'Committed source byte count mismatch: {source}')
    fd, temporary = tempfile.mkstemp(prefix='.' + destination.name + '-', suffix='.part', dir=destination.parent)
    digest, count, proof_bytes = hashlib.sha256(), 0, bytearray()
    try:
        with os.fdopen(fd, 'wb') as dst, source.open('rb') as src:
            for block in iter(lambda: src.read(4 * 1024 * 1024), b''):
                count += len(block)
                if count > maximum:
                    raise RuntimeError(f'Source grew beyond its configured byte limit: {source}')
                digest.update(block)
                dst.write(block)
                if provenance_json is not None:
                    proof_bytes.extend(block)
            dst.flush()
            os.fsync(dst.fileno())
        actual = digest.hexdigest()
        if count != before[0] or _s7s_stat(source) != before:
            raise RuntimeError(f'Source changed during staging: {source}')
        if expected_sha is not None and actual != expected_sha:
            raise RuntimeError(f'Committed SHA-256 mismatch: {source}; restore the published source bytes or rerun its producer.')
        if provenance_json is not None:
            _s7s_provenance(bytes(proof_bytes), provenance_json, str(destination))
        written_sha, written_bytes = _s7s_hash_file(Path(temporary), maximum)
        if written_sha != actual or written_bytes != count:
            raise RuntimeError(f'SSD destination verification failed: {destination}')
        os.replace(temporary, destination)
        return actual, count
    finally:
        # The installed destination survives interruptions; an unfinished temp file is never evidence.
        if os.path.exists(temporary):
            os.unlink(temporary)


def _s7s_stage_image(row, drive_root, local_root, config):
    relative = row.image_relpath
    local = _s7s_safe_file(local_root, relative)
    expected_bytes = None if pd.isna(row.expected_bytes) else int(row.expected_bytes)
    maximum = int(config.get('qc_max_image_bytes', 64 * 1024 * 1024))
    reused = False
    if local.is_file():
        try:
            digest, count = _s7s_hash_file(local, maximum)
            reused = digest == row.expected_sha256 and (expected_bytes is None or count == expected_bytes)
        except (OSError, RuntimeError):
            reused = False
    if not reused:
        source = _s7s_safe_file(drive_root, relative)
        digest, count = _s7s_atomic_copy(source, local, row.expected_sha256, expected_bytes, config)
    proof_local, proof_sha = pd.NA, pd.NA
    if pd.notna(row.expected_provenance_json):
        proof_rel = relative + '.provenance.json'
        proof_local = _s7s_safe_file(local_root, proof_rel)
        proof_reused = False
        if proof_local.is_file():
            try:
                proof_sha, _ = _s7s_read_provenance(proof_local, row.expected_provenance_json, relative)
                proof_reused = True
            except (OSError, RuntimeError, ValueError):
                proof_reused = False
        if not proof_reused:
            proof_source = _s7s_safe_file(drive_root, proof_rel)
            proof_sha, _ = _s7s_atomic_copy(proof_source, proof_local, None, None, config, row.expected_provenance_json)
        proof_local = str(proof_local)
    record = {'image_path': row.image_path, 'image_relpath': relative,
        'video_key': row.video_key, 'opencv_frame_index': row.opencv_frame_index,
        'local_image_path': str(local), 'image_sha256': digest, 'image_bytes': count,
        'expected_sha256': row.expected_sha256, 'expected_bytes': row.expected_bytes,
        'expected_hash_sources_json': row.expected_hash_sources_json,
        'source_status': 'verified', 'source_matches_upstream': True,
        'source_error': pd.NA, 'local_provenance_path': proof_local, 'provenance_sha256': proof_sha,
        'expected_provenance_json': row.expected_provenance_json}
    return record, reused


def io_audit_sector7_sources(image_inventory, inputs, config):
    """Stage once from Drive and compare all image bytes to committed S5/S6 SHA-256."""
    expected = build_sector7_source_expectations(inputs, image_inventory, config)
    drive_root = Path(config['storage_root']).expanduser().absolute()
    local_root = Path(config['sector7']['local_workspace_root']).expanduser().absolute()
    resolved_drive, resolved_local = drive_root.resolve(), local_root.resolve()
    if resolved_drive == resolved_local or resolved_drive in resolved_local.parents or resolved_local in resolved_drive.parents:
        raise ValueError('S7 SSD workspace and persistent storage root must be separate directories.')
    _s7s_safe_file(drive_root, '.s7_root_probe')
    _s7s_safe_file(local_root, '.s7_root_probe')
    local_root.mkdir(parents=True, exist_ok=True)
    for name, minimum in [('qc_workers', 1), ('qc_max_image_bytes', 1), ('qc_staging_reserve_bytes', 0)]:
        _s7s_integer(config.get(name, {'qc_workers': 16, 'qc_max_image_bytes': 64 * 1024 * 1024, 'qc_staging_reserve_bytes': 2 * 1024 ** 3}[name]), name, minimum)
    workers = _s7s_staging_workers(config)
    def stage(row):
        return _s7s_stage_image(row, drive_root, local_root, config)
    # Limit submitted work; update progress on completion, not input order.
    # Preserve input order in the final audit so hashes remain deterministic.
    staged = [None] * len(expected)
    rows = iter(enumerate(expected.itertuples(index=False)))
    pending = {}
    completed = reused_count = 0
    executor = ThreadPoolExecutor(max_workers=workers)
    started = time.monotonic()
    try:
        with tqdm(total=len(expected), desc=f'Verify/stage S7 on SSD ({workers} workers)', unit='image') as progress:
            while True:
                while len(pending) < workers * 2:
                    item = next(rows, None)
                    if item is None:
                        break
                    index, row = item
                    pending[executor.submit(stage, row)] = index
                if not pending:
                    break
                done, _ = wait(pending, return_when=FIRST_COMPLETED)
                for future in done:
                    index = pending.pop(future)
                    result = future.result()
                    staged[index] = result
                    completed += 1
                    reused_count += int(result[1])
                    progress.update(1)
                progress.set_postfix(reused=reused_count, copied=completed - reused_count, refresh=False)
    finally:
        # Stop queued work on failure/interrupt; drain active atomic writes before retry.
        for future in pending:
            future.cancel()
        executor.shutdown(wait=True, cancel_futures=True)
    elapsed = time.monotonic() - started
    columns = ['image_path', 'image_relpath', 'video_key', 'opencv_frame_index', 'local_image_path',
        'image_sha256', 'image_bytes', 'expected_sha256', 'expected_bytes', 'expected_hash_sources_json',
        'source_status', 'source_matches_upstream', 'source_error', 'local_provenance_path',
        'provenance_sha256', 'expected_provenance_json']
    audit = pd.DataFrame.from_records([record for record, _ in staged], columns=columns)
    for column in columns:
        dtype = 'Int64' if column in {'opencv_frame_index', 'image_bytes', 'expected_bytes'} else 'boolean' if column == 'source_matches_upstream' else 'string'
        audit[column] = audit[column].astype(dtype)
    print(f'S7 source integrity passed: {len(staged)} images; {reused_count} verified SSD images reused; '
          f'{len(staged) - reused_count} images copied; {workers} staging workers; '
          f'{len(staged) / max(elapsed, 1e-9):.2f} images/s.')
    return audit


def io_validate_sector7_source_audit(audit):
    """Validate the SSD snapshot actually decoded; never rehash the mounted Drive set."""
    qc_require_columns(audit, ['image_relpath', 'local_image_path', 'image_sha256', 'image_bytes',
        'expected_sha256', 'source_status', 'source_matches_upstream', 'local_provenance_path',
        'provenance_sha256', 'expected_provenance_json'], 'S7 source audit')
    if not audit['image_relpath'].is_unique:
        raise ValueError('S7 source audit contains duplicate file identities.')
    for row in tqdm(
        audit.itertuples(index=False),
        total=len(audit),
        desc="S7 | Verify SHA-256 SSD images",
        unit="image",
        dynamic_ncols=True,
    ):
        rel = _s7s_relative(row.image_relpath)
        if row.source_status != 'verified' or pd.isna(row.source_matches_upstream) or not bool(row.source_matches_upstream):
            raise RuntimeError(f'Unverified image cannot be persisted: {rel}')
        expected = _s7s_digest(row.expected_sha256, rel)
        path = Path(row.local_image_path)
        root = path.parents[len(PurePosixPath(rel).parts) - 1]
        if _s7s_safe_file(root, rel) != path:
            raise ValueError(f'Local image path disagrees with portable identity: {rel}')
        digest, count = _s7s_hash_file(path, int(row.image_bytes))
        if digest != expected or digest != row.image_sha256 or count != int(row.image_bytes):
            raise RuntimeError(f'QC source snapshot changed after staging: {rel}; rerun source staging.')
        if pd.notna(row.expected_provenance_json):
            sidecar = _s7s_safe_file(root, rel + '.provenance.json')
            if str(sidecar) != row.local_provenance_path:
                raise RuntimeError(f'Local provenance path changed: {rel}')
            digest, _ = _s7s_read_provenance(sidecar, row.expected_provenance_json, rel)
            if digest != row.provenance_sha256:
                raise RuntimeError(f'Extraction provenance changed after staging: {rel}')
    return True


def add_qc_source_status(qc_manifest, image_audit):
    """Require metrics to describe exactly the hash-verified snapshot, including decode errors."""
    required = ['image_relpath', 'image_sha256']
    qc_require_columns(qc_manifest, required, 'QC metric manifest')
    qc_require_columns(image_audit, required + ['source_matches_upstream'], 'S7 source audit')
    if not qc_manifest.image_relpath.is_unique or not image_audit.image_relpath.is_unique or set(qc_manifest.image_relpath) != set(image_audit.image_relpath):
        raise RuntimeError('QC metrics and source audit must have identical image coverage.')
    extra = image_audit[['image_relpath', 'image_sha256', 'source_matches_upstream']].rename(
        columns={'image_sha256': 'qc_verified_source_sha256', 'source_matches_upstream': 'qc_source_matches_upstream'})
    result = qc_manifest.merge(extra, on='image_relpath', how='left', sort=False, validate='one_to_one')
    if result.image_sha256.isna().any() or result.image_sha256.ne(result.qc_verified_source_sha256).fillna(True).any() or not result.qc_source_matches_upstream.fillna(False).all():
        raise RuntimeError('An image changed or became unreadable between source staging and QC decoding; rerun S7.')
    result['qc_source_matches_upstream'] = result['qc_source_matches_upstream'].astype('boolean')
    return result


def build_sector7_summary(tables):
    """QC completion certifies material analysis, never a final training partition."""
    summary = tables['image_qc_summary'].iloc[0].to_dict()
    return {
        'schema_version': 2, 'phase': 2, 'sector': 7,
        'training_ready': False, 'split_policy': 'deferred',
        'split_assignment_status': 'pending',
        'qc_assessment_status': 'metrics_only_final_split_pending',
        'material_validation_passed': True,
        'table_row_counts': {name: len(frame) for name, frame in tables.items()},
        'qc': summary,
        'threshold_fit_policy': 'deferred_until_validated_final_split',
        'annotation_semantics': 'Every source annotation and temporal reference is preserved; unlabelled is not normal.',
        'quality_semantics': 'Technical pixel metrics and read-failure flags; no clinical labels or model-readiness guarantee.',
    }


def _s7_checkpoint_root(config, signature):
    if not isinstance(signature, str) or re.fullmatch(r'[0-9a-f]{64}', signature) is None:
        raise ValueError('QC checkpoint identity must be a processing SHA-256.')
    root = Path(config['sector7']['local_workspace_root']).expanduser().resolve()
    folder = root / '.qc_checkpoints' / signature
    # No source-controlled path component is accepted for checkpoint filenames.
    for candidate in (root / '.qc_checkpoints', folder):
        if candidate.is_symlink():
            raise ValueError('QC checkpoint directories cannot be symlinks.')
    folder.mkdir(parents=True, exist_ok=True)
    return folder


def _s7_checkpoint_identity(inventory, audit, signature):
    proof = audit.set_index('image_relpath')
    return _p3_json_hash({
        'schema_version': 1, 'processing_signature': signature,
        'inventory_fingerprint': sector3_table_fingerprint(inventory),
        'sources': [{
            'image_relpath': row.image_relpath,
            'image_sha256': str(proof.loc[row.image_relpath, 'image_sha256']),
        } for row in inventory.itertuples(index=False)],
    })


def _s7_validate_checkpoint_metrics(metrics, inventory, audit):
    columns = IMAGE_QC_INVENTORY_COLUMNS + [key for key in IMAGE_QC_COLUMNS if key != 'image_path']
    if list(metrics.columns) != columns or len(metrics) != len(inventory):
        raise ValueError('QC checkpoint column/row coverage changed.')
    pd.testing.assert_frame_equal(metrics[IMAGE_QC_INVENTORY_COLUMNS].reset_index(drop=True),
                                  inventory[IMAGE_QC_INVENTORY_COLUMNS].reset_index(drop=True),
                                  check_exact=True, check_dtype=True)
    expected = audit.set_index('image_relpath')['image_sha256'].reindex(metrics['image_relpath'])
    if metrics['image_sha256'].isna().any() or not np.array_equal(
            metrics['image_sha256'].astype(str).to_numpy(), expected.astype(str).to_numpy()):
        raise RuntimeError('QC checkpoint/decoder hashes disagree with the verified source snapshot.')
    if str(metrics['image_readable'].dtype) != 'boolean' or metrics['image_readable'].isna().any():
        raise ValueError('QC checkpoint readability must be a non-null boolean.')
    return metrics


def io_read_sector7_checkpoint(folder, identity, inventory, audit):
    """A corrupt disposable batch is recomputed; source-integrity failures stay fatal."""
    metadata_path, table_path = folder / (identity + '.json'), folder / (identity + '.parquet')
    if not metadata_path.exists():
        return None
    try:
        if metadata_path.is_symlink() or table_path.is_symlink():
            raise ValueError('QC checkpoint files cannot be symlinks.')
        metadata = json.loads(metadata_path.read_text(encoding='utf-8'))
        if (not isinstance(metadata, dict) or metadata.get('schema_version') != 1
                or metadata.get('identity') != identity or metadata.get('complete') is not True):
            raise ValueError('Incomplete or incompatible QC checkpoint.')
        if _p3_file_hash(table_path) != metadata.get('table_sha256'):
            raise ValueError('QC checkpoint byte checksum is invalid.')
        metrics = pd.read_parquet(table_path, engine='pyarrow')
        if sector3_table_fingerprint(metrics) != metadata.get('table_fingerprint'):
            raise ValueError('QC checkpoint table fingerprint is invalid.')
        return _s7_validate_checkpoint_metrics(metrics, inventory, audit)
    except (ValueError, RuntimeError, KeyError, TypeError, FileNotFoundError, AssertionError) as error:
        print(f'Recomputing invalid QC batch {identity[:12]}: {type(error).__name__}')
        return None


def io_write_sector7_checkpoint(folder, identity, metrics):
    """Verify a complete Parquet part, then atomically publish its completion record."""
    stage = Path(tempfile.mkdtemp(prefix='.part-', dir=folder))
    try:
        table = stage / (identity + '.parquet')
        metrics.to_parquet(table, index=False, compression='zstd', engine='pyarrow')
        validate_persisted_dataframe(metrics, table, 'QC checkpoint batch')
        record = {'schema_version': 1, 'identity': identity, 'complete': True,
                  'table_sha256': _p3_file_hash(table),
                  'table_fingerprint': sector3_table_fingerprint(metrics)}
        metadata = stage / (identity + '.json')
        _p7_write_json(metadata, record)
        for path in (table, metadata):
            with path.open('rb') as stream:
                os.fsync(stream.fileno())
        os.replace(table, folder / table.name)
        os.replace(metadata, folder / metadata.name)  # Completion record is always last.
    finally:
        shutil.rmtree(stage, ignore_errors=True)


def io_compute_sector7_checkpointed_metrics(inventory, source_audit, config, runtime,
                                            checkpoint_signature=None):
    """Read/decode SSD bytes; stable output paths still refer to persistent media."""
    size = config.get('qc_checkpoint_batch_size', 1000)
    if isinstance(size, bool) or not isinstance(size, (int, np.integer)) or not 1 <= size <= 10000:
        raise ValueError('qc_checkpoint_batch_size must be an integer in 1..10000.')
    proof = source_audit.set_index('image_relpath')
    if not proof.index.is_unique or set(proof.index) != set(inventory['image_relpath']):
        raise ValueError('Source audit must cover the exact unique QC image inventory.')
    folder = None if checkpoint_signature is None else _s7_checkpoint_root(config, checkpoint_signature)
    parts, reused, computed = [], 0, 0
    for start in tqdm(range(0, len(inventory), int(size)), desc='Resumable QC parts'):
        batch = inventory.iloc[start:start + int(size)].reset_index(drop=True)
        identity = _s7_checkpoint_identity(batch, source_audit, checkpoint_signature)
        metrics = None if folder is None else io_read_sector7_checkpoint(folder, identity, batch, source_audit)
        if metrics is None:
            local = batch.copy()
            local['image_path'] = local['image_relpath'].map(proof['local_image_path']).astype('string')
            if local['image_path'].isna().any() or not local['image_path'].is_unique:
                raise ValueError('Each QC image needs one distinct verified local SSD path.')
            metrics = io_compute_qc_for_image_inventory(local, config, runtime=runtime)
            # Metric hashes bind exactly the encoded bytes fed to the decoder.
            persistent = batch.set_index('image_relpath')['image_path']
            metrics['image_path'] = metrics['image_relpath'].map(persistent).astype('string')
            _s7_validate_checkpoint_metrics(metrics, batch, source_audit)
            if folder is not None:
                io_write_sector7_checkpoint(folder, identity, metrics)
            computed += len(batch)
        else:
            reused += len(batch)
        parts.append(metrics)
    runtime['checkpoint_reused_images'] = reused
    runtime['checkpoint_computed_images'] = computed
    columns = IMAGE_QC_INVENTORY_COLUMNS + [name for name in IMAGE_QC_COLUMNS if name != 'image_path']
    return pd.concat(parts, ignore_index=True) if parts else qc_empty_table(columns)


def io_compute_sector7_tables(inputs, config, inventory, source_audit, runtime=None,
                              checkpoint_signature=None):
    """Compose immutable source references, technical metrics and deferred readiness."""
    labelled = inputs['sector5']['labelled_frame_manifest_with_segments']
    temporal = inputs['sector6']['temporal_manifest']
    execution = io_create_sector7_gpu_runtime(config) if runtime is None else runtime
    metrics = io_compute_sector7_checkpointed_metrics(inventory, source_audit, config, execution,
                                                     checkpoint_signature)
    thresholds = derive_image_qc_thresholds(metrics, config)
    qc = add_qc_source_status(add_image_qc_flags(metrics, thresholds), source_audit)
    enriched = attach_image_qc_to_manifests(labelled, temporal, qc, config)
    reports = build_qc_reference_reports(labelled, temporal, qc, config)
    tables = {
        'image_qc_inventory': inventory, 'image_qc_manifest': qc,
        'image_qc_thresholds': thresholds, 'image_qc_source_audit': source_audit,
        'labelled_frame_manifest_with_qc': enriched['labelled_frame_manifest_with_qc'],
        'temporal_manifest_with_qc': enriched['temporal_manifest_with_qc'],
        'image_qc_summary': build_image_qc_summary(qc, thresholds, reports, config),
        'image_read_failure_report': reports['image_read_failure_report'],
        'qc_reference_report': reports['qc_reference_report'],
        'missing_image_reference_report': reports['missing_image_reference_report'],
    }
    if len(tables['labelled_frame_manifest_with_qc']) != len(labelled) or len(
            tables['temporal_manifest_with_qc']) != len(temporal):
        raise RuntimeError('QC enrichment must preserve every annotation and temporal reference.')
    return tables


def io_prepare_sector7(inputs, config, lineage, namespace):
    """Verify/stage once, reuse complete results or resume validated metric batches."""
    labelled = inputs['sector5']['labelled_frame_manifest_with_segments']
    temporal = inputs['sector6']['temporal_manifest']
    validate_image_qc_config(config)
    inventory = build_qc_image_inventory(labelled, temporal, config)
    source_audit = io_audit_sector7_sources(inventory, inputs, config)
    versions = io_sector7_dependency_versions()
    gpu_info = io_describe_sector7_gpu(config)
    versions['gpu_environment'] = gpu_info
    current = copy.deepcopy(lineage)
    current['core_source_sha256'] = _s3_semantic_digest({
        'inventory': sector7_runtime_core_sha256(build_qc_image_inventory, namespace, versions),
        'pipeline': sector7_runtime_core_sha256(io_compute_sector7_tables, namespace, versions),
        'gpu_runtime': sector7_runtime_core_sha256(io_create_sector7_gpu_runtime, namespace, versions),
        'source_audit': sector7_runtime_core_sha256(io_audit_sector7_sources, namespace, versions),
        'input_reader': sector7_runtime_core_sha256(io_load_sector7_context, namespace, versions),
    })
    current['dependency_versions'] = versions
    current['gpu_execution'] = gpu_info
    current['image_source_audit_sha256'] = sector3_table_fingerprint(source_audit)
    current['split_policy'] = 'deferred'
    current['split_assignment_status'] = 'pending'
    current['training_ready'] = False
    signature = sector7_processing_signature(config, current)
    cached = io_load_cached_sector7(config, signature)
    if cached is not None:
        pd.testing.assert_frame_equal(cached['tables']['image_qc_inventory'], inventory,
                                      check_exact=True, check_dtype=True)
        pd.testing.assert_frame_equal(cached['tables']['image_qc_source_audit'], source_audit,
                                      check_exact=True, check_dtype=True)
        tables, status = cached['tables'], 'reused'
        for name in ('runtime_fallback_reasons', 'decoder_mode', 'gpu_metrics_available_at_completion'):
            if name in cached['lineage']:
                current[name] = copy.deepcopy(cached['lineage'][name])
        progress = {'reused_images': len(inventory), 'computed_images': 0}
    else:
        runtime = io_create_sector7_gpu_runtime(config, gpu_info=gpu_info)
        tables = io_compute_sector7_tables(inputs, config, inventory, source_audit, runtime=runtime,
                                           checkpoint_signature=signature)
        status = 'resumed' if runtime['checkpoint_reused_images'] else 'computed'
        current['runtime_fallback_reasons'] = sorted(runtime['fallback_reasons'])
        current['decoder_mode'] = runtime['decoder_mode']
        current['gpu_metrics_available_at_completion'] = runtime['gpu_metrics_available']
        progress = {'reused_images': runtime['checkpoint_reused_images'],
                    'computed_images': runtime['checkpoint_computed_images']}
    current['backend_summary'] = tables['image_qc_summary'].iloc[0].to_dict()
    current['fallback_reasons'] = sorted(tables['image_qc_manifest']['image_fallback_reason'].dropna().unique().tolist())
    return {'tables': tables, 'lineage': current, 'processing_signature': signature,
            'status': status, 'gpu_execution': gpu_info, 'checkpoint_progress': progress}

In [34]:
class _S7CloudIdentityError(ValueError):
    """The configured path is ambiguous; do not select an arbitrary Drive ID."""


class _S7CloudSourceChanged(RuntimeError):
    """The sealed SSD bundle changed during delivery."""


def _s7c_relative(value):
    from pathlib import PurePosixPath
    if not isinstance(value, str) or not value or '\\' in value:
        raise ValueError('Sector 7 needs a nonempty POSIX relative path.')
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in ('', '.', '..') for part in value.split('/')):
        raise ValueError(f'Unsafe Sector 7 relative path: {value!r}')
    return path


def _s7c_cloud_parts(config):
    """Map the configured MyDrive project path to API folder names, without stat()."""
    from pathlib import PurePosixPath
    storage = PurePosixPath(str(config['storage_root']))
    for anchor in (PurePosixPath('/content/drive/MyDrive'),
                   PurePosixPath('/content/drive/My Drive')):
        try:
            project = storage.relative_to(anchor)
            break
        except ValueError:
            pass
    else:
        raise ValueError('Sector 7 cloud delivery expects storage_root under /content/drive/MyDrive.')
    if any(part in ('.', '..') for part in project.parts):
        raise ValueError('Unsafe Sector 7 storage_root.')
    output = _s7c_relative(config.get('sector7', {}).get(
        'local_output_dir', 'outputs/phase2/sector7'))
    return list(project.parts + output.parts)


def _s7c_stat(path):
    stat = path.stat()
    return (stat.st_dev, stat.st_ino, stat.st_size, stat.st_mtime_ns, stat.st_ctime_ns)


def _s7c_hash(path):
    import hashlib
    digest = hashlib.sha256()
    with path.open('rb') as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def _s7c_matches(record, metadata):
    if not isinstance(metadata, dict):
        return False
    try:
        return (metadata.get('mimeType') != 'application/vnd.google-apps.folder'
                and int(metadata.get('size', -1)) == record['bytes']
                and str(metadata.get('sha256Checksum', '')).lower() == record['sha256'])
    except (ValueError, TypeError):
        return False


def _s7c_pending_reason(record, metadata):
    if not isinstance(metadata, dict):
        return 'missing'
    try:
        if int(metadata.get('size', -1)) != record['bytes']:
            return 'size_mismatch'
    except (TypeError, ValueError):
        return 'size_unavailable'
    if not metadata.get('sha256Checksum'):
        return 'sha256_unavailable'
    if str(metadata['sha256Checksum']).lower() != record['sha256']:
        return 'sha256_mismatch'
    return 'type_mismatch'


class _S7DriveAPI:
    """Synchronous Drive REST uploads; no DriveFS reads or writes."""
    _base = 'https://www.googleapis.com/drive/v3'
    _upload = 'https://www.googleapis.com/upload/drive/v3'
    _folder_type = 'application/vnd.google-apps.folder'
    _fields = 'id,name,mimeType,size,sha256Checksum,modifiedTime'

    def __init__(self, session):
        self.session = session

    def _response(self, method, url, **kwargs):
        try:
            response = self.session.request(method, url, timeout=(30, 120), **kwargs)
        except Exception as exc:
            # Upload session URLs can appear in transport exception messages.
            raise RuntimeError(f'Drive API {method} transport failed: {type(exc).__name__}') from exc
        if not response.ok:
            # Do not print authenticated URLs, request headers or tokens.
            raise RuntimeError(f'Drive API {method} failed: HTTP {response.status_code}')
        return response

    def _request(self, method, url, **kwargs):
        return self._response(method, url, **kwargs).json()

    @staticmethod
    def _quote(value):
        return "'" + str(value).replace('\\', '\\\\').replace("'", "\\'") + "'"

    def _list(self, parent, name=None):
        query = f'{self._quote(parent)} in parents and trashed = false'
        if name is not None:
            query += f' and name = {self._quote(name)}'
        params = {'q': query, 'pageSize': 1000, 'spaces': 'drive',
                  'fields': f'nextPageToken,incompleteSearch,files({self._fields})'}
        result = []
        while True:
            page = self._request('GET', self._base + '/files', params=params)
            if page.get('incompleteSearch'):
                raise RuntimeError('Drive API inventory is incomplete; no missing-file decision is safe.')
            result.extend(page.get('files', []))
            token = page.get('nextPageToken')
            if not token:
                return result
            params['pageToken'] = token

    def _child(self, parent, name, *, folder, create=False):
        matches = self._list(parent, name)
        if len(matches) > 1:
            raise _S7CloudIdentityError(f'Duplicate Drive name; delivery blocked: {name}')
        if matches:
            item = matches[0]
            if (item.get('mimeType') == self._folder_type) != folder:
                raise _S7CloudIdentityError(f'Drive file/folder conflict: {name}')
            return item
        if not create:
            return None
        body = {'name': name, 'parents': [parent]}
        if folder:
            body['mimeType'] = self._folder_type
        # A failed/unknown create is never repeated here. The next outer pass
        # lists this exact path first, so an accepted create can be recovered.
        return self._request('POST', self._base + '/files',
                             params={'fields': self._fields}, json=body)

    def resolve_root(self, parts):
        parent = 'root'
        required = getattr(self, '_required_prefix_length', 1)
        for index, name in enumerate(parts):
            item = self._child(parent, name, folder=True, create=index >= required)
            if item is None:
                raise _S7CloudIdentityError(
                    f'Configured Drive project is absent: {name}; verify the authenticated account and storage_root.')
            parent = item['id']
        return parent

    def inventory(self, root_id, relatives):
        # Directory/name caches last for this scan only. Every new pass re-lists.
        directories = {'': root_id}
        listings = {}

        def listing(folder_id):
            if folder_id not in listings:
                index = {}
                for item in self._list(folder_id):
                    index.setdefault(item['name'], []).append(item)
                listings[folder_id] = index
            return listings[folder_id]

        def select(folder_id, name):
            matches = listing(folder_id).get(name, [])
            if len(matches) > 1:
                raise _S7CloudIdentityError(f'Duplicate Drive name; delivery blocked: {name}')
            return matches[0] if matches else None

        def directory(parts):
            key = '/'.join(parts)
            if key in directories:
                return directories[key]
            parent = directory(parts[:-1])
            item = None if parent is None else select(parent, parts[-1])
            if item is not None and item.get('mimeType') != self._folder_type:
                raise _S7CloudIdentityError(f'Drive folder conflict: {key}')
            directories[key] = None if item is None else item['id']
            return directories[key]

        result = {}
        for relative in relatives:
            parts = _s7c_relative(relative).parts
            folder_id = directory(parts[:-1])
            item = None if folder_id is None else select(folder_id, parts[-1])
            if item is not None and item.get('mimeType') == self._folder_type:
                raise _S7CloudIdentityError(f'Drive file conflict: {relative}')
            result[relative] = item
        return result

    def upload(self, root_id, relative, local_path, existing_metadata):
        parts = _s7c_relative(relative).parts
        parent = root_id
        for name in parts[:-1]:
            parent = self._child(parent, name, folder=True, create=True)['id']
        # Resolve immediately before writing; never trust an ID from an old scan.
        target = self._child(parent, parts[-1], folder=False, create=True)
        if existing_metadata is not None and target['id'] != existing_metadata['id']:
            raise _S7CloudIdentityError(f'Drive identity changed before upload: {relative}')
        size = local_path.stat().st_size
        # Resumable protocol is appropriate for the larger Parquet artifacts.
        # A failed/unknown transfer is reconciled through fresh API metadata before
        # another attempt; the next attempt always opens the SSD file at byte 0.
        initiation = self._response(
            'PATCH', self._upload + '/files/' + target['id'],
            params={'uploadType': 'resumable', 'fields': self._fields},
            headers={'X-Upload-Content-Type': 'application/octet-stream',
                     'X-Upload-Content-Length': str(size)}, json={})
        upload_url = initiation.headers.get('Location')
        from urllib.parse import urlsplit
        parsed = urlsplit(upload_url or '')
        if parsed.scheme != 'https' or parsed.hostname != 'www.googleapis.com':
            raise RuntimeError('Drive API did not return a trusted resumable upload URL.')
        headers = {'Content-Type': 'application/octet-stream', 'Content-Length': str(size)}
        # Each retry opens the file afresh at byte 0. AuthorizedSession is created
        # with transparent 401 retries disabled for these streaming requests.
        with local_path.open('rb') as stream:
            response = self._response('PUT', upload_url, headers=headers, data=stream)
            if response.status_code not in (200, 201):
                raise RuntimeError(f'Drive resumable upload is not complete: HTTP {response.status_code}')
        return target['id']


def _s7c_api():
    import google.auth
    from google.colab import auth
    from google.auth.transport.requests import AuthorizedSession
    auth.authenticate_user()
    credentials, _ = google.auth.default(scopes=['https://www.googleapis.com/auth/drive'])
    # No httplib2 transport, and no transparent retry of a partially read stream.
    return _S7DriveAPI(AuthorizedSession(credentials, max_refresh_attempts=0))


def io_sync_sector7_cloud(persisted, config, *, poll_seconds=15,
                         retry_seconds=90, api=None):
    """Deliver sealed SSD metadata and wait for fresh API SHA-256 confirmation.

    The catalog is uploaded last. Missing server hashes remain pending; an
    existing name or equal size alone never completes this operation.
    Interrupting leaves the journal pending, and rerunning uploads only the diff.
    """
    import json
    import os
    import re
    import time
    from datetime import datetime, timezone
    from pathlib import Path
    from collections import Counter
    from tqdm.auto import tqdm

    persisted.pop('cloud_delivery', None)
    if poll_seconds <= 0 or retry_seconds <= 0:
        raise ValueError('Cloud poll/retry intervals must be positive.')
    root_value = persisted.get('local_root', persisted.get('root'))
    if root_value is None:
        raise ValueError('Persist the Sector 7 tables on SSD before cloud delivery.')
    root = Path(root_value).expanduser().resolve()
    if root != Path(_p7_root(config)).resolve():
        raise ValueError('Persist Sector 7 again on its configured SSD root first.')
    for forbidden in (Path('/content/drive'), Path(config['storage_root']).expanduser().resolve()):
        if root == forbidden or forbidden in root.parents:
            raise ValueError('Sector 7 delivery source must be SSD, not the Drive mount.')
    cloud_parts = _s7c_cloud_parts(config)
    cloud_root = 'MyDrive/' + '/'.join(cloud_parts)
    snapshot = _p7_read_snapshot(root)
    if snapshot is None or snapshot['state'] != persisted.get('state'):
        raise RuntimeError('Sector 7 SSD snapshot changed; persist again before delivery.')
    state = snapshot['state']
    state_relative = globals().get('S7_STATE_PATH', 'configs/sector7_state.json')
    records = [dict(record) for record in state['artifacts']]
    if state_relative in {item['relative_path'] for item in records}:
        raise ValueError('The Sector 7 catalog may not catalog itself.')
    state_path = root / _s7c_relative(state_relative)
    records.append({'relative_path': state_relative, 'bytes': state_path.stat().st_size,
                    'sha256': _s7c_hash(state_path)})
    if len({item['relative_path'] for item in records}) != len(records):
        raise ValueError('Duplicate path in Sector 7 SSD catalog.')
    expected = {}
    seals = {}
    for record in records:
        relative = record['relative_path']
        path = root / _s7c_relative(relative)
        resolved = path.resolve()
        if root not in resolved.parents or path.is_symlink() or not path.is_file():
            raise ValueError(f'Unsafe SSD artifact: {relative}')
        if (type(record['bytes']) is not int or record['bytes'] < 0
                or not isinstance(record['sha256'], str)
                or not re.fullmatch('[0-9a-f]{64}', record['sha256'])
                or path.stat().st_size != record['bytes']):
            raise ValueError(f'Invalid SSD artifact catalog entry: {relative}')
        seal = _s7c_stat(path)
        if _s7c_hash(path) != record['sha256'] or _s7c_stat(path) != seal:
            raise _S7CloudSourceChanged(f'SSD artifact changed before delivery: {relative}')
        expected[relative] = record
        seals[relative] = seal

    def check_local():
        for relative, seal in seals.items():
            try:
                current = _s7c_stat(root / relative)
            except OSError as exc:
                raise _S7CloudSourceChanged(f'SSD artifact disappeared: {relative}') from exc
            if current != seal:
                raise _S7CloudSourceChanged(f'SSD artifact changed during delivery: {relative}')

    journal = root / '_transfer_state' / 'sector7_cloud_status.json'
    journal.parent.mkdir(parents=True, exist_ok=True)
    report = {'status': 'pending', 'complete': False, 'content_id': state['content_id'],
              'local_root': str(root), 'cloud_root': cloud_root,
              'state_sha256': expected[state_relative]['sha256'],
              'total': len(expected), 'verified': 0, 'pending': len(expected),
              'journal': str(journal), 'proofs': [], 'errors': {}, 'checked_at_utc': None}

    def checkpoint():
        # Saving a journal after an upload is not a new cloud observation.
        report['updated_at_utc'] = datetime.now(timezone.utc).isoformat()
        globals()['SECTOR7_CLOUD_STATUS'] = dict(report)
        temporary = journal.with_suffix('.tmp')
        temporary.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
        os.replace(temporary, journal)

    checkpoint()  # All local validation precedes authentication/network access.
    client = api if api is not None else _s7c_api()
    if isinstance(client, _S7DriveAPI):
        output_parts = _s7c_relative(config.get('sector7', {}).get(
            'local_output_dir', 'outputs/phase2/sector7')).parts
        client._required_prefix_length = len(cloud_parts) - len(output_parts)
    last_attempt = {}
    delivery_errors = {}
    previous_error_summary = None
    with tqdm(total=len(expected), desc='S7 | Cloud SHA-256 confirmed',
              unit='file', dynamic_ncols=True) as progress:
        while True:
            check_local()
            uploaded = False
            try:
                # Refresh the full parent chain, rather than reusing stale folder IDs.
                root_id = client.resolve_root(cloud_parts)
                observed = client.inventory(root_id, list(expected))
                pending = [key for key, record in expected.items()
                           if not _s7c_matches(record, observed.get(key))]
                if not pending:
                    # An independent fresh metadata scan confirms the whole bundle,
                    # including the catalog, before allowing a completed result.
                    root_id = client.resolve_root(cloud_parts)
                    observed = client.inventory(root_id, list(expected))
                    pending = [key for key, record in expected.items()
                               if not _s7c_matches(record, observed.get(key))]
                observed_at = datetime.now(timezone.utc).isoformat()
                verified = len(expected) - len(pending)
                details = {key: {'reason': _s7c_pending_reason(expected[key], observed.get(key)),
                                 'expected_bytes': expected[key]['bytes'],
                                 'cloud_bytes': (observed.get(key) or {}).get('size'),
                                 'expected_sha256': expected[key]['sha256'],
                                 'cloud_sha256': (observed.get(key) or {}).get('sha256Checksum')}
                           for key in pending}
                reasons = dict(Counter(item['reason'] for item in details.values()))
                delivery_errors = {key: value for key, value in delivery_errors.items()
                                   if key in pending}
                progress.n = verified
                progress.set_postfix(pending=len(pending), reasons=reasons, refresh=True)
                report.update(verified=verified, pending=len(pending), pending_paths=pending,
                              pending_reasons=reasons, pending_details=details,
                              errors=dict(delivery_errors), cloud_folder_id=root_id,
                              checked_at_utc=observed_at)
                if not pending:
                    check_local()
                    report.update(status='complete', complete=True,
                                  proofs=[{'relative_path': key, 'bytes': record['bytes'],
                                           'sha256': record['sha256'], 'file_id': observed[key]['id']}
                                          for key, record in expected.items()])
                    checkpoint()
                    persisted['cloud_delivery'] = report
                    return report

                # Metadata catalog publication is deferred until every data artifact
                # is confirmed in a fresh cloud inventory.
                data_pending = [key for key in pending if key != state_relative]
                eligible = data_pending if data_pending else [state_relative]
                now = time.monotonic()
                eligible = [key for key in eligible
                            if now - last_attempt.get(key, float('-inf')) >= retry_seconds]
                checkpoint()
                for relative in tqdm(eligible, desc='S7 | SSD to Drive API', unit='file',
                                     dynamic_ncols=True, leave=False, disable=not eligible):
                    check_local()
                    last_attempt[relative] = time.monotonic()
                    try:
                        client.upload(root_id, relative, root / relative, observed.get(relative))
                        check_local()
                        uploaded = True
                        delivery_errors.pop(relative, None)
                    except (_S7CloudIdentityError, _S7CloudSourceChanged):
                        raise
                    except Exception as exc:
                        delivery_errors[relative] = f'{type(exc).__name__}: {exc}'
                report['errors'] = dict(delivery_errors)
                checkpoint()
                if report['errors']:
                    progress.set_postfix(pending=len(pending), errors=len(report['errors']), refresh=True)
                    summary = next(iter(report['errors'].values()))
                    if summary != previous_error_summary:
                        tqdm.write('S7 | Pending: ' + summary[:240])
                        previous_error_summary = summary
            except (_S7CloudIdentityError, _S7CloudSourceChanged):
                raise
            except Exception as exc:
                # Never turn a timeout, auth failure or stale listing into success.
                report.update(status='pending', complete=False, verified=0,
                              pending=len(expected), proofs=[],
                              errors={'inventory': f'{type(exc).__name__}: {exc}'})
                progress.n = 0
                progress.set_postfix(pending=len(expected), error=type(exc).__name__, refresh=True)
                checkpoint()
                summary = report['errors']['inventory']
                if summary != previous_error_summary:
                    tqdm.write('S7 | Pending: ' + summary[:240])
                    previous_error_summary = summary
            if not uploaded:
                time.sleep(poll_seconds)


def _p7_root(config):
    """Keep the authoritative S7 result bundle on the local SSD."""
    from pathlib import Path, PurePosixPath

    sector = config.get('sector7', {})
    workspace = Path(sector['local_workspace_root']).expanduser()
    relative = PurePosixPath(str(sector.get('local_output_dir', 'outputs/phase2/sector7')))
    if (not workspace.is_absolute() or relative.is_absolute() or
            not relative.parts or any(p in ('..', '.') for p in relative.parts) or
            '\\' in str(relative)):
        raise ValueError('S7 needs an absolute SSD workspace and a safe relative local_output_dir.')
    workspace = workspace.resolve()
    root = (workspace / Path(*relative.parts)).resolve()
    storage = Path(config['storage_root']).expanduser().resolve()
    if (not root.is_relative_to(workspace) or
            workspace.is_relative_to(Path('/content/drive').resolve()) or
            root.is_relative_to(storage)):
        raise ValueError('Sector 7 result root must be on SSD, outside Google Drive.')
    # Resolve the filesystem too: a nonstandard Drive mount must not pass as SSD.
    mounts = Path('/proc/self/mountinfo')
    if mounts.is_file():
        for line in mounts.read_text().splitlines():
            left, separator, right = line.partition(' - ')
            fields = left.split()
            if separator and len(fields) > 4 and 'drive' in right.split()[0].lower():
                mount = Path(fields[4].replace('\\040', ' ').replace('\\134', '\\'))
                if root.is_relative_to(mount):
                    raise ValueError('Sector 7 result root resolves to a Drive filesystem.')
    return root


def _s7c_require_delivery(persisted, config):
    """Bind publication permission to this exact completed SSD/cloud snapshot."""
    from pathlib import Path
    import hashlib

    root_value = persisted.get('local_root', persisted.get('root'))
    if not root_value or Path(root_value).resolve() != _p7_root(config):
        raise RuntimeError('Persist Sector 7 on SSD first; the old Drive-backed result cannot be published.')
    proof = persisted.get('cloud_delivery')
    state = persisted.get('state', {})
    if not isinstance(proof, dict) or proof.get('status') != 'complete':
        raise RuntimeError('Sector 7 cloud SHA-256 confirmation is pending; run io_sync_sector7_cloud first.')
    state_path = Path(root_value) / S7_STATE_PATH
    state_sha = hashlib.sha256(state_path.read_bytes()).hexdigest()
    if (proof.get('content_id') != state.get('content_id') or
            proof.get('local_root') != str(_p7_root(config)) or
            proof.get('cloud_root') != 'MyDrive/' + '/'.join(_s7c_cloud_parts(config)) or
            proof.get('state_sha256') != state_sha):
        raise RuntimeError('Sector 7 cloud proof belongs to a different SSD snapshot; synchronize again.')
    expected = {item['relative_path']: (item['bytes'], item['sha256'])
                for item in state.get('artifacts', [])}
    expected[S7_STATE_PATH] = (state_path.stat().st_size, state_sha)
    records = proof.get('proofs', [])
    observed = {item.get('relative_path'): (item.get('bytes'), item.get('sha256'))
                for item in records if isinstance(item, dict) and item.get('file_id')}
    if (proof.get('complete') is not True or proof.get('pending') != 0 or
            proof.get('total') != len(expected) or proof.get('verified') != len(expected) or
            len(records) != len(expected) or observed != expected):
        raise RuntimeError('Sector 7 cloud proof does not cover this complete SSD catalog.')
    # The original publisher will independently validate every local artifact.
    return proof


# Re-executing this cell must not stack wrappers or clear live QC tables.
_s7_ssd_base_push = getattr(io_push_sector7, '_s7_ssd_base_push', io_push_sector7)


def io_push_sector7(persisted, config):
    """Publish directly from SSD; require cloud confirmation for an actual push."""
    from pathlib import Path

    options = _p7_git_options(config)
    if options['push'] or options['dry_run']:
        value = persisted.get('local_root', persisted.get('root'))
        if not value or Path(value).resolve() != _p7_root(config):
            raise RuntimeError('Save the Sector 7 bundle on SSD before publishing.')
        if options['push'] and not options['dry_run']:
            _s7c_require_delivery(persisted, config)
    return _s7_ssd_base_push(persisted, config)


io_push_sector7._s7_ssd_base_push = _s7_ssd_base_push

## 7. Mount and load one published snapshot

This cell clears stale run variables before loading. It reads metadata from pinned GitHub `main`, verifies the chain and the deferred S6 contract, and prepares persistent media paths. Failure requires correcting the reported upstream problem and rerunning this cell.

In [8]:
# Clear dependent state first: a failed new load must not expose an earlier run.
for _name in ('CONFIG', 'INPUTS', 'LINEAGE', 'SECTOR7_CONTEXT', 'SECTOR7_RUN',
              'SECTOR7_TABLES', 'TABLES', 'SECTOR7_PERSISTED', 'SECTOR7_PUBLICATION',
              'PROCESSING_SIGNATURE'):
    globals().pop(_name, None)
STORAGE_STATUS = io_mount_storage(BOOTSTRAP)
SECTOR7_CONTEXT = io_load_sector7_context(BOOTSTRAP, SECTOR7_SETTINGS)
CONFIG = SECTOR7_CONTEXT['config']
INPUTS = SECTOR7_CONTEXT['inputs']
LINEAGE = SECTOR7_CONTEXT['lineage']
validate_image_qc_config(CONFIG)
display(pd.DataFrame([
    {'sector': sector, 'table': name, 'rows': len(table)}
    for sector, tables in INPUTS.items() if isinstance(tables, dict)
    for name, table in tables.items() if isinstance(table, pd.DataFrame)
]))
if 'config_inheritance_report' in LINEAGE:
    display(LINEAGE['config_inheritance_report'])
print('PASS: pinned published chain and deferred S6 contract verified.')

Mounted at /content/drive

     sector                                  table    rows
0   sector2                 df_alignment_confirmed   47239
1   sector2               frame_alignment_excluded       0
2   sector2                           decode_audit     117
3   sector2                         video_manifest     117
4   sector3                labelled_frame_manifest   47239
5   sector3                   video_frame_manifest     117
6   sector3                     video_class_matrix      43
7   sector3                    video_class_support     117
8   sector4     labelled_frame_manifest_with_split   47239
9   sector4                   video_split_manifest     129
10  sector4                   frame_split_manifest   47229
11  sector5               finding_segment_manifest   22220
12  sector5  labelled_frame_manifest_with_segments   47239
13  sector5        split_class_distribution_report      42
14  sector6              extracted_temporal_frames   18889
15  sector6           temporal_extraction_failures       0
16  sector6           temporal_extraction_requests   18889
17  sector6                   temporal_image_audit   61329
18  sector6                      temporal_manifest  110666
19  sector6                 temporal_status_report      27
20  sector6                 temporal_window_report   22220

,config_key,effective_value_json,resolution
0,qc_enabled,true,sector7_override
1,qc_fov_radius_fraction,0.95,declared_sector7_default
2,qc_underexposed_pixel_threshold,20,declared_sector7_default
3,qc_overexposed_pixel_threshold,240,declared_sector7_default
4,qc_specular_value_threshold,240,declared_sector7_default
5,qc_specular_saturation_threshold,30,declared_sector7_default
6,qc_blur_quantile,0.01,declared_sector7_default
7,qc_contrast_quantile,0.01,declared_sector7_default
8,qc_brightness_low_quantile,0.01,declared_sector7_default
9,qc_brightness_high_quantile,0.99,declared_sector7_default
10,qc_threshold_fit_split,"""deferred""",sector7_override
11,qc_workers,16,sector7_override
12,qc_staging_workers,32,sector7_override
13,qc_checkpoint_batch_size,1000,declared_sector7_default
14,qc_staging_reserve_bytes,2147483648,declared_sector7_default
15,qc_max_image_bytes,67108864,declared_sector7_default
16,qc_decoder,"""nvimagecodec""",sector7_override
17,qc_gpu_backend_policy,"""gpu_preferred""",sector7_override
18,qc_gpu_id,0,sector7_override
19,qc_decode_batch_size,64,sector7_override

PASS: pinned published chain and deferred S6 contract verified.

## 8. Verify/stage media, then reuse or resume QC

Every distinct image must match its committed reference before reuse or decoding. Rerunning this cell reuses verified SSD copies and complete metric checkpoints. A newly started Colab runtime needs staging again because `/content` is ephemeral. No final split is assigned.

In [9]:
for _name in ('SECTOR7_RUN', 'SECTOR7_TABLES', 'TABLES', 'PROCESSING_SIGNATURE',
              'SECTOR7_PERSISTED', 'SECTOR7_PUBLICATION'):
    globals().pop(_name, None)
SECTOR7_RUN = io_prepare_sector7(INPUTS, CONFIG, SECTOR7_CONTEXT['lineage'], globals())
TABLES = SECTOR7_TABLES = SECTOR7_RUN['tables']
LINEAGE = SECTOR7_RUN['lineage']
PROCESSING_SIGNATURE = SECTOR7_RUN['processing_signature']
print('Sector 7 execution:', SECTOR7_RUN['status'])
print('QC checkpoints:', SECTOR7_RUN['checkpoint_progress'])
display(pd.DataFrame([SECTOR7_RUN['gpu_execution']]))
display(TABLES['image_qc_summary'])
display(TABLES['image_qc_thresholds'])
display(TABLES['image_qc_manifest'].head())
print('Hash-verified images with decoding failures:', len(TABLES['image_read_failure_report']))
display(TABLES['image_read_failure_report'].head(20))
print('Missing/pending reference rows:', len(TABLES['missing_image_reference_report']))
print('Final splits: pending. Training ready: False. Quantile calibration: deferred.')

Verify/stage S7 on SSD (32 workers):   0%|          | 0/66127 [00:00<?, ?image/s]

S7 source integrity passed: 66127 images; 0 verified SSD images reused; 66127 images copied; 32 staging workers; 33.41 images/s.
Sector 7 local cache failed validation; QC will be recomputed. Existing files are retained until a replacement is verified.

Resumable QC parts:   0%|          | 0/67 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/16 [00:00<?, ?it/s]

GPU-preferred image QC batches:   0%|          | 0/2 [00:00<?, ?it/s]

Sector 7 execution: computed
QC checkpoints: {'reused_images': 0, 'computed_images': 66127}

,device_id,device_name,cuda_available,nvimagecodec_available,decoder,backends,hybrid_backends,sample_format,apply_exif_orientation,cpu_decode_fallback,pixel_processing,unavailable_reason,compute_capability,cuda_runtime_version,cuda_driver_version
0,0,NVIDIA L4,True,True,nvimagecodec/nvjpeg with OpenCV fallback,"[HW_GPU_ONLY, GPU_ONLY]",[HYBRID_CPU_GPU],I_RGB,False,True,cupy preferred; numpy fallback,None,"[8, 9]",12090,13000

,qc_status,total_unique_images,readable_images,unreadable_images,review_required_images,technically_usable_images,model_usable_images,training_ready,split_assignment_status,qc_assessment_status,threshold_calibration_status,threshold_fit_split,calibration_candidate_images,calibration_readable_images,nvidia_gpu_decoded_images,nvidia_hybrid_decoded_images,cpu_decoded_images,gpu_qc_images,cpu_qc_images,fallback_images
0,completed,66127,66127,0,0,66127,0,False,pending,metrics_only_final_split_pending,deferred_final_split_pending,deferred,0,0,66127,0,0,66127,0,0

,blur_laplacian_lower_threshold,contrast_std_lower_threshold,brightness_mean_lower_threshold,brightness_mean_upper_threshold,threshold_calibration_status,threshold_fit_split,calibration_candidate_images,calibration_readable_images,total_readable_images
0,<NA>,<NA>,<NA>,<NA>,deferred_final_split_pending,deferred,0,0,66127

,image_relpath,image_path,physical_frame_id,video_key,opencv_frame_index,upstream_splits_json,upstream_split_count,final_split,split_assignment_status,used_by_labelled_manifest,...,qc_low_brightness_outlier,qc_high_brightness_outlier,qc_thresholds_calibrated,qc_requires_review,image_technically_usable,training_ready,image_usable_for_modelling,qc_assessment_status,qc_verified_source_sha256,qc_source_matches_upstream
0,curated/phase2/temporal_frames/04a78ef00c5245e...,/content/drive/MyDrive/MMVQA_Clinical/curated/...,"[""04a78ef00c5245e0"",827]",04a78ef00c5245e0,827,"[""train""]",1,<NA>,pending,False,...,<NA>,<NA>,False,False,True,False,False,metrics_only_final_split_pending,b9511350f4e010390b3e86cf7e519b1dcc63876023a183...,True
1,curated/phase2/temporal_frames/04a78ef00c5245e...,/content/drive/MyDrive/MMVQA_Clinical/curated/...,"[""04a78ef00c5245e0"",828]",04a78ef00c5245e0,828,"[""test""]",1,<NA>,pending,False,...,<NA>,<NA>,False,False,True,False,False,metrics_only_final_split_pending,7df5d2e23e715508574f19fe19b4c983c3c3022fe00803...,True
2,curated/phase2/temporal_frames/04a78ef00c5245e...,/content/drive/MyDrive/MMVQA_Clinical/curated/...,"[""04a78ef00c5245e0"",830]",04a78ef00c5245e0,830,"[""train""]",1,<NA>,pending,False,...,<NA>,<NA>,False,False,True,False,False,metrics_only_final_split_pending,05292eb645ed817dcf214f24c10ee8ab3a4186fd554b45...,True
3,curated/phase2/temporal_frames/04a78ef00c5245e...,/content/drive/MyDrive/MMVQA_Clinical/curated/...,"[""04a78ef00c5245e0"",831]",04a78ef00c5245e0,831,"[""validation""]",1,<NA>,pending,False,...,<NA>,<NA>,False,False,True,False,False,metrics_only_final_split_pending,021a430a46c5b6b43942b13191e76e048ee0eaf00dd8dc...,True
4,curated/phase2/temporal_frames/04a78ef00c5245e...,/content/drive/MyDrive/MMVQA_Clinical/curated/...,"[""04a78ef00c5245e0"",832]",04a78ef00c5245e0,832,"[""test""]",1,<NA>,pending,False,...,<NA>,<NA>,False,False,True,False,False,metrics_only_final_split_pending,61dda6c4fa0492654d4a1d7cad9a5aa04882eceb907e11...,True

Hash-verified images with decoding failures: 0

Empty DataFrame
Columns: [image_relpath, image_path, physical_frame_id, image_read_error, used_by_labelled_manifest, used_by_temporal_manifest]
Index: []

Missing/pending reference rows: 0
Final splits: pending. Training ready: False. Quantile calibration: deferred.

## 9. Persist and verify the complete QC bundle

Persist only after the previous cell succeeds. This cell rechecks the local source snapshot, writes/readbacks typed tables, and installs the catalog last with interruption recovery. Image bytes remain unchanged. A failed save clears the publication handle; rerun this cell after fixing the cause.

In [36]:
for _name in (
    "SECTOR7_PERSISTED",
    "SECTOR7_PUBLICATION",
    "SECTOR7_CLOUD",
    "SECTOR7_CLOUD_STATUS",
):
    globals().pop(_name, None)

SECTOR7_PERSISTED = io_persist_sector7(TABLES, CONFIG, LINEAGE)
print("Results are saved on the SSD:", SECTOR7_PERSISTED["local_root"])

SECTOR7_CLOUD = io_sync_sector7_cloud(SECTOR7_PERSISTED, CONFIG)

print("Cloud:", SECTOR7_CLOUD["status"])
print(
    "Confirmed files having same SHA-256:",
    SECTOR7_CLOUD["verified"],
    "/",
    SECTOR7_CLOUD["total"],
)

S7 | Validating configurations, sources and existing results...

S7 | Table stamps:   0%|          | 0/10 [00:00<?, ?table/s]

S7 | Verify SHA-256 SSD images:   0%|          | 0/66127 [00:00<?, ?image/s]

Results are saved on the SSD: /content/mmvqa_sector7/outputs/phase2/sector7

S7 | Cloud SHA-256 confirmed:   0%|          | 0/26 [00:00<?, ?file/s]

S7 | SSD to Drive API:   0%|          | 0/15 [00:00<?, ?file/s]

S7 | SSD to Drive API:   0%|          | 0/1 [00:00<?, ?file/s]

Cloud: complete
Confirmed files having same SHA-256: 26 / 26

## 10. Optional publication — disabled by default

The default `push=False` validates and saves without uploading. To publish after reviewing the results, set `SECTOR7_SETTINGS["push"]=True` and rerun sections 7–10; verified image/QC caches remain reusable. Set the Colab secret `GITHUB_TOKEN` with repository write access. Publication touches only selected S7 metadata and preserves unrelated files, including maintained documentation.

If consumed upstream metadata changed on `main`, rerun input loading and QC against the compatible current chain. Do not bypass the lineage check or merge stale result files manually.

In [37]:
CONFIG["sector7"].update(
    push=True,
    dry_run=False,
)

print("push:", CONFIG["sector7"]["push"])
print("dry_run:", CONFIG["sector7"]["dry_run"])

push: True
dry_run: False

In [38]:
print(f'{SECTOR7_SETTINGS["push"]}')
globals().pop('SECTOR7_PUBLICATION', None)
SECTOR7_PUBLICATION = io_push_sector7(SECTOR7_PERSISTED, CONFIG)
print(SECTOR7_PUBLICATION)

True
{'status': 'published', 'branch': 'main', 'export_dir': 'outputs/phase2/sector7', 'pushed': True, 'dry_run': False, 'count': 26, 'remote_tip': 'add681376ab71d068e98337093d44d0818d4e140', 'changed_paths': ['outputs/phase2/sector7/configs/sector7_config_20261023T005643407465Z.json', 'outputs/phase2/sector7/configs/sector7_lineage.json', 'outputs/phase2/sector7/configs/sector7_state.json', 'outputs/phase2/sector7/reports/executive_report_20261023T005643407465Z.md', 'outputs/phase2/sector7/reports/image_qc_source_audit_20261023T005643407465Z.parquet', 'outputs/phase2/sector7/reports/image_qc_source_audit_20261023T005643407465Z_schema.json', 'outputs/phase2/sector7/reports/image_qc_summary_20261023T005643407465Z.csv', 'outputs/phase2/sector7/reports/image_qc_summary_20261023T005643407465Z.parquet', 'outputs/phase2/sector7/reports/image_qc_summary_20261023T005643407465Z_schema.json', 'outputs/phase2/sector7/reports/image_read_failure_report_20261023T005643407465Z.parquet', 'outputs/phase2/sector7/reports/image_read_failure_report_20261023T005643407465Z_schema.json', 'outputs/phase2/sector7/reports/missing_image_reference_report_20261023T005643407465Z.parquet', 'outputs/phase2/sector7/reports/missing_image_reference_report_20261023T005643407465Z_schema.json', 'outputs/phase2/sector7/reports/qc_reference_report_20261023T005643407465Z.parquet', 'outputs/phase2/sector7/reports/qc_reference_report_20261023T005643407465Z_schema.json', 'outputs/phase2/sector7/reports/summary_20261023T005643407465Z.json', 'outputs/phase2/sector7/results/image_qc_inventory.parquet', 'outputs/phase2/sector7/results/image_qc_inventory_schema.json', 'outputs/phase2/sector7/results/image_qc_manifest.parquet', 'outputs/phase2/sector7/results/image_qc_manifest_schema.json', 'outputs/phase2/sector7/results/image_qc_thresholds.parquet', 'outputs/phase2/sector7/results/image_qc_thresholds_schema.json', 'outputs/phase2/sector7/results/labelled_frame_manifest_with_qc.parquet', 'outputs/phase2/sector7/results/labelled_frame_manifest_with_qc_schema.json', 'outputs/phase2/sector7/results/temporal_manifest_with_qc.parquet', 'outputs/phase2/sector7/results/temporal_manifest_with_qc_schema.json'], 'attempt': 1, 'commit': 'ef44f481ea6ed653246adae876e043df04fd0dca'}

## Output contract for later sectors

The result tables are `image_qc_inventory`, `image_qc_manifest`, `image_qc_thresholds`, `labelled_frame_manifest_with_qc` and `temporal_manifest_with_qc`. Reports cover source hashes/provenance, reference coverage, unreadable images, pending/missing references and the overall QC summary. Catalog-selected schemas, configuration and lineage accompany them.

Consumers must verify the S7 catalog/table hashes and verify staged image bytes against the recorded SHA-256. Preserve every annotation/reference and propagate `upstream_split` only as historical provenance. All outputs remain `final_split=null`, `split_assignment_status=pending`, `training_ready=false`; readable images and completed QC are not training authorization.

Final partitioning is a later explicit policy over physical-frame identities and selected complete examples. Once it is validated, train-dependent thresholds must be fitted separately on that final training set. S7 does not implement the earlier illustrative 332-group split, generate crops/collages, change source annotations, or declare unlabelled context normal.